"use client";

import { GameRulesGuide } from "@/app/games/_components/GameRulesGuide";

export type PhoneGameRulesId="on-my-list"|"how-close"|"chain-reaction"|"inside-man"|"holdem"|"trivia";

const RULES={
  "on-my-list":{gameName:"On My List",goal:"Know the Surveyed Player well enough to uncover the answers on their private ranked list.",turns:["The Surveyed Player gets a prompt and privately enters 5–10 answers, strongest first. If the prompt does not fit them, they can choose a different question before submitting.","Guessers take turns saying one guess out loud.","If it is on the list, tap GOT IT! and the Surveyed Player reveals the matching answer. If not, tap MISS.","Two misses knocks a guesser out for that board only. Then a new player becomes Surveyed."],scoring:["Every completed board has the same 55 total points available, whether it contains 5 answers or 10.","Higher-ranked answers are worth more points than lower-ranked answers.","Only the player who uncovers an answer earns its points."],ending:"Each player gets two turns as the Surveyed Player. Highest total score wins.",example:"Prompt: List things Tyler would want on a stranded island. Tyler ranks Phone #1, Knife #2, Water #3… If you guess Phone, you earn the highest-value answer."},
  "how-close":{gameName:"How Close Are We?",goal:"Guess the number the Spotlight Player will honestly choose about themselves.",turns:["One player is placed in the Spotlight and everyone sees a 1–100 question about them.","The Spotlight Player secretly chooses their true answer.","Everyone else secretly guesses the number they think the Spotlight Player chose.","When everyone locks in, all guesses and the true number are revealed. Then the Spotlight rotates."],scoring:["Exact match = 3 points.","Within 5 = 2 points.","Within 10 = 1 point.","More than 10 = 0 points. The Spotlight Player does not score on their own question."],ending:"Everyone gets two Spotlight turns. Highest total score wins.",example:"Tyler chooses 78. You guess 81, so you are 3 away and score 2 points."},
  "chain-reaction":{gameName:"Chain Reaction",goal:"If you are the Secret Player, quietly steer the word chain toward your private Target Word without giving yourself away.",turns:["One player secretly receives the Target Word.","Players rotate, adding one word or short phrase that reasonably connects to the previous one.","The Secret Player participates normally while trying to guide the chain toward the target.","The round ends when the target is reached or the chain reaches 20 links. A rejected connection is erased and that player gets one retry."],scoring:["Another player says the Target Word within 20 links: Secret Player +3.","The player who actually lands on the Target Word gets +1.","If the Secret Player uses their own Target Word as a legitimate connection, they get +1.","No target within 20 links = 0 for the Secret Player."],ending:"Play through the game’s rounds; the player with the highest total score wins.",example:"Target: CHRISTMAS. The chain moves DOG → BARK → TREE → CHRISTMAS. The Secret Player scores 3 and the player who said CHRISTMAS scores 1."},
  "inside-man":{gameName:"The Inside Man",goal:"Crew players try to complete missions while the hidden Inside Man secretly pushes the group toward their private sabotage objective.",turns:["Everyone receives a private role. One player is the Inside Man; the others are Crew.","Read the mission and discuss the group decision face-to-face. Crew may also have private side objectives.","Vote on the mission choice and watch the success/failure result.","Use accusations carefully. A wrong conviction helps the Inside Man, and nobody is eliminated from play."],scoring:["Mission outcomes move the match toward Crew or Inside Man victory.","Private objectives and accusation results can affect the score or advantage.","Keep your role and private objective secret until the reveal."],ending:"The match runs across five missions and ends when the game’s win condition is reached, followed by a full role reveal.",example:"The mission may ask the group to save limited supplies while the Inside Man secretly needs a particular item left behind. They must influence the discussion without looking suspicious."},
  "holdem":{gameName:"Phone Hold’em",goal:"Win virtual chips by making the best five-card poker hand or getting everyone else to fold.",turns:["Each phone privately receives two hole cards. Shared community cards appear for everyone.","When it is your turn, choose the available poker action: check, call, bet/raise, or fold.","Betting moves through preflop, flop, turn, and river as players remain in the hand.","At showdown, the server compares the remaining hands and awards the pot, including side pots when needed."],scoring:["Poker chips are virtual game chips only.","Win the pot by having the best hand at showdown or by being the last player who has not folded.","Standard Texas Hold’em hand rankings apply."],ending:"Cash-style play continues until the table stops. Tournament play continues until one player has all the chips.",example:"Your A♠ K♠ plus a board of Q♠ J♠ 10♠ 4♦ 2♣ makes a royal flush — the best possible hand."},
  "trivia":{gameName:"Play Point Trivia",goal:"Answer questions correctly and outscore the rest of the table.",turns:["Join the host’s trivia game on your phone.","Read each question and submit your answer before the round advances.","Answers are revealed and the scoreboard updates.","Keep playing through the selected question set."],scoring:["Correct answers earn the points assigned by the trivia game.","The scoreboard tracks each player across the full game."],ending:"After the final question, the player with the highest score wins.",example:"A question appears on everyone’s phone, you lock in your answer, then the game reveals the correct answer and updates the standings."}
} as const;

export function PhoneGameRules({game,className=""}:{game:PhoneGameRulesId;className?:string}){const r=RULES[game];return <GameRulesGuide {...r} className={className}/>}
