"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { RoomJoinPanel } from "@/app/games/_components/RoomJoinPanel";

type Player={id:string;name:string;seat:number;score:number;accusationUsed:boolean;role?:"crew"|"inside_man"};
type Scenario={id:string;title:string;setup:string;choices:string[];pick:number;required:number[]};
type Game={code:string;phase:"lobby"|"mission"|"reveal"|"accusation"|"trial"|"finished";players:Player[];round:number;maxRounds:number;missionVotes:Record<string,number[]>;groupSelection:number[];missionSuccess:boolean|null;crewPoints:number;sabotagePoints:number;accusations:Record<string,string|null>;trialTargetId:string|null;trialVotes:Record<string,"guilty"|"not_guilty">;message:string;winner:"crew"|"inside_man"|null;scenario:Scenario;submittedCount:number;accusedCount:number;trialVoteCount:number;insideManId:string|null;me:{id:string;isHost:boolean;role:"crew"|"inside_man";objective:string}|null};
type Session={code:string;playerId:string;token:string};
const KEY="pps-inside-man-session";

export function InsideManClient(){
  const[game,setGame]=useState<Game|null>(null),[session,setSession]=useState<Session|null>(null),[name,setName]=useState(""),[code,setCode]=useState(""),[selected,setSelected]=useState<number[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const request=useCallback(async(url:string,init?:RequestInit)=>{const r=await fetch(url,{...init,cache:"no-store",headers:{"content-type":"application/json",...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Something went wrong.");return j},[]);
  const store=(s:Session,g:Game)=>{localStorage.setItem(KEY,JSON.stringify(s));setSession(s);setGame(g)};
  useEffect(()=>{const q=new URLSearchParams(location.search).get("code");if(q)setCode(q.toUpperCase());try{const raw=localStorage.getItem(KEY);if(raw)setSession(JSON.parse(raw))}catch{}},[]);
  const refresh=useCallback(async()=>{if(!session)return;try{const j=await request(`/api/games/inside-man/${session.code}?playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);setGame(j.state)}catch(e){setError(e instanceof Error?e.message:"Unable to refresh.")}},[request,session]);
  useEffect(()=>{if(!session)return;refresh();const t=setInterval(refresh,1800);return()=>clearInterval(t)},[refresh,session]);
  useEffect(()=>{setSelected([])},[game?.round,game?.phase]);
  const open=async(intent:"create"|"join")=>{setBusy(true);setError("");try{const j=await request("/api/games/inside-man",{method:"POST",body:JSON.stringify({intent,name,code})});store({code:j.code,playerId:j.playerId,token:j.token},j.state)}catch(e){setError(e instanceof Error?e.message:"Unable to open room.")}finally{setBusy(false)}};
  const act=async(action:string,payload:Record<string,unknown>={})=>{if(!session)return;setBusy(true);setError("");try{const j=await request(`/api/games/inside-man/${session.code}`,{method:"POST",body:JSON.stringify({playerId:session.playerId,token:session.token,action,payload})});setGame(j.state)}catch(e){setError(e instanceof Error?e.message:"Unable to update game.")}finally{setBusy(false)}};
  const joinUrl=typeof location!=="undefined"?`${location.origin}/games/inside-man?code=${game?.code??code}`:"";
  const myPlayer=game&&session?game.players.find(p=>p.id===session.playerId):null;
  const trialTarget=game?.players.find(p=>p.id===game.trialTargetId);
  const hasMissionVote=!!(session&&game?.missionVotes[session.playerId]);
  const hasAccused=session&&game?game.accusations[session.playerId]!==undefined:false;
  const hasTrialVote=session&&game?!!game.trialVotes[session.playerId]:false;
  const sortedScores=useMemo(()=>game?[...game.players].sort((a,b)=>b.score-a.score):[],[game]);

  if(!game)return <main className="px-5 py-10 sm:px-8"><div className="mx-auto max-w-xl"><div className="rounded-[32px] border border-rose-300/20 bg-rose-300/[0.06] p-7"><div className="text-xs font-black uppercase tracking-[.24em] text-rose-200">Play Point Games</div><h1 className="mt-3 text-5xl font-black tracking-tight text-white">The Inside Man</h1><p className="mt-4 text-white/65">Complete the missions. Read the room. One player is secretly steering the table toward failure.</p><input className="mt-7 w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-lg text-white" placeholder="Your first name" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()} onClick={()=>open("create")} className="mt-3 w-full rounded-2xl bg-rose-300 px-5 py-4 font-black text-slate-950 disabled:opacity-40">CREATE PRIVATE ROOM</button><div className="my-5 text-center text-xs font-black uppercase tracking-widest text-white/35">or join a table</div><input className="w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-center text-xl font-black uppercase tracking-[.3em] text-white" placeholder="ROOM CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button disabled={busy||!name.trim()||code.length!==6} onClick={()=>open("join")} className="mt-3 w-full rounded-2xl border border-white/15 px-5 py-4 font-black text-white disabled:opacity-40">JOIN GAME</button>{error&&<p className="mt-4 text-sm text-rose-200">{error}</p>}</div></div></main>;

  return <main className="px-4 py-7 sm:px-8"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-rose-200">The Inside Man</div><div className="mt-1 text-sm text-white/50">Room <b className="text-white">{game.code}</b></div></div><div className="text-right text-xs text-white/45">Mission {Math.min(game.round+1,game.maxRounds)}/{game.maxRounds}</div></header>

  <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{game.players.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="truncate text-sm font-bold text-white">{p.name}{p.id===session?.playerId?" · You":""}</div><div className="mt-1 text-xs text-white/45">Side goals: <b className="text-white">{p.score}</b>{p.accusationUsed?" · accusation used":""}</div></div>)}</div>

  {game.phase==="lobby"&&<section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black text-white">Build the room</h2><p className="mt-2 text-sm leading-6 text-white/60">Best with 4–10 players. The host needs an account; guests join instantly.</p><RoomJoinPanel code={game.code} joinUrl={joinUrl} gameName="The Inside Man"/><div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/58">Phones reveal the secrets. The actual game happens face-to-face: argue, persuade, bluff, and watch who keeps steering the table.</div>{game.me?.isHost?<button disabled={busy||game.players.length<4} onClick={()=>act("start")} className="mt-4 w-full rounded-2xl bg-rose-300 px-4 py-4 font-black text-slate-950 disabled:opacity-40">ASSIGN ROLES & START</button>:<p className="mt-4 text-center text-sm text-white/50">Waiting for the host to start…</p>}</section>}

  {game.phase!=="lobby"&&<><section className={`mt-6 rounded-[30px] border p-6 ${game.me?.role==="inside_man"?"border-rose-300/25 bg-rose-300/10":"border-cyan-300/15 bg-cyan-300/[0.06]"}`}><div className="text-xs font-black uppercase tracking-[.22em] text-white/45">Your secret role</div><div className="mt-2 text-3xl font-black text-white">{game.me?.role==="inside_man"?"INSIDE MAN":"CREW"}</div><p className="mt-3 text-sm leading-6 text-white/70">{game.me?.role==="inside_man"?"Blend in. Help the table sound reasonable while quietly pushing the mission toward your sabotage target.":"Complete the mission—but remember, innocent players also have private objectives that can make them look suspicious."}</p><div className="mt-4 rounded-2xl bg-black/25 p-4 text-sm font-bold leading-6 text-white">{game.me?.objective}</div></section>

  <section className="mt-4 rounded-[30px] border border-white/10 bg-white/[.035] p-6"><div className="text-xs font-black uppercase tracking-[.2em] text-amber-100/70">Mission {game.round+1}</div><h2 className="mt-2 text-3xl font-black text-white">{game.scenario.title}</h2><p className="mt-3 text-base leading-7 text-white/65">{game.scenario.setup}</p><div className="mt-5 flex items-center justify-between text-xs font-black uppercase tracking-widest text-white/45"><span>Crew {game.crewPoints}/3</span><span>Inside Man {game.sabotagePoints}/3</span></div><div className="mt-2 grid grid-cols-3 gap-2">{[0,1,2].map(i=><div key={i} className={`h-2 rounded-full ${i<game.crewPoints?"bg-cyan-300":"bg-white/10"}`}/> )}</div><div className="mt-2 grid grid-cols-3 gap-2">{[0,1,2].map(i=><div key={i} className={`h-2 rounded-full ${i<game.sabotagePoints?"bg-rose-300":"bg-white/10"}`}/> )}</div></section>

  {game.phase==="mission"&&<section className="mt-4 rounded-[28px] border border-white/10 bg-white/[.03] p-5"><div className="text-center text-xs font-black uppercase tracking-widest text-white/45">Talk first. Then choose exactly {game.scenario.pick}.</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{game.scenario.choices.map((choice,idx)=>{const on=selected.includes(idx);return <button key={choice} disabled={hasMissionVote} onClick={()=>setSelected(prev=>on?prev.filter(x=>x!==idx):prev.length<game.scenario.pick?[...prev,idx]:prev)} className={`rounded-2xl border px-4 py-4 text-left font-bold ${on?"border-cyan-300/60 bg-cyan-300/15 text-white":"border-white/10 bg-black/15 text-white/75"}`}>{choice}</button>})}</div>{hasMissionVote?<p className="mt-4 text-center text-sm text-white/55">Locked. {game.submittedCount}/{game.players.length} players have voted.</p>:<button disabled={busy||selected.length!==game.scenario.pick} onClick={()=>act("vote",{picks:selected})} className="mt-4 w-full rounded-2xl bg-cyan-300 px-4 py-4 font-black text-slate-950 disabled:opacity-40">LOCK MY CHOICES</button>}</section>}

  {(game.phase==="reveal"||game.phase==="accusation"||game.phase==="trial"||game.phase==="finished")&&<section className={`mt-4 rounded-[28px] border p-6 ${game.missionSuccess?"border-emerald-300/20 bg-emerald-300/10":"border-rose-300/20 bg-rose-300/10"}`}><div className="text-xs font-black uppercase tracking-widest text-white/50">Group decision</div><div className="mt-3 flex flex-wrap gap-2">{game.groupSelection.map(idx=><span key={idx} className="rounded-2xl bg-black/25 px-4 py-3 font-black text-white">{game.scenario.choices[idx]}</span>)}</div><div className="mt-4 text-2xl font-black text-white">{game.missionSuccess?"MISSION SUCCESS":"MISSION FAILED"}</div><p className="mt-2 text-sm leading-6 text-white/65">{game.message}</p></section>}

  {game.phase==="reveal"&&<section className="mt-4 rounded-[28px] border border-white/10 bg-white/[.03] p-5">{game.me?.isHost?<div className="grid gap-3 sm:grid-cols-2"><button disabled={busy} onClick={()=>act("open_accusations")} className="rounded-2xl border border-amber-300/25 px-4 py-4 font-black text-amber-100">OPEN ACCUSATIONS</button><button disabled={busy} onClick={()=>act("next")} className="rounded-2xl bg-white px-4 py-4 font-black text-slate-950">NEXT MISSION</button></div>:<p className="text-center text-sm text-white/55">Discuss what happened. The host decides whether to open accusations or continue.</p>}</section>}

  {game.phase==="accusation"&&<section className="mt-4 rounded-[28px] border border-amber-300/20 bg-amber-300/[0.07] p-5"><h3 className="text-xl font-black text-white">Do you accuse someone?</h3><p className="mt-2 text-sm leading-6 text-white/60">You get only one real accusation for the entire game. Passing does not spend it.</p>{hasAccused?<p className="mt-4 text-center text-white/55">Decision locked. {game.accusedCount}/{game.players.length}</p>:<div className="mt-4 grid gap-2 sm:grid-cols-2">{game.players.filter(p=>p.id!==session?.playerId).map(p=><button key={p.id} disabled={busy||!!myPlayer?.accusationUsed} onClick={()=>act("accuse",{targetId:p.id})} className="rounded-2xl border border-white/10 px-4 py-3 text-left font-bold text-white disabled:opacity-35">ACCUSE {p.name.toUpperCase()}</button>)}<button disabled={busy} onClick={()=>act("accuse",{targetId:null})} className="rounded-2xl border border-white/10 px-4 py-3 font-bold text-white/70">KEEP WATCHING</button></div>}</section>}

  {game.phase==="trial"&&<section className="mt-4 rounded-[28px] border border-rose-300/25 bg-rose-300/10 p-6 text-center"><div className="text-xs font-black uppercase tracking-widest text-rose-100">Trial</div><h3 className="mt-2 text-3xl font-black text-white">{trialTarget?.name}</h3><p className="mt-2 text-sm leading-6 text-white/65">Defend yourself aloud. Everyone else votes privately.</p>{trialTarget?.id===session?.playerId?<p className="mt-5 text-sm font-bold text-white/60">You are on trial. Make your case.</p>:hasTrialVote?<p className="mt-5 text-sm text-white/55">Vote locked. {game.trialVoteCount}/{Math.max(1,game.players.length-1)}</p>:<div className="mt-5 grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>act("trial_vote",{vote:"guilty"})} className="rounded-2xl bg-rose-300 px-3 py-4 font-black text-slate-950">GUILTY</button><button disabled={busy} onClick={()=>act("trial_vote",{vote:"not_guilty"})} className="rounded-2xl bg-white px-3 py-4 font-black text-slate-950">NOT GUILTY</button></div>}</section>}

  {game.phase==="finished"&&<section className="mt-4 rounded-[30px] border border-white/10 bg-white/[.04] p-7 text-center"><div className="text-xs font-black uppercase tracking-[.22em] text-white/45">Operation complete</div><h2 className="mt-2 text-4xl font-black text-white">{game.winner==="crew"?"THE CREW WINS":"THE INSIDE MAN WINS"}</h2><p className="mt-3 text-white/65">{game.message}</p><div className="mt-6 rounded-2xl border border-rose-300/20 bg-rose-300/10 p-5"><div className="text-xs font-black uppercase tracking-widest text-white/45">The Inside Man was</div><div className="mt-2 text-3xl font-black text-white">{game.players.find(p=>p.id===game.insideManId)?.name??"Unknown"}</div></div><div className="mt-5 text-left"><div className="text-xs font-black uppercase tracking-widest text-white/45">Private objective points</div>{sortedScores.map(p=><div key={p.id} className="mt-2 flex items-center justify-between rounded-xl bg-black/20 px-4 py-3"><span className="font-bold text-white">{p.name}</span><span className="font-black text-cyan-100">{p.score}</span></div>)}</div>{game.me?.isHost&&<button disabled={busy} onClick={()=>act("restart")} className="mt-6 w-full rounded-2xl bg-white px-4 py-4 font-black text-slate-950">PLAY AGAIN</button>}</section>}</>}
  {error&&<p className="mt-4 text-center text-sm text-rose-200">{error}</p>}</div></main>;
}
