"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { RoomJoinPanel } from "@/app/games/_components/RoomJoinPanel";

type Player={id:string;name:string;seat:number;destinations:number;successfulSteps:number;attempts:number};
type Pending={playerId:string;answer:string}|null;
type Game={code:string;status:"lobby"|"playing"|"round_result"|"finished";hostPlayerId:string;players:Player[];round:number;roundsPerPlayer:number;navigatorId:string|null;responderId:string|null;start:string;destination:string|null;path:string[];pending:Pending;answersThisRound:number;maxAnswersThisRound:number;success:boolean|null;message:string;totalRounds:number;me:{id:string;isHost:boolean;isNavigator:boolean;isResponder:boolean}};
type Session={code:string;playerId:string;token:string};
const KEY="pps-get-there-session";

export function GetThereClient(){
 const[game,setGame]=useState<Game|null>(null),[session,setSession]=useState<Session|null>(null),[name,setName]=useState(""),[code,setCode]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const request=useCallback(async(url:string,init?:RequestInit)=>{const r=await fetch(url,{...init,cache:"no-store",headers:{"content-type":"application/json",...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Something went wrong.");return j},[]);
 const store=(s:Session,g:Game)=>{localStorage.setItem(KEY,JSON.stringify(s));setSession(s);setGame(g)};
 useEffect(()=>{const q=new URLSearchParams(location.search).get("code");if(q)setCode(q.toUpperCase());try{const raw=localStorage.getItem(KEY);if(raw)setSession(JSON.parse(raw))}catch{}},[]);
 const refresh=useCallback(async()=>{if(!session)return;try{const j=await request(`/api/games/get-there/${session.code}?playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);setGame(j.state)}catch{}},[request,session]);
 useEffect(()=>{if(!session)return;refresh();const t=setInterval(refresh,1000);return()=>clearInterval(t)},[session,refresh]);
 async function open(intent:"create"|"join"){setBusy(true);setError("");try{const j=await request("/api/games/get-there",{method:"POST",body:JSON.stringify({intent,name,code})});store({code:j.code,playerId:j.playerId,token:j.token},j.state);history.replaceState(null,"",`/games/get-there?code=${j.code}`)}catch(e){setError(e instanceof Error?e.message:"Unable to join.")}finally{setBusy(false)}}
 async function act(action:string,payload:Record<string,unknown>={}){if(!session)return;setBusy(true);setError("");try{const j=await request(`/api/games/get-there/${session.code}`,{method:"POST",body:JSON.stringify({...session,action,payload})});setGame(j.state);if(action==="answer")setAnswer("")}catch(e){setError(e instanceof Error?e.message:"Try again.")}finally{setBusy(false)}}
 const joinUrl=game&&typeof window!=="undefined"?`${window.location.origin}/games/get-there?code=${game.code}`:"";
 const navigator=game?.players.find(p=>p.id===game.navigatorId);const responder=game?.players.find(p=>p.id===game.responderId);
 const standings=useMemo(()=>game?[...game.players].sort((a,b)=>b.destinations-a.destinations||a.successfulSteps-b.successfulSteps||a.seat-b.seat):[],[game]);
 if(!game)return <main className="px-5 py-10 sm:px-8"><div className="mx-auto max-w-xl rounded-[32px] border border-cyan-300/20 bg-cyan-300/[0.06] p-7"><div className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Play Point Family Games</div><h1 className="mt-3 text-5xl font-black tracking-tight text-white">GET THERE</h1><p className="mt-3 text-lg font-bold text-cyan-100">Start the conversation. Hide the destination.</p><p className="mt-4 leading-7 text-white/65">One Navigator secretly knows where the conversation needs to go. Everyone else gives the only roads they are allowed to take.</p><input className="mt-7 w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-lg text-white" placeholder="Your first name" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} onClick={()=>open("create")} className="mt-3 w-full rounded-2xl bg-cyan-300 px-5 py-4 font-black text-slate-950 disabled:opacity-40">CREATE GAME</button><div className="my-5 text-center text-xs font-black uppercase tracking-widest text-white/35">or join a table</div><input className="w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-center text-xl font-black uppercase tracking-[.3em] text-white" placeholder="ROOM CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button disabled={busy} onClick={()=>open("join")} className="mt-3 w-full rounded-2xl border border-white/15 px-5 py-4 font-black text-white">JOIN GAME</button>{error&&<p className="mt-4 text-sm text-rose-200">{error}</p>}</div></main>;
 return <main className="px-4 py-7 sm:px-8"><div className="mx-auto max-w-3xl"><header className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.22em] text-cyan-200">GET THERE</div><div className="mt-1 text-sm text-white/50">Room <b className="text-white">{game.code}</b></div></div><div className="text-right text-xs text-white/45">{game.status==="lobby"?"Lobby":game.status==="finished"?"Finished":`Route ${Math.min(game.round+1,game.totalRounds)} of ${game.totalRounds}`}</div></header>
 <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{standings.map((p,i)=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="truncate text-sm font-bold text-white">{p.name}{p.id===session?.playerId?" · You":""}</div><div className="mt-1 text-2xl font-black text-cyan-100">{p.destinations}</div><div className="text-[11px] text-white/40">destinations · {p.successfulSteps} steps</div>{game.status==="finished"&&<div className="mt-1 text-[10px] font-black uppercase tracking-widest text-white/30">#{i+1}</div>}</div>)}</div>
 {game.status==="lobby"&&<section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black text-white">Get the table in</h2><p className="mt-2 text-sm leading-6 text-white/60">Guests scan the QR code, enter a first name, and join. Three players minimum.</p><RoomJoinPanel code={game.code} joinUrl={joinUrl} gameName="GET THERE"/><div className="mt-4 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] p-4 text-sm leading-6 text-white/65"><b className="text-cyan-100">How it works:</b> the Navigator asks a question using the current route word. Players answer clockwise. After every answer the Navigator must <b>USE</b> it or <b>PASS</b> it forever.</div>{game.me.isHost?<button disabled={busy||game.players.length<3} onClick={()=>act("start")} className="mt-4 w-full rounded-2xl bg-cyan-300 px-4 py-4 font-black text-slate-950 disabled:opacity-40">START GET THERE</button>:<p className="mt-4 text-center text-sm text-white/50">Waiting for the host to start…</p>}</section>}
 {game.status==="playing"&&<><section className="mt-6 rounded-[30px] border border-cyan-300/15 bg-cyan-300/[.06] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.2em] text-white/40">Navigator</div><div className="mt-1 text-xl font-black text-white">{navigator?.name}</div></div><div className="text-right"><div className="text-xs font-black uppercase tracking-[.2em] text-white/40">Answers used / heard</div><div className="mt-1 text-xl font-black text-cyan-100">{game.path.length-1} / {game.answersThisRound}</div></div></div><div className="mt-5 rounded-2xl bg-black/25 p-5 text-center"><div className="text-xs font-black uppercase tracking-[.2em] text-white/40">Current route word</div><div className="mt-2 text-4xl font-black text-white">{game.path[game.path.length-1]}</div></div>{game.me.isNavigator?<div className="mt-4 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-5 text-center"><div className="text-xs font-black uppercase tracking-widest text-amber-100">Your secret destination</div><div className="mt-2 text-4xl font-black text-white">{game.destination}</div><p className="mt-3 text-sm leading-6 text-white/60">Do not say it, spell it, rhyme it, give the first letter, or define it directly.</p></div>:<div className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-center text-sm text-white/55">The destination is hidden. Listen closely—you may be the one who says it.</div>}<p className="mt-4 text-center text-sm font-semibold text-white/65">{game.message}</p></section>
 {!game.pending&&game.me.isResponder&&<section className="mt-4 rounded-[28px] border border-white/10 bg-white/[.035] p-6"><div className="text-xs font-black uppercase tracking-widest text-cyan-200">Your turn to answer</div><h3 className="mt-2 text-2xl font-black text-white">Say your answer out loud first.</h3><p className="mt-2 text-sm leading-6 text-white/55">Then type the key word or short phrase you just said so the route can remember it.</p><input autoFocus className="mt-5 w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-lg text-white" placeholder="What did you say?" value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&answer.trim())act("answer",{answer})}}/><button disabled={busy||!answer.trim()} onClick={()=>act("answer",{answer})} className="mt-3 w-full rounded-2xl bg-cyan-300 px-4 py-4 font-black text-slate-950 disabled:opacity-40">SUBMIT ANSWER</button></section>}
 {!game.pending&&!game.me.isResponder&&!game.me.isNavigator&&<section className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-5 text-center"><div className="text-sm text-white/55">{responder?.name} answers next.</div></section>}
 {game.pending&&game.me.isNavigator&&<section className="mt-4 rounded-[28px] border border-amber-300/20 bg-amber-300/10 p-6 text-center"><div className="text-xs font-black uppercase tracking-widest text-amber-100">Road offered</div><div className="mt-3 text-4xl font-black text-white">{game.pending.answer}</div><p className="mt-3 text-sm leading-6 text-white/60"><b>USE</b> makes it your next route word. <b>PASS</b> sacrifices it forever and lets the next person answer the same question.</p><div className="mt-5 grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>act("pass")} className="rounded-2xl border border-white/20 bg-black/20 px-4 py-4 font-black text-white">PASS</button><button disabled={busy} onClick={()=>act("use")} className="rounded-2xl bg-amber-300 px-4 py-4 font-black text-slate-950">USE</button></div></section>}
 {game.pending&&!game.me.isNavigator&&<section className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-5 text-center text-sm text-white/55">Navigator is deciding whether to use that road or pass it.</section>}</>}
 {game.status==="round_result"&&<section className={`mt-6 rounded-[28px] border p-6 ${game.success?"border-emerald-300/20 bg-emerald-300/10":"border-rose-300/20 bg-rose-300/10"}`}><div className="text-center text-xs font-black uppercase tracking-widest text-white/60">{game.success?"YOU GOT THERE":"ROAD CLOSED"}</div><div className="mt-2 text-center text-4xl font-black text-white">{game.destination}</div><div className="mt-5 flex flex-wrap items-center justify-center gap-2">{game.path.map((word,i)=><div key={`${word}-${i}`} className="flex items-center gap-2"><span className="rounded-xl bg-black/25 px-3 py-2 text-sm font-black text-white">{word}</span>{i<game.path.length-1&&<span className="text-white/35">→</span>}</div>)}</div><p className="mt-4 text-center text-sm text-white/60">{game.success?`${navigator?.name} reached the destination in ${game.path.length-1} steps.`:`${navigator?.name} did not reach the destination before the road limit.`}</p>{(game.me.isHost||game.me.isNavigator)&&<button disabled={busy} onClick={()=>act("next")} className="mt-5 w-full rounded-2xl bg-white px-4 py-4 font-black text-slate-950">NEXT NAVIGATOR</button>}</section>}
 {game.status==="finished"&&<section className="mt-6 rounded-[28px] border border-emerald-300/20 bg-emerald-300/10 p-6"><div className="text-center text-xs font-black uppercase tracking-widest text-emerald-100">Final standings</div><h2 className="mt-2 text-center text-3xl font-black text-white">{standings[0]?.name} got there!</h2><p className="mt-2 text-center text-sm text-white/55">Most destinations wins. Ties go to the player who used the fewest total steps on successful routes.</p><div className="mt-5 space-y-2">{standings.map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-2xl bg-black/20 px-4 py-3"><span className="font-bold text-white">{i+1}. {p.name}</span><span className="text-right"><b className="text-xl text-emerald-100">{p.destinations}</b><span className="ml-2 text-xs text-white/40">· {p.successfulSteps} steps</span></span></div>)}</div>{game.me.isHost&&<button onClick={()=>act("restart")} className="mt-5 w-full rounded-2xl bg-white px-5 py-3 font-black text-slate-950">PLAY AGAIN</button>}</section>}{error&&<p className="mt-4 text-center text-sm text-rose-200">{error}</p>}</div></main>;
}
