import "server-only";

import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { getSupabaseServerClient } from "@/lib/play-point-core/quick-score-supabase";

const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const STARTERS = ["DOG","PIZZA","BEACH","SCHOOL","MUSIC","RAIN","SPACE","BIRTHDAY","CAMPING","CHOCOLATE","FOOTBALL","MOVIE","OCEAN","SUMMER","DINNER","ROAD","PHONE","FAMILY","FIRE","TREE"];
type Player={id:string;name:string;tokenHash:string;score:number;seat:number}; type Link={id:string;word:string;playerId:string|null;createdAt:string}; type Challenge={challengerId:string;linkId:string;votes:Record<string,"counts"|"no_way">}|null; type State={code:string;status:"lobby"|"playing"|"finished";hostPlayerId:string;players:Player[];links:Link[];turnSeat:number;maxLinks:number;challenge:Challenge;message:string}; type Row={code:string;state:State;version:number};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex"); function tokenMatches(expected:string,token:string){const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
function cleanName(v:unknown){const n=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!n||n.length>24)throw new Error("Enter a name up to 24 characters.");return n} function cleanCode(v:unknown){const c=typeof v==="string"?v.trim().toUpperCase():"";if(!/^[A-Z2-9]{6}$/.test(c))throw new Error("Enter a valid 6-character room code.");return c} function cleanWord(v:unknown){const w=typeof v==="string"?v.trim().replace(/\s+/g," ").toUpperCase():"";if(!/^[A-Z][A-Z '-]{0,29}$/.test(w))throw new Error("Enter a word or short phrase up to 30 characters.");return w}
function roomCode(){const b=randomBytes(6);return Array.from(b,x=>ALPHABET[x%ALPHABET.length]).join("")} function playerToken(){return randomBytes(32).toString("base64url")}
async function read(code:string):Promise<Row|null>{const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_chain_reaction_rooms").select("code,state,version").eq("code",code).maybeSingle();if(error)throw new Error(error.message);return data as Row|null} async function save(row:Row,state:State){const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_chain_reaction_rooms").update({state,version:row.version+1,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}).eq("code",row.code).eq("version",row.version).select("code,state,version").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("The table changed. Try again.");return data as Row}
function auth(state:State,id:string,token:string){const p=state.players.find(x=>x.id===id);if(!p||!tokenMatches(p.tokenHash,token))throw new Error("Invalid player session.");return p} function project(state:State,viewer:string){return{...state,players:state.players.map(({tokenHash:_,...p})=>p),me:state.players.find(p=>p.id===viewer)?{id:viewer,isHost:state.hostPlayerId===viewer}:null}}
export async function createChainRoom(nameValue:unknown){const name=cleanName(nameValue);for(let i=0;i<8;i++){const code=roomCode(),token=playerToken(),id=randomUUID();const state:State={code,status:"lobby",hostPlayerId:id,players:[{id,name,tokenHash:hash(token),score:0,seat:0}],links:[],turnSeat:0,maxLinks:20,challenge:null,message:"Invite your family, then start the chain."};const s=getSupabaseServerClient();const{error}=await s.from("ppl_chain_reaction_rooms").insert({code,state,version:1});if(!error)return{code,playerId:id,token,state:project(state,id)}}throw new Error("Unable to create a room.")}
export async function joinChainRoom(codeValue:unknown,nameValue:unknown){const code=cleanCode(codeValue),name=cleanName(nameValue),row=await read(code);if(!row)throw new Error("Room not found.");if(row.state.status!=="lobby")throw new Error("That game has already started.");if(row.state.players.length>=8)throw new Error("That room is full.");const token=playerToken(),id=randomUUID();row.state.players.push({id,name,tokenHash:hash(token),score:0,seat:row.state.players.length});const saved=await save(row,row.state);return{code,playerId:id,token,state:project(saved.state,id)}}
export async function getChainRoom(codeValue:unknown,id:string,token:string){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");auth(row.state,id,token);return{state:project(row.state,id)}}
export async function actChainRoom(codeValue:unknown,id:string,token:string,action:string,payload:Record<string,unknown>={}){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");const state=row.state,me=auth(state,id,token);
if(action==="start"){if(state.hostPlayerId!==id)throw new Error("Only the host can start.");if(state.players.length<2)throw new Error("Invite at least one more player.");const starter=STARTERS[Math.floor(Math.random()*STARTERS.length)];state.links=[{id:randomUUID(),word:starter,playerId:null,createdAt:new Date().toISOString()}];state.turnSeat=Math.floor(Math.random()*state.players.length);state.status="playing";state.message=`Start with ${starter}.`}
else if(action==="word"){if(state.status!=="playing"||state.challenge)throw new Error("The chain is not ready for a word.");if(me.seat!==state.turnSeat)throw new Error("It is not your turn.");const word=cleanWord(payload.word);if(state.links.some(l=>l.word===word))throw new Error("That word is already in this chain.");state.links.push({id:randomUUID(),word,playerId:id,createdAt:new Date().toISOString()});me.score+=1;state.turnSeat=(state.turnSeat+1)%state.players.length;state.message=`${me.name} linked ${word}.`;if(state.links.length-1>=state.maxLinks){state.status="finished";state.message="Chain complete!"}}
else if(action==="challenge"){if(state.status!=="playing"||state.challenge)throw new Error("There is nothing to challenge.");const latest=state.links.at(-1);if(!latest?.playerId||latest.playerId===id)throw new Error("You cannot challenge that link.");state.challenge={challengerId:id,linkId:latest.id,votes:{[id]:"no_way"}};state.message=`${me.name} challenged ${latest.word}.`}
else if(action==="vote"){if(!state.challenge)throw new Error("There is no active challenge.");const vote=payload.vote==="counts"?"counts":payload.vote==="no_way"?"no_way":null;if(!vote)throw new Error("Choose a vote.");const challenged=state.links.find(l=>l.id===state.challenge!.linkId);if(!challenged)throw new Error("Challenged link is missing.");if(challenged.playerId===id)throw new Error("The challenged player does not vote.");state.challenge.votes[id]=vote;const eligible=state.players.filter(p=>p.id!==challenged.playerId).length,needed=Math.floor(eligible/2)+1,counts=Object.values(state.challenge.votes).filter(v=>v==="counts").length,noWay=Object.values(state.challenge.votes).filter(v=>v==="no_way").length;if(counts>=needed){const author=state.players.find(p=>p.id===challenged.playerId);if(author)author.score+=1;state.message=`It counts! ${challenged.word} survives.`;state.challenge=null}else if(noWay>=needed){const author=state.players.find(p=>p.id===challenged.playerId),challenger=state.players.find(p=>p.id===state.challenge!.challengerId);if(author)author.score=Math.max(0,author.score-1);if(challenger)challenger.score+=1;state.links=state.links.filter(l=>l.id!==challenged.id);if(author)state.turnSeat=author.seat;state.message=`No way! ${challenged.word} is removed.`;state.challenge=null}}
else if(action==="restart"){if(state.hostPlayerId!==id)throw new Error("Only the host can restart.");state.status="lobby";state.links=[];state.challenge=null;state.players.forEach(p=>p.score=0);state.message="Ready for another chain."}else throw new Error("Unknown action.");const saved=await save(row,state);return{state:project(saved.state,id)}}
