import "server-only";

import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { getSupabaseServerClient } from "@/lib/play-point-core/quick-score-supabase";

const ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const PAIRS=[
 ["DOG","CHRISTMAS"],["SCHOOL","OCEAN"],["TOOTHBRUSH","FOOTBALL"],["PIZZA","VACATION"],["RAIN","BIRTHDAY"],["COFFEE","MOUNTAIN"],["PHONE","DINOSAUR"],["BEACH","HOMEWORK"],["MUSIC","AIRPLANE"],["TREE","MOVIE"],["BREAKFAST","SPACE"],["CAR","WEDDING"],["CAMPING","CHOCOLATE"],["SHOES","BASEBALL"],["SUMMER","HOSPITAL"],["CAT","THANKSGIVING"],["DINNER","ROLLER COASTER"],["FAMILY","SNOW"],["BOOK","DISNEY"],["GARDEN","CONCERT"]
] as const;
type Player={id:string;name:string;tokenHash:string;seat:number;destinations:number;successfulSteps:number;attempts:number};
type Pending={playerId:string;answer:string}|null;
type State={code:string;status:"lobby"|"playing"|"round_result"|"finished";hostPlayerId:string;players:Player[];round:number;roundsPerPlayer:number;navigatorId:string|null;responderId:string|null;start:string;destination:string;path:string[];pending:Pending;answersThisRound:number;maxAnswersThisRound:number;success:boolean|null;message:string;pairOrder:number[]};
type Row={code:string;state:State;version:number};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function tokenMatches(expected:string,token:string){const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
function cleanName(v:unknown){const n=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!n||n.length>24)throw new Error("Enter a name up to 24 characters.");return n}
function cleanCode(v:unknown){const c=typeof v==="string"?v.trim().toUpperCase():"";if(!/^[A-Z2-9]{6}$/.test(c))throw new Error("Enter a valid 6-character room code.");return c}
function cleanAnswer(v:unknown){const a=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!a||a.length>40)throw new Error("Enter the answer you said at the table.");return a}
function norm(v:string){return v.trim().toUpperCase().replace(/[^A-Z0-9 ]/g,"").replace(/\s+/g," ")}
function roomCode(){const b=randomBytes(6);return Array.from(b,x=>ALPHABET[x%ALPHABET.length]).join("")}
function playerToken(){return randomBytes(32).toString("base64url")}
function shuffleNumbers(n:number){const a=Array.from({length:n},(_,i)=>i);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function read(code:string):Promise<Row|null>{const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_get_there_rooms").select("code,state,version").eq("code",code).maybeSingle();if(error)throw new Error(error.message);return data as Row|null}
async function save(row:Row,state:State){const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_get_there_rooms").update({state,version:row.version+1,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}).eq("code",row.code).eq("version",row.version).select("code,state,version").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("The table changed. Try again.");return data as Row}
function auth(state:State,id:string,token:string){const p=state.players.find(x=>x.id===id);if(!p||!tokenMatches(p.tokenHash,token))throw new Error("Invalid player session.");return p}
function nextNonNavigator(state:State,afterSeat:number){for(let i=1;i<=state.players.length;i++){const p=state.players[(afterSeat+i)%state.players.length];if(p.id!==state.navigatorId)return p}throw new Error("No responder available.")}
function beginRound(state:State){const total=state.players.length*state.roundsPerPlayer;if(state.round>=total){state.status="finished";state.navigatorId=null;state.responderId=null;state.message="Final routes are in.";return}const nav=state.players[state.round%state.players.length];const pair=PAIRS[state.pairOrder[state.round%state.pairOrder.length]%PAIRS.length];state.status="playing";state.navigatorId=nav.id;state.start=pair[0];state.destination=pair[1];state.path=[pair[0]];state.pending=null;state.answersThisRound=0;state.maxAnswersThisRound=Math.max(2,(state.players.length-1)*2);state.success=null;state.responderId=nextNonNavigator(state,nav.seat).id;nav.attempts+=1;state.message=`${nav.name} is navigating. Start with ${pair[0]}.`}
function project(state:State,viewer:string){const me=state.players.find(p=>p.id===viewer);const isNav=state.navigatorId===viewer;const revealDestination=isNav||state.status==="round_result"||state.status==="finished";return{...state,players:state.players.map(({tokenHash:_,...p})=>p),destination:revealDestination?state.destination:null,pending:state.pending&&(isNav||state.pending.playerId===viewer)?state.pending:null,me:me?{id:viewer,isHost:state.hostPlayerId===viewer,isNavigator:isNav,isResponder:state.responderId===viewer}:null,totalRounds:state.players.length*state.roundsPerPlayer}}
export async function createGetThereRoom(nameValue:unknown){const name=cleanName(nameValue);for(let i=0;i<8;i++){const code=roomCode(),token=playerToken(),id=randomUUID();const state:State={code,status:"lobby",hostPlayerId:id,players:[{id,name,tokenHash:hash(token),seat:0,destinations:0,successfulSteps:0,attempts:0}],round:0,roundsPerPlayer:3,navigatorId:null,responderId:null,start:"",destination:"",path:[],pending:null,answersThisRound:0,maxAnswersThisRound:0,success:null,message:"Invite the table. One player will know where the conversation needs to go.",pairOrder:shuffleNumbers(PAIRS.length)};const s=getSupabaseServerClient();const{error}=await s.from("ppl_get_there_rooms").insert({code,state,version:1});if(!error)return{code,playerId:id,token,state:project(state,id)}}throw new Error("Unable to create a room.")}
export async function joinGetThereRoom(codeValue:unknown,nameValue:unknown){const code=cleanCode(codeValue),name=cleanName(nameValue),row=await read(code);if(!row)throw new Error("Room not found.");if(row.state.status!=="lobby")throw new Error("That game has already started.");if(row.state.players.length>=8)throw new Error("That room is full.");const token=playerToken(),id=randomUUID();row.state.players.push({id,name,tokenHash:hash(token),seat:row.state.players.length,destinations:0,successfulSteps:0,attempts:0});const saved=await save(row,row.state);return{code,playerId:id,token,state:project(saved.state,id)}}
export async function getGetThereRoom(codeValue:unknown,id:string,token:string){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");auth(row.state,id,token);return{state:project(row.state,id)}}
export async function actGetThereRoom(codeValue:unknown,id:string,token:string,action:string,payload:Record<string,unknown>={}){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");const state=row.state;auth(state,id,token);
 if(action==="start"){if(state.hostPlayerId!==id)throw new Error("Only the host can start.");if(state.players.length<3)throw new Error("GET THERE works best with at least 3 players.");state.round=0;state.players.forEach(p=>{p.destinations=0;p.successfulSteps=0;p.attempts=0});state.pairOrder=shuffleNumbers(PAIRS.length);beginRound(state)}
 else if(action==="answer"){if(state.status!=="playing"||state.responderId!==id||state.pending)throw new Error("It is not your answer right now.");const answer=cleanAnswer(payload.answer);state.answersThisRound+=1;state.pending={playerId:id,answer};if(norm(answer)===norm(state.destination)){const nav=state.players.find(p=>p.id===state.navigatorId)!;state.path.push(answer);nav.destinations+=1;nav.successfulSteps+=state.path.length-1;state.success=true;state.status="round_result";state.pending=null;state.message=`YOU GOT THERE in ${state.path.length-1} steps!`}else if(state.answersThisRound>=state.maxAnswersThisRound){state.success=false;state.status="round_result";state.pending=null;state.message="Road closed. The destination stayed hidden."}else state.message="Navigator: USE this answer or PASS it for the next answer."}
 else if(action==="use"){if(state.status!=="playing"||state.navigatorId!==id||!state.pending)throw new Error("There is no answer to use.");const used=state.pending;state.path.push(used.answer);const speaker=state.players.find(p=>p.id===used.playerId)!;state.pending=null;state.responderId=nextNonNavigator(state,speaker.seat).id;state.message=`Build your next question from “${used.answer}.”`}
 else if(action==="pass"){if(state.status!=="playing"||state.navigatorId!==id||!state.pending)throw new Error("There is no answer to pass.");const passed=state.pending;const speaker=state.players.find(p=>p.id===passed.playerId)!;state.pending=null;state.responderId=nextNonNavigator(state,speaker.seat).id;state.message="That answer is gone. Let the next player answer the same question."}
 else if(action==="next"){if(state.status!=="round_result")throw new Error("Finish this route first.");if(state.hostPlayerId!==id&&state.navigatorId!==id)throw new Error("The Navigator or host can continue.");state.round+=1;beginRound(state)}
 else if(action==="restart"){if(state.hostPlayerId!==id)throw new Error("Only the host can restart.");state.status="lobby";state.round=0;state.navigatorId=null;state.responderId=null;state.start="";state.destination="";state.path=[];state.pending=null;state.success=null;state.players.forEach(p=>{p.destinations=0;p.successfulSteps=0;p.attempts=0});state.message="Ready to GET THERE again."}
 else throw new Error("Unknown action.");const saved=await save(row,state);return{state:project(saved.state,id)}}
