import type { ExtraHowCloseQuestion } from "@/lib/play-point-core/how-close-questions-extra";
export const HOW_CLOSE_EXTRA_QUESTIONS_2:ExtraHowCloseQuestion[]=[
{id:"adventure-101",category:"adventure",prompt:"How willing is {name} to take a trip where the destination is revealed only at the airport?",low:"Needs to know",high:"Surprise me"},
{id:"adventure-102",category:"adventure",prompt:"How likely is {name} to hike to a viewpoint even if the trail is steep?",low:"Stay near the car",high:"Worth the climb"},
{id:"adventure-103",category:"adventure",prompt:"How much would {name} enjoy sleeping under the stars with no tent?",low:"Absolutely not",high:"Would love it"},
{id:"adventure-104",category:"adventure",prompt:"How likely is {name} to rent a bike or scooter to explore a new city?",low:"Walk or drive",high:"Absolutely"},
{id:"adventure-105",category:"adventure",prompt:"How willing is {name} to try scuba diving with an instructor?",low:"No chance",high:"Sign me up"},
{id:"adventure-106",category:"adventure",prompt:"How much would {name} enjoy a vacation built around outdoor activities?",low:"Relax indoors",high:"Outside all day"},
{id:"adventure-107",category:"adventure",prompt:"How likely is {name} to take a dirt road just to see where it goes?",low:"Stay on route",high:"Let's find out"},
{id:"adventure-108",category:"adventure",prompt:"How willing is {name} to try an unfamiliar food while traveling?",low:"Sticks to familiar",high:"Absolutely tries it"},
{id:"adventure-109",category:"adventure",prompt:"How likely is {name} to wake up before sunrise to see something special while traveling?",low:"Needs sleep",high:"Worth it"},
{id:"adventure-110",category:"adventure",prompt:"How much would {name} enjoy a weekend in a cabin with no cell service?",low:"Would hate it",high:"Perfect getaway"},
{id:"adventure-111",category:"adventure",prompt:"How likely is {name} to ride in a hot-air balloon?",low:"No chance",high:"Absolutely"},
{id:"adventure-112",category:"adventure",prompt:"How willing is {name} to explore a cave with a guide?",low:"Stay above ground",high:"Lead the way"},
{id:"adventure-113",category:"adventure",prompt:"How likely is {name} to choose a window seat mainly for the view?",low:"Seat does not matter",high:"Window every time"},
{id:"adventure-114",category:"adventure",prompt:"How much would {name} enjoy traveling alone for a weekend?",low:"Would hate it",high:"Would love it"},
{id:"adventure-115",category:"adventure",prompt:"How likely is {name} to swim in the ocean where they cannot touch the bottom?",low:"Stays shallow",high:"No problem"},
{id:"adventure-116",category:"adventure",prompt:"How willing is {name} to sleep in an airport overnight to save a trip?",low:"Find a hotel",high:"Make it work"},
{id:"adventure-117",category:"adventure",prompt:"How likely is {name} to take the longer route if it passes through a national park?",low:"Fastest route",high:"Take the scenic way"},
{id:"adventure-118",category:"adventure",prompt:"How much would {name} enjoy a surprise weekend planned entirely by someone else?",low:"Needs control",high:"Would love it"},
{id:"adventure-119",category:"adventure",prompt:"How willing is {name} to ride a horse on a mountain trail?",low:"No thanks",high:"Absolutely"},
{id:"adventure-120",category:"adventure",prompt:"How likely is {name} to stop at an unplanned roadside attraction during a trip?",low:"Stay on schedule",high:"Always stop"},
{id:"adventure-121",category:"adventure",prompt:"How much would {name} enjoy spending a whole day on a boat?",low:"Not for me",high:"Love it"},
{id:"adventure-122",category:"adventure",prompt:"How willing is {name} to try whitewater rafting with a guide?",low:"Absolutely not",high:"Let's go"},
{id:"adventure-123",category:"adventure",prompt:"How likely is {name} to visit somewhere mainly because they saw an amazing photo of it?",low:"Photos do not sway me",high:"Book it"},
{id:"adventure-124",category:"adventure",prompt:"How much would {name} enjoy a long train trip through beautiful scenery?",low:"Too slow",high:"Would love it"},
{id:"adventure-125",category:"adventure",prompt:"How likely is {name} to wander away from the tourist area to explore local neighborhoods?",low:"Stays on the main path",high:"Likes to explore"},
{id:"adventure-126",category:"adventure",prompt:"How willing is {name} to travel with only a carry-on bag for a full week?",low:"Needs more luggage",high:"Easy"},
{id:"adventure-127",category:"adventure",prompt:"How likely is {name} to take a spontaneous detour because someone says there is something cool nearby?",low:"Stick to plan",high:"Turn the car"},
{id:"adventure-128",category:"adventure",prompt:"How much would {name} enjoy spending a night in a treehouse, yurt, or unusual rental?",low:"Give me a normal room",high:"That sounds awesome"},
{id:"adventure-129",category:"adventure",prompt:"How willing is {name} to try skiing or snowboarding if they had never done it before?",low:"No thanks",high:"Absolutely"},
{id:"adventure-130",category:"adventure",prompt:"How likely is {name} to explore a city during a long layover instead of staying at the airport?",low:"Stay put",high:"Go explore"},
{id:"adventure-131",category:"adventure",prompt:"How much would {name} enjoy a vacation where plans change every day?",low:"Needs a schedule",high:"Loves flexibility"},
{id:"adventure-132",category:"adventure",prompt:"How willing is {name} to visit a place specifically because it is rumored to be haunted?",low:"Avoid it",high:"That makes it better"},
{id:"competition-101",category:"competition",prompt:"How likely is {name} to practice privately before a friendly competition?",low:"Just shows up",high:"Definitely practices"},
{id:"competition-102",category:"competition",prompt:"How much would {name} care about winning a game with absolutely no prize?",low:"Not at all",high:"Winning still matters"},
{id:"competition-103",category:"competition",prompt:"How likely is {name} to remember a close loss weeks later?",low:"Forgets immediately",high:"Still thinking about it"},
{id:"competition-104",category:"competition",prompt:"How willing is {name} to compete in something they know they are bad at?",low:"Avoids it",high:"Why not"},
{id:"competition-105",category:"competition",prompt:"How likely is {name} to study an opponent's strategy before a rematch?",low:"Just play",high:"Comes prepared"},
{id:"competition-106",category:"competition",prompt:"How much would {name} enjoy a trivia night where the winning team gets only bragging rights?",low:"Not interested",high:"Very into it"},
{id:"competition-107",category:"competition",prompt:"How likely is {name} to take a friendly bet seriously?",low:"Purely for fun",high:"Now it matters"},
{id:"competition-108",category:"competition",prompt:"How likely is {name} to challenge a questionable call during a game?",low:"Lets it go",high:"Definitely challenges"},
{id:"competition-109",category:"competition",prompt:"How much would {name} enjoy coaching a team from the sidelines?",low:"No thanks",high:"Would love it"},
{id:"competition-110",category:"competition",prompt:"How likely is {name} to pick the harder difficulty level in a game?",low:"Keep it easy",high:"Bring the challenge"},
{id:"competition-111",category:"competition",prompt:"How bothered would {name} be if someone celebrated too much after beating them?",low:"Would laugh",high:"Very bothered"},
{id:"competition-112",category:"competition",prompt:"How likely is {name} to turn a casual activity into a competition?",low:"Keeps it casual",high:"Everything can be scored"},
{id:"competition-113",category:"competition",prompt:"How willing is {name} to enter a tournament just to see how they stack up?",low:"No interest",high:"Sign me up"},
{id:"competition-114",category:"competition",prompt:"How much would {name} enjoy being the underdog in a competition?",low:"Prefers being favored",high:"Loves the challenge"},
{id:"competition-115",category:"competition",prompt:"How likely is {name} to replay a game immediately after losing badly?",low:"Needs a break",high:"Run it back now"},
{id:"competition-116",category:"competition",prompt:"How likely is {name} to keep their strategy secret before a game?",low:"Tells everyone",high:"Says nothing"},
{id:"competition-117",category:"competition",prompt:"How much would {name} enjoy competing against someone clearly better than them?",low:"Not fun",high:"Best way to improve"},
{id:"competition-118",category:"competition",prompt:"How likely is {name} to celebrate a teammate's win as loudly as their own?",low:"Keeps it quiet",high:"Huge celebration"},
{id:"competition-119",category:"competition",prompt:"How bothered would {name} be by losing because of bad luck instead of bad play?",low:"That's the game",high:"Drives me crazy"},
{id:"competition-120",category:"competition",prompt:"How likely is {name} to learn the rules thoroughly before a new game starts?",low:"Learns while playing",high:"Reads everything"},
{id:"competition-121",category:"competition",prompt:"How likely is {name} to keep a personal best score and try to beat it?",low:"Does not track it",high:"Always chasing a best"},
{id:"competition-122",category:"competition",prompt:"How much would {name} enjoy a competition decided entirely by luck?",low:"Hates pure luck",high:"Sounds fun"},
{id:"competition-123",category:"competition",prompt:"How likely is {name} to volunteer for the pressure moment if their team needs someone?",low:"Let someone else do it",high:"Give me the chance"},
{id:"competition-124",category:"competition",prompt:"How much does {name} enjoy playful trash talk before a competition starts?",low:"Not at all",high:"Part of the fun"},
{id:"competition-125",category:"competition",prompt:"How likely is {name} to keep competing even when there is almost no chance of winning?",low:"Calls it",high:"Never quits"},
{id:"competition-126",category:"competition",prompt:"How likely is {name} to choose a teammate based on chemistry instead of pure skill?",low:"Best player available",high:"Chemistry matters most"},
{id:"competition-127",category:"competition",prompt:"How much would {name} enjoy being judged by a panel instead of a scoreboard?",low:"Hates subjective judging",high:"Totally fine"},
{id:"competition-128",category:"competition",prompt:"How likely is {name} to practice one skill repeatedly until they finally get it right?",low:"Moves on",high:"Keeps at it"},
{id:"competition-129",category:"competition",prompt:"How much would {name} enjoy captaining a team made up of complete beginners?",low:"No thanks",high:"Would love the challenge"},
{id:"competition-130",category:"competition",prompt:"How likely is {name} to choose a risky play if it is the only way to win?",low:"Play it safe",high:"Go for the win"},
{id:"competition-131",category:"competition",prompt:"How likely is {name} to congratulate someone immediately after a frustrating loss?",low:"Needs a minute",high:"Always does"},
{id:"competition-132",category:"competition",prompt:"How much would {name} enjoy a full day of friendly contests with family or friends?",low:"Too much competition",high:"Perfect day"},
{id:"habits-101",category:"habits",prompt:"How likely is {name} to check their phone within five minutes of waking up?",low:"Rarely",high:"Almost immediately"},
{id:"habits-102",category:"habits",prompt:"How likely is {name} to set multiple alarms for the same morning?",low:"One alarm",high:"A whole lineup"},
{id:"habits-103",category:"habits",prompt:"How likely is {name} to keep dozens of browser tabs open at once?",low:"Closes everything",high:"Tabs everywhere"},
{id:"habits-104",category:"habits",prompt:"How likely is {name} to put something in a safe place and then forget where that safe place was?",low:"Almost never",high:"Very likely"},
{id:"habits-105",category:"habits",prompt:"How likely is {name} to reread a message before sending it?",low:"Sends immediately",high:"Checks it carefully"},
{id:"habits-106",category:"habits",prompt:"How likely is {name} to keep the same phone wallpaper for years?",low:"Changes it often",high:"Never changes it"},
{id:"habits-107",category:"habits",prompt:"How likely is {name} to scroll or watch videos longer than they intended?",low:"Stops on time",high:"Loses track completely"},
{id:"habits-108",category:"habits",prompt:"How likely is {name} to leave a little bit of a drink unfinished?",low:"Finishes it",high:"Always leaves some"},
{id:"habits-109",category:"habits",prompt:"How likely is {name} to organize things by a system that makes sense mainly to them?",low:"No system",high:"Very specific system"},
{id:"habits-110",category:"habits",prompt:"How likely is {name} to talk to themselves while working through a problem?",low:"Never",high:"All the time"},
{id:"habits-111",category:"habits",prompt:"How likely is {name} to rewatch a favorite movie or show instead of starting something new?",low:"Always wants new",high:"Loves familiar favorites"},
{id:"habits-112",category:"habits",prompt:"How likely is {name} to keep old messages or photos because they might want them later?",low:"Deletes freely",high:"Keeps everything"},
{id:"habits-113",category:"habits",prompt:"How likely is {name} to start packing for a trip several days early?",low:"Last minute",high:"Way ahead"},
{id:"habits-114",category:"habits",prompt:"How likely is {name} to check a locked door more than once?",low:"Once is enough",high:"Checks again"},
{id:"habits-115",category:"habits",prompt:"How likely is {name} to have a favorite cup, chair, or spot they use whenever possible?",low:"No preference",high:"Definitely has a spot"},
{id:"habits-116",category:"habits",prompt:"How likely is {name} to save screenshots they never look at again?",low:"Rarely screenshots",high:"Camera roll full of them"},
{id:"habits-117",category:"habits",prompt:"How likely is {name} to put off making a phone call they do not want to make?",low:"Gets it over with",high:"Delays it"},
{id:"habits-118",category:"habits",prompt:"How likely is {name} to check a menu online before going to a restaurant?",low:"Never",high:"Almost always"},
{id:"habits-119",category:"habits",prompt:"How likely is {name} to keep a running mental list instead of writing things down?",low:"Writes everything",high:"Keeps it in their head"},
{id:"habits-120",category:"habits",prompt:"How likely is {name} to wear the same favorite shoes whenever they can?",low:"Rotates everything",high:"Same pair constantly"},
{id:"habits-121",category:"habits",prompt:"How likely is {name} to keep a charger in more than one place just in case?",low:"One charger",high:"Chargers everywhere"},
{id:"habits-122",category:"habits",prompt:"How likely is {name} to check reviews before watching a movie?",low:"Goes in blind",high:"Checks first"},
{id:"habits-123",category:"habits",prompt:"How likely is {name} to keep packaging from an expensive purchase for a long time?",low:"Throws it away",high:"Keeps the box"},
{id:"habits-124",category:"habits",prompt:"How likely is {name} to snack while standing in the kitchen instead of sitting down?",low:"Always sits",high:"Very likely"},
{id:"habits-125",category:"habits",prompt:"How likely is {name} to fall asleep with the TV or music still on?",low:"Needs quiet",high:"Happens often"},
{id:"habits-126",category:"habits",prompt:"How likely is {name} to keep a favorite pen and notice if someone takes it?",low:"Any pen works",high:"Definitely has one"},
{id:"habits-127",category:"habits",prompt:"How likely is {name} to look up a random question immediately instead of wondering about it?",low:"Lets it go",high:"Looks it up now"},
{id:"habits-128",category:"habits",prompt:"How likely is {name} to replay a conversation in their head afterward?",low:"Moves on",high:"Replays it a lot"},
{id:"habits-129",category:"habits",prompt:"How likely is {name} to put a completed task on a list just so they can cross it off?",low:"Never",high:"Absolutely"},
{id:"habits-130",category:"habits",prompt:"How likely is {name} to check the time repeatedly when waiting for something important?",low:"Rarely",high:"Constantly"},
{id:"habits-131",category:"habits",prompt:"How likely is {name} to keep an item they never use because they might need it someday?",low:"Gets rid of it",high:"Keeps it just in case"},
{id:"habits-132",category:"habits",prompt:"How likely is {name} to listen to the same favorite song several times in one day?",low:"Needs variety",high:"Plays it again"},
{id:"hypothetical-101",category:"hypothetical",prompt:"If {name} could instantly master one musical instrument, how likely are they to take the deal?",low:"Not interested",high:"Absolutely"},
{id:"hypothetical-102",category:"hypothetical",prompt:"If {name} could know exactly what people first think of them, how much would they want to know?",low:"Do not tell me",high:"I want to know everything"},
{id:"hypothetical-103",category:"hypothetical",prompt:"If {name} could relive one favorite day exactly as it happened, how likely are they to do it?",low:"Keep moving forward",high:"Absolutely relive it"},
{id:"hypothetical-104",category:"hypothetical",prompt:"If {name} could have free restaurant meals for life but never cook again, how appealing would that be?",low:"No deal",high:"Perfect deal"},
{id:"hypothetical-105",category:"hypothetical",prompt:"If {name} had to give up either TV or social media for a year, how easy would it be for them to choose one?",low:"Very difficult",high:"Easy choice"},
{id:"hypothetical-106",category:"hypothetical",prompt:"If {name} could teleport anywhere once today, how likely are they to use it immediately?",low:"Save it",high:"Use it now"},
{id:"hypothetical-107",category:"hypothetical",prompt:"If {name} were offered a year off work with half their normal income, how likely are they to take it?",low:"No chance",high:"Absolutely"},
{id:"hypothetical-108",category:"hypothetical",prompt:"If {name} could be famous for one talent, how much would they actually want the fame?",low:"Keep me anonymous",high:"Would love it"},
{id:"hypothetical-109",category:"hypothetical",prompt:"If {name} could erase one embarrassing memory from everyone else's minds, how likely are they to use that power?",low:"Leave it alone",high:"Erase it now"},
{id:"hypothetical-110",category:"hypothetical",prompt:"If {name} found a hidden room in their house, how likely are they to go in alone immediately?",low:"Get someone first",high:"Going in now"},
{id:"hypothetical-111",category:"hypothetical",prompt:"If {name} could ask their future self one question, how badly would they want the answer?",low:"Rather not know",high:"Need the answer"},
{id:"hypothetical-112",category:"hypothetical",prompt:"If {name} could permanently eliminate one household chore, how excited would they be to choose one?",low:"Chores do not bother me",high:"Best gift ever"},
{id:"hypothetical-113",category:"hypothetical",prompt:"If {name} could switch lives with a celebrity for one week, how likely are they to do it?",low:"No thanks",high:"Absolutely"},
{id:"hypothetical-114",category:"hypothetical",prompt:"If {name} could know the exact date of every future vacation they will take, how much would they want to know?",low:"Keep it a surprise",high:"Tell me all of them"},
{id:"hypothetical-115",category:"hypothetical",prompt:"If {name} could instantly become fluent in every language, how valuable would that be to them?",low:"Nice but unnecessary",high:"Life-changing"},
{id:"hypothetical-116",category:"hypothetical",prompt:"If {name} could live anywhere in the world for one year with expenses paid, how likely are they to leave home and do it?",low:"Would stay home",high:"Packing now"},
{id:"hypothetical-117",category:"hypothetical",prompt:"If {name} could never get stuck in traffic again but had to leave 20 minutes earlier everywhere, how likely are they to take that deal?",low:"No deal",high:"Absolutely"},
{id:"hypothetical-118",category:"hypothetical",prompt:"If {name} could pause time for one hour with no consequences, how eager would they be to try it?",low:"Not interested",high:"Immediately"},
{id:"hypothetical-119",category:"hypothetical",prompt:"If {name} were handed tickets tonight to an event they know nothing about, how likely are they to go?",low:"Needs details",high:"Let's go"},
{id:"hypothetical-120",category:"hypothetical",prompt:"If {name} could choose between a guaranteed comfortable life and a risky chance at an extraordinary one, how likely are they to choose the risk?",low:"Choose security",high:"Take the risk"},
{id:"hypothetical-121",category:"hypothetical",prompt:"If {name} could have a personal chef or a personal housekeeper for free, how strongly would they prefer the housekeeper?",low:"Chef please",high:"Housekeeper please"},
{id:"hypothetical-122",category:"hypothetical",prompt:"If {name} could instantly see every place they have ever visited on a giant map, how interested would they be?",low:"Not very",high:"Would love that"},
{id:"hypothetical-123",category:"hypothetical",prompt:"If {name} could spend one day in any historical era and safely return, how likely are they to go?",low:"Stay here",high:"Absolutely go"},
{id:"hypothetical-124",category:"hypothetical",prompt:"If {name} could have perfect weather every weekend but random weather all week, how appealing is that deal?",low:"No deal",high:"Perfect deal"},
{id:"hypothetical-125",category:"hypothetical",prompt:"If {name} could instantly know whether someone was lying, how much would they want that ability?",low:"Rather not know",high:"Absolutely want it"},
{id:"hypothetical-126",category:"hypothetical",prompt:"If {name} could get $1,000 today or a 50% chance at $5,000 tomorrow, how likely are they to gamble on tomorrow?",low:"Take the $1,000",high:"Take the chance"},
{id:"hypothetical-127",category:"hypothetical",prompt:"If {name} could instantly become excellent at one sport, how much would that appeal to them?",low:"Not much",high:"A lot"},
{id:"hypothetical-128",category:"hypothetical",prompt:"If {name} could watch one unreleased movie from five years in the future, how likely are they to do it?",low:"Wait for it",high:"Show me now"},
{id:"hypothetical-129",category:"hypothetical",prompt:"If {name} could have their dream home but it had to be 500 miles from everyone they know, how likely are they to take it?",low:"Stay near people",high:"Take the dream home"},
{id:"hypothetical-130",category:"hypothetical",prompt:"If {name} could permanently remove one minor annoyance from daily life, how excited would they be by that power?",low:"Not a big deal",high:"Would love it"},
{id:"hypothetical-131",category:"hypothetical",prompt:"If {name} could trade one year of ordinary weekends for one three-month adventure, how likely are they to make the trade?",low:"Keep the weekends",high:"Take the adventure"},
{id:"hypothetical-132",category:"hypothetical",prompt:"If {name} received a key that opens one mysterious door somewhere in the world, how determined would they be to find the door?",low:"Probably forget about it",high:"Must find it"}
];