import "server-only";

import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { getSupabaseServerClient } from "@/lib/play-point-core/quick-score-supabase";

const ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const PROMPTS=["How embarrassing is it when restaurant staff sing Happy Birthday to you?","How much fun is a surprise road trip?","How annoying is it when someone chews loudly?","How likely are you to try a food you have never heard of?","How much better is a weekend with no plans?","How scary is a roller coaster with a huge first drop?","How important is dessert after a good meal?","How funny is Dad telling the same story again?","How much would you enjoy camping for a week?","How exciting is opening a mystery package?","How bad is being 15 minutes late?","How much fun is singing in the car together?","How likely are you to talk to a stranger in line?","How much does weather affect your mood?","How good is breakfast for dinner?","How much fun would a family game night be tonight?","How likely are you to order the same thing every time at a favorite restaurant?","How stressful is losing your phone for an hour?","How much do you enjoy being surprised?","How likely are you to laugh during a serious moment?"];
type Player={id:string;name:string;tokenHash:string;score:number;seat:number};
type State={code:string;status:"lobby"|"playing"|"finished";hostPlayerId:string;players:Player[];round:number;maxRounds:number;promptOrder:string[];answers:Record<string,number>;revealed:boolean;average:number|null;sameBrain:boolean;message:string};
type Row={code:string;state:State;version:number};
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function tokenMatches(expected:string,token:string){const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
function cleanName(v:unknown){const n=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!n||n.length>24)throw new Error("Enter a name up to 24 characters.");return n}
function cleanCode(v:unknown){const c=typeof v==="string"?v.trim().toUpperCase():"";if(!/^[A-Z2-9]{6}$/.test(c))throw new Error("Enter a valid 6-character room code.");return c}
function roomCode(){const b=randomBytes(6);return Array.from(b,x=>ALPHABET[x%ALPHABET.length]).join("")}
function playerToken(){return randomBytes(32).toString("base64url")}
function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function read(code:string):Promise<Row|null>{const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_how_close_rooms").select("code,state,version").eq("code",code).maybeSingle();if(error)throw new Error(error.message);return data as Row|null}
async function save(row:Row,state:State){const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_how_close_rooms").update({state,version:row.version+1,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}).eq("code",row.code).eq("version",row.version).select("code,state,version").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("The table changed. Try again.");return data as Row}
function auth(state:State,id:string,token:string){const p=state.players.find(x=>x.id===id);if(!p||!tokenMatches(p.tokenHash,token))throw new Error("Invalid player session.");return p}
function project(state:State,viewer:string){const reveal=state.revealed||state.status==="finished";return{...state,players:state.players.map(({tokenHash:_,...p})=>p),answers:reveal?state.answers:(state.answers[viewer]!==undefined?{[viewer]:state.answers[viewer]}:{}),me:state.players.find(p=>p.id===viewer)?{id:viewer,isHost:state.hostPlayerId===viewer}:null,currentPrompt:state.promptOrder[state.round]??null,answeredCount:Object.keys(state.answers).length}}
function points(distance:number){if(distance===0)return 5;if(distance<=5)return 4;if(distance<=10)return 3;if(distance<=20)return 2;return 1}
export async function createHowCloseRoom(nameValue:unknown){const name=cleanName(nameValue);for(let i=0;i<8;i++){const code=roomCode(),token=playerToken(),id=randomUUID();const state:State={code,status:"lobby",hostPlayerId:id,players:[{id,name,tokenHash:hash(token),score:0,seat:0}],round:0,maxRounds:7,promptOrder:shuffle(PROMPTS).slice(0,7),answers:{},revealed:false,average:null,sameBrain:false,message:"Invite everyone, then see how close you really are."};const s=getSupabaseServerClient();const{error}=await s.from("ppl_how_close_rooms").insert({code,state,version:1});if(!error)return{code,playerId:id,token,state:project(state,id)}}throw new Error("Unable to create a room.")}
export async function joinHowCloseRoom(codeValue:unknown,nameValue:unknown){const code=cleanCode(codeValue),name=cleanName(nameValue),row=await read(code);if(!row)throw new Error("Room not found.");if(row.state.status!=="lobby")throw new Error("That game has already started.");if(row.state.players.length>=8)throw new Error("That room is full.");const token=playerToken(),id=randomUUID();row.state.players.push({id,name,tokenHash:hash(token),score:0,seat:row.state.players.length});const saved=await save(row,row.state);return{code,playerId:id,token,state:project(saved.state,id)}}
export async function getHowCloseRoom(codeValue:unknown,id:string,token:string){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");auth(row.state,id,token);return{state:project(row.state,id)}}
export async function actHowCloseRoom(codeValue:unknown,id:string,token:string,action:string,payload:Record<string,unknown>={}){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");const state=row.state;auth(state,id,token);
 if(action==="start"){if(state.hostPlayerId!==id)throw new Error("Only the host can start.");if(state.players.length<2)throw new Error("Invite at least one more player.");state.status="playing";state.round=0;state.answers={};state.revealed=false;state.average=null;state.sameBrain=false;state.message="Pick a number from 1 to 100. No peeking."}
 else if(action==="answer"){if(state.status!=="playing"||state.revealed)throw new Error("This round is not accepting answers.");if(state.answers[id]!==undefined)throw new Error("Your answer is already locked.");const value=Number(payload.value);if(!Number.isInteger(value)||value<1||value>100)throw new Error("Choose a whole number from 1 to 100.");state.answers[id]=value;state.message=`${Object.keys(state.answers).length}/${state.players.length} answers locked.`;if(Object.keys(state.answers).length===state.players.length){const values=Object.values(state.answers);state.average=Math.round(values.reduce((a,b)=>a+b,0)/values.length);state.sameBrain=values.every(v=>v===values[0]);for(const p of state.players){p.score+=points(Math.abs(state.answers[p.id]-state.average))+(state.sameBrain?2:0)}state.revealed=true;state.message=state.sameBrain?"SAME BRAIN! Everybody matched exactly.":`Table average: ${state.average}.`}}
 else if(action==="next"){if(state.hostPlayerId!==id)throw new Error("Only the host can continue.");if(!state.revealed)throw new Error("Wait for the reveal.");if(state.round+1>=state.maxRounds){state.status="finished";state.message="That is the table!"}else{state.round+=1;state.answers={};state.revealed=false;state.average=null;state.sameBrain=false;state.message="New question. Lock in your number."}}
 else if(action==="restart"){if(state.hostPlayerId!==id)throw new Error("Only the host can restart.");state.status="lobby";state.round=0;state.answers={};state.revealed=false;state.average=null;state.sameBrain=false;state.promptOrder=shuffle(PROMPTS).slice(0,7);state.players.forEach(p=>p.score=0);state.message="Ready for another round of How Close Are We?"}
 else throw new Error("Unknown action.");const saved=await save(row,state);return{state:project(saved.state,id)}}
