export type HowCloseQuestion = {
  id: string;
  category: "everyday" | "food" | "social" | "money" | "adventure" | "competition" | "habits" | "hypothetical";
  prompt: string;
  low: string;
  high: string;
};

export const HOW_CLOSE_QUESTIONS: HowCloseQuestion[] = [
  { id: "everyday-01", category: "everyday", prompt: "How likely is {name} to hit snooze more than once?", low: "Never", high: "Every chance" },
  { id: "everyday-02", category: "everyday", prompt: "How annoyed would {name} be if someone changed the thermostat without asking?", low: "Would not care", high: "Very annoyed" },
  { id: "everyday-03", category: "everyday", prompt: "How likely is {name} to leave the house and come back because they forgot something?", low: "Almost never", high: "Constantly" },
  { id: "everyday-04", category: "everyday", prompt: "How much would {name} enjoy an entire Saturday with absolutely no plans?", low: "Hate it", high: "Perfect day" },
  { id: "everyday-05", category: "everyday", prompt: "How likely is {name} to start cleaning right before company arrives?", low: "Never", high: "Guaranteed" },
  { id: "everyday-06", category: "everyday", prompt: "How bothered would {name} be by being 15 minutes late?", low: "Not bothered", high: "Extremely bothered" },
  { id: "everyday-07", category: "everyday", prompt: "How likely is {name} to watch one more episode even when they should go to bed?", low: "No chance", high: "Absolutely" },
  { id: "everyday-08", category: "everyday", prompt: "How much does bad weather change {name}'s mood?", low: "Not at all", high: "Completely" },
  { id: "everyday-09", category: "everyday", prompt: "How likely is {name} to check the weather before deciding what to do?", low: "Never", high: "Always" },
  { id: "everyday-10", category: "everyday", prompt: "How much would {name} enjoy a long drive with no real destination?", low: "Not at all", high: "Love it" },
  { id: "everyday-11", category: "everyday", prompt: "How likely is {name} to answer a phone call instead of letting it go to voicemail?", low: "Never answers", high: "Always answers" },
  { id: "everyday-12", category: "everyday", prompt: "How much would {name} care if the house was messy for one full day?", low: "Would not care", high: "Could not stand it" },
  { id: "everyday-13", category: "everyday", prompt: "How likely is {name} to read the instructions before trying to put something together?", low: "Never", high: "Every time" },
  { id: "everyday-14", category: "everyday", prompt: "How much would {name} enjoy getting up before sunrise for something fun?", low: "No thanks", high: "Absolutely" },

  { id: "food-01", category: "food", prompt: "How likely is {name} to order the same meal at a favorite restaurant?", low: "Always tries new things", high: "Same order every time" },
  { id: "food-02", category: "food", prompt: "How likely is {name} to send food back if the order is wrong?", low: "Would never", high: "Without hesitation" },
  { id: "food-03", category: "food", prompt: "How important is dessert to {name} after a really good meal?", low: "Skip it", high: "Essential" },
  { id: "food-04", category: "food", prompt: "How likely is {name} to try the strangest thing on the menu?", low: "No chance", high: "First choice" },
  { id: "food-05", category: "food", prompt: "How much would {name} enjoy breakfast for dinner?", low: "Not at all", high: "Love it" },
  { id: "food-06", category: "food", prompt: "How likely is {name} to eat leftovers straight from the refrigerator?", low: "Never", high: "Absolutely" },
  { id: "food-07", category: "food", prompt: "How upset would {name} be if someone ate the leftovers they were saving?", low: "Would not care", high: "Major offense" },
  { id: "food-08", category: "food", prompt: "How likely is {name} to choose a restaurant mostly because it has a great dessert?", low: "Never", high: "Definitely" },
  { id: "food-09", category: "food", prompt: "How adventurous is {name} with food they have never tried before?", low: "Very cautious", high: "Try anything" },
  { id: "food-10", category: "food", prompt: "How likely is {name} to steal a fry off someone else's plate?", low: "Never", high: "Already reaching" },
  { id: "food-11", category: "food", prompt: "How much would {name} enjoy cooking a complicated meal from scratch?", low: "Hate it", high: "Love it" },
  { id: "food-12", category: "food", prompt: "How likely is {name} to choose the spicy option?", low: "Never spicy", high: "Bring the heat" },

  { id: "social-01", category: "social", prompt: "How likely is {name} to start a conversation with a stranger in line?", low: "Never", high: "Absolutely" },
  { id: "social-02", category: "social", prompt: "How embarrassed would {name} be if restaurant staff sang Happy Birthday to them?", low: "Love the attention", high: "Please make it stop" },
  { id: "social-03", category: "social", prompt: "How likely is {name} to be the first person on the dance floor?", low: "No chance", high: "Already dancing" },
  { id: "social-04", category: "social", prompt: "How much would {name} enjoy being the center of attention for an evening?", low: "Hate it", high: "Love it" },
  { id: "social-05", category: "social", prompt: "How likely is {name} to tell a joke to break an awkward silence?", low: "Never", high: "Definitely" },
  { id: "social-06", category: "social", prompt: "How likely is {name} to remember someone's name after meeting them once?", low: "No chance", high: "Always remembers" },
  { id: "social-07", category: "social", prompt: "How much would {name} enjoy hosting a house full of people?", low: "Not at all", high: "Love it" },
  { id: "social-08", category: "social", prompt: "How likely is {name} to speak up when everyone else disagrees with them?", low: "Keep quiet", high: "Say it anyway" },
  { id: "social-09", category: "social", prompt: "How likely is {name} to laugh at the worst possible moment?", low: "Never", high: "Very likely" },
  { id: "social-10", category: "social", prompt: "How much would {name} enjoy going to a party where they know almost nobody?", low: "Hate it", high: "Love it" },
  { id: "social-11", category: "social", prompt: "How likely is {name} to compliment a complete stranger?", low: "Rarely", high: "All the time" },
  { id: "social-12", category: "social", prompt: "How likely is {name} to keep a surprise party secret?", low: "Would give it away", high: "Vault-level secret" },
  { id: "social-13", category: "social", prompt: "How likely is {name} to volunteer to give a speech with no preparation?", low: "Absolutely not", high: "Hand me the microphone" },
  { id: "social-14", category: "social", prompt: "How much does {name} care about making a good first impression?", low: "Hardly at all", high: "A great deal" },

  { id: "money-01", category: "money", prompt: "How likely is {name} to buy something just because it is on sale?", low: "Never", high: "Very likely" },
  { id: "money-02", category: "money", prompt: "How hard would it be for {name} to spend $500 on something purely for fun?", low: "Easy", high: "Painful" },
  { id: "money-03", category: "money", prompt: "How likely is {name} to compare prices at three places before buying something expensive?", low: "Buy it now", high: "Research everything" },
  { id: "money-04", category: "money", prompt: "How likely is {name} to pick up a lucky penny from the ground?", low: "Walk past it", high: "Every time" },
  { id: "money-05", category: "money", prompt: "If {name} unexpectedly got $1,000, how likely are they to save most of it?", low: "Spend it", high: "Save it" },
  { id: "money-06", category: "money", prompt: "How likely is {name} to pay extra for convenience?", low: "Never", high: "Worth every dollar" },
  { id: "money-07", category: "money", prompt: "How likely is {name} to negotiate the price of a used car?", low: "Take the listed price", high: "Negotiate hard" },
  { id: "money-08", category: "money", prompt: "How much would {name} enjoy receiving cash instead of a wrapped birthday gift?", low: "Not at all", high: "Perfect gift" },
  { id: "money-09", category: "money", prompt: "How likely is {name} to keep using something old because it still works?", low: "Replace it", high: "Use it forever" },
  { id: "money-10", category: "money", prompt: "How likely is {name} to buy an expensive item without sleeping on the decision first?", low: "Never", high: "Absolutely" },

  { id: "adventure-01", category: "adventure", prompt: "How likely is {name} to ride the biggest roller coaster in the park?", low: "No chance", high: "Front row" },
  { id: "adventure-02", category: "adventure", prompt: "How much would {name} enjoy camping for a full week?", low: "Miserable", high: "Love every minute" },
  { id: "adventure-03", category: "adventure", prompt: "How likely is {name} to take a last-minute road trip with only an hour to pack?", low: "No way", high: "Already packed" },
  { id: "adventure-04", category: "adventure", prompt: "How willing would {name} be to sleep one night in a supposedly haunted house?", low: "Absolutely not", high: "Sounds fun" },
  { id: "adventure-05", category: "adventure", prompt: "How likely is {name} to go zip-lining if everyone else is doing it?", low: "Stay on the ground", high: "First in line" },
  { id: "adventure-06", category: "adventure", prompt: "How much would {name} enjoy a vacation with no itinerary?", low: "Need a plan", high: "Perfect vacation" },
  { id: "adventure-07", category: "adventure", prompt: "How likely is {name} to jump into very cold water on a dare?", low: "Never", high: "Absolutely" },
  { id: "adventure-08", category: "adventure", prompt: "How willing would {name} be to travel somewhere they do not speak the language?", low: "Very hesitant", high: "Book the flight" },
  { id: "adventure-09", category: "adventure", prompt: "How likely is {name} to choose the scenic route even if it takes longer?", low: "Fastest route", high: "Scenic every time" },
  { id: "adventure-10", category: "adventure", prompt: "How much would {name} enjoy spending a day completely off the grid?", low: "Hate it", high: "Love it" },
  { id: "adventure-11", category: "adventure", prompt: "How likely is {name} to try an activity they are terrible at just for the story?", low: "No thanks", high: "Absolutely" },
  { id: "adventure-12", category: "adventure", prompt: "How likely is {name} to explore a weird roadside attraction?", low: "Drive past", high: "Pull over" },

  { id: "competition-01", category: "competition", prompt: "How competitive does {name} get during a friendly game?", low: "Does not care", high: "Must win" },
  { id: "competition-02", category: "competition", prompt: "How likely is {name} to demand a rematch after losing?", low: "Good game", high: "Run it back" },
  { id: "competition-03", category: "competition", prompt: "How much would losing by one point bother {name}?", low: "Not at all", high: "All night" },
  { id: "competition-04", category: "competition", prompt: "How likely is {name} to celebrate a small victory like they won a championship?", low: "Stay calm", high: "Huge celebration" },
  { id: "competition-05", category: "competition", prompt: "How likely is {name} to bend a house rule in their favor during a game?", low: "Never", high: "If they can get away with it" },
  { id: "competition-06", category: "competition", prompt: "How much would {name} enjoy being captain and choosing the teams?", low: "No thanks", high: "Absolutely" },
  { id: "competition-07", category: "competition", prompt: "How likely is {name} to keep score when everyone else says it does not matter?", low: "Forget the score", high: "Score matters" },
  { id: "competition-08", category: "competition", prompt: "How likely is {name} to trash-talk someone they know well during a game?", low: "Never", high: "Nonstop" },
  { id: "competition-09", category: "competition", prompt: "How willing is {name} to try again immediately after failing at something?", low: "Done for now", high: "Again right now" },
  { id: "competition-10", category: "competition", prompt: "How much does {name} enjoy proving someone wrong?", low: "Does not matter", high: "Very satisfying" },

  { id: "habits-01", category: "habits", prompt: "How likely is {name} to have unread notifications piling up on their phone?", low: "Inbox zero", high: "Hundreds" },
  { id: "habits-02", category: "habits", prompt: "How likely is {name} to make a list before going grocery shopping?", low: "Never", high: "Always" },
  { id: "habits-03", category: "habits", prompt: "How likely is {name} to lose track of time while doing something they enjoy?", low: "Never", high: "Very likely" },
  { id: "habits-04", category: "habits", prompt: "How organized is {name}'s car on a normal day?", low: "Total chaos", high: "Spotless" },
  { id: "habits-05", category: "habits", prompt: "How likely is {name} to keep a box because it might be useful someday?", low: "Throw it away", high: "Keep every good box" },
  { id: "habits-06", category: "habits", prompt: "How likely is {name} to start a project before finishing the last one?", low: "One at a time", high: "Several going" },
  { id: "habits-07", category: "habits", prompt: "How likely is {name} to replay a favorite song several times in a row?", low: "Never", high: "On repeat" },
  { id: "habits-08", category: "habits", prompt: "How likely is {name} to keep their phone battery above 50 percent?", low: "Always near dead", high: "Always charged" },
  { id: "habits-09", category: "habits", prompt: "How likely is {name} to arrive early rather than exactly on time?", low: "Cuts it close", high: "Always early" },
  { id: "habits-10", category: "habits", prompt: "How likely is {name} to look up the ending of a movie before finishing it?", low: "Never spoil it", high: "Needs to know" },
  { id: "habits-11", category: "habits", prompt: "How likely is {name} to take a picture of something instead of writing it down?", low: "Write it down", high: "Camera roll notes" },
  { id: "habits-12", category: "habits", prompt: "How likely is {name} to fix something themselves before calling someone?", low: "Call for help", high: "I can fix it" },
  { id: "habits-13", category: "habits", prompt: "How likely is {name} to check a restaurant menu online before going there?", low: "Never", high: "Every time" },
  { id: "habits-14", category: "habits", prompt: "How likely is {name} to fall asleep during a movie they chose?", low: "Never", high: "Very likely" },

  { id: "hypothetical-01", category: "hypothetical", prompt: "If {name} won $1 million tomorrow, how likely are they to keep working at the same job for a while?", low: "Quit immediately", high: "Keep working" },
  { id: "hypothetical-02", category: "hypothetical", prompt: "If {name} could instantly master one new skill, how likely are they to choose something practical over something fun?", low: "Purely fun", high: "Very practical" },
  { id: "hypothetical-03", category: "hypothetical", prompt: "If {name} became famous overnight, how much would they enjoy the attention?", low: "Hate it", high: "Love it" },
  { id: "hypothetical-04", category: "hypothetical", prompt: "If {name} found a wallet full of cash with an ID inside, how quickly would they try to return it?", low: "Eventually", high: "Immediately" },
  { id: "hypothetical-05", category: "hypothetical", prompt: "If {name} could live anywhere for one year, how likely are they to choose somewhere completely unfamiliar?", low: "Stay familiar", high: "Somewhere new" },
  { id: "hypothetical-06", category: "hypothetical", prompt: "If {name} had to give up either TV or social media for a year, how willing would they be to give up social media?", low: "Keep social media", high: "Delete it today" },
  { id: "hypothetical-07", category: "hypothetical", prompt: "If {name} could know exactly what people think of them, how much would they actually want to know?", low: "Do not tell me", high: "Tell me everything" },
  { id: "hypothetical-08", category: "hypothetical", prompt: "If {name} were offered a free trip leaving tomorrow, how likely are they to say yes before asking many questions?", low: "Need every detail", high: "I'm in" },
  { id: "hypothetical-09", category: "hypothetical", prompt: "If {name} had one extra free hour every day, how likely are they to spend it relaxing instead of being productive?", low: "Be productive", high: "Relax" },
  { id: "hypothetical-10", category: "hypothetical", prompt: "If {name} could relive one great day from their past, how likely are they to do it?", low: "Keep moving forward", high: "Absolutely relive it" },
  { id: "hypothetical-11", category: "hypothetical", prompt: "If {name} had to perform on a talent show tomorrow, how confident would they feel?", low: "Terrified", high: "Bring it on" },
  { id: "hypothetical-12", category: "hypothetical", prompt: "If {name} could press a button to skip every line for the rest of their life, how badly would they want it?", low: "Do not care", high: "Press it now" },
  { id: "hypothetical-13", category: "hypothetical", prompt: "If {name} could spend a day with any celebrity, how excited would they be about it?", low: "Not interested", high: "Dream day" },
  { id: "hypothetical-14", category: "hypothetical", prompt: "If {name} woke up with no obligations tomorrow, how likely are they to leave the house before noon?", low: "Stay home", high: "Out the door" },
  { id: "hypothetical-15", category: "hypothetical", prompt: "If {name} could erase one embarrassing memory from everyone else's mind, how badly would they want to use that power?", low: "Leave it alone", high: "Erase it now" },
  { id: "hypothetical-16", category: "hypothetical", prompt: "If {name} had to eat the same dinner every night for a month, how well would they handle it?", low: "Miserable", high: "No problem" }
];

export function formatHowClosePrompt(prompt: string, name: string) {
  return prompt.replaceAll("{name}", name);
}
