export type ExtraHowCloseQuestion={id:string;category:"everyday"|"food"|"social"|"money"|"adventure"|"competition"|"habits"|"hypothetical";prompt:string;low:string;high:string};
export const HOW_CLOSE_EXTRA_QUESTIONS:ExtraHowCloseQuestion[]=[
{id:"everyday-101",category:"everyday",prompt:"How likely is {name} to arrive early just so they never have to rush?",low:"Usually cutting it close",high:"Early every time"},
{id:"everyday-102",category:"everyday",prompt:"How much would {name} enjoy spending an entire rainy day at home?",low:"Climbing the walls",high:"Ideal day"},
{id:"everyday-103",category:"everyday",prompt:"How likely is {name} to try fixing a small household problem before asking for help?",low:"Ask for help first",high:"I can fix it"},
{id:"everyday-104",category:"everyday",prompt:"How bothered would {name} be by a crooked picture hanging on the wall?",low:"Would not care",high:"Has to fix it"},
{id:"everyday-105",category:"everyday",prompt:"How likely is {name} to change clothes more than once before going out?",low:"First outfit wins",high:"Several changes"},
{id:"everyday-106",category:"everyday",prompt:"How much would {name} enjoy doing absolutely nothing for two hours?",low:"Would get restless",high:"Sounds perfect"},
{id:"everyday-107",category:"everyday",prompt:"How likely is {name} to notice when something in a familiar room has been moved?",low:"Probably would not notice",high:"Immediately notices"},
{id:"everyday-108",category:"everyday",prompt:"How likely is {name} to make the bed every morning?",low:"Almost never",high:"Every morning"},
{id:"everyday-109",category:"everyday",prompt:"How irritated would {name} be if the internet went out for the evening?",low:"No big deal",high:"Very irritated"},
{id:"everyday-110",category:"everyday",prompt:"How likely is {name} to use the last clean cup instead of washing dishes?",low:"Wash first",high:"Grab the last one"},
{id:"everyday-111",category:"everyday",prompt:"How much does {name} enjoy running errands?",low:"Hates errands",high:"Actually enjoys them"},
{id:"everyday-112",category:"everyday",prompt:"How likely is {name} to stop what they are doing to watch a beautiful sunset?",low:"Keep moving",high:"Always stops"},
{id:"everyday-113",category:"everyday",prompt:"How likely is {name} to keep the TV or music on just for background noise?",low:"Prefers quiet",high:"Almost always"},
{id:"everyday-114",category:"everyday",prompt:"How much would {name} enjoy rearranging the furniture just for a fresh look?",low:"Leave it alone",high:"Would love it"},
{id:"everyday-115",category:"everyday",prompt:"How likely is {name} to take a nap on a free afternoon?",low:"Never naps",high:"Definitely napping"},
{id:"everyday-116",category:"everyday",prompt:"How bothered would {name} be by clutter covering the kitchen counter?",low:"Does not care",high:"Clear it now"},
{id:"everyday-117",category:"everyday",prompt:"How likely is {name} to choose stairs instead of an elevator for a few floors?",low:"Elevator every time",high:"Take the stairs"},
{id:"everyday-118",category:"everyday",prompt:"How likely is {name} to hum or sing while doing chores?",low:"Never",high:"Constant soundtrack"},
{id:"everyday-119",category:"everyday",prompt:"How much would {name} enjoy a completely spontaneous day with no schedule?",low:"Needs structure",high:"Would love it"},
{id:"everyday-120",category:"everyday",prompt:"How likely is {name} to keep an old item mainly because it has sentimental value?",low:"Let it go",high:"Keeps meaningful things"},
{id:"everyday-121",category:"everyday",prompt:"How likely is {name} to drive back home to double-check that a door is locked?",low:"Trusts it",high:"Has to check"},
{id:"everyday-122",category:"everyday",prompt:"How much does {name} enjoy grocery shopping?",low:"Get me out",high:"Enjoys the trip"},
{id:"everyday-123",category:"everyday",prompt:"How likely is {name} to open the refrigerator several times hoping something new looks good?",low:"Never",high:"Definitely"},
{id:"everyday-124",category:"everyday",prompt:"How likely is {name} to spend extra time making a gift look nicely wrapped?",low:"Bag and go",high:"Presentation matters"},
{id:"everyday-125",category:"everyday",prompt:"How much would {name} enjoy spending a morning at a farmers market?",low:"Not interested",high:"Love it"},
{id:"everyday-126",category:"everyday",prompt:"How likely is {name} to keep driving with the fuel light on for a while?",low:"Fills up early",high:"Pushes the limit"},
{id:"everyday-127",category:"everyday",prompt:"How likely is {name} to clean up while cooking instead of waiting until the meal is over?",low:"Big cleanup later",high:"Cleans as they go"},
{id:"everyday-128",category:"everyday",prompt:"How much would {name} enjoy waking up with an entire day free and nothing expected of them?",low:"Would feel restless",high:"Dream day"},
{id:"everyday-129",category:"everyday",prompt:"How likely is {name} to choose comfort over style when getting dressed?",low:"Style first",high:"Comfort wins"},
{id:"everyday-130",category:"everyday",prompt:"How likely is {name} to leave a small task until tomorrow even though it would take five minutes now?",low:"Do it now",high:"Tomorrow is fine"},
{id:"everyday-131",category:"everyday",prompt:"How much would {name} enjoy spending an hour browsing a hobby store with no shopping list?",low:"Get in and out",high:"Could wander forever"},
{id:"everyday-132",category:"everyday",prompt:"How likely is {name} to start getting ready much earlier than necessary for an important event?",low:"Last minute",high:"Way ahead of time"},
{id:"food-101",category:"food",prompt:"How likely is {name} to choose sweet over salty for a late-night snack?",low:"Always salty",high:"Always sweet"},
{id:"food-102",category:"food",prompt:"How willing is {name} to eat at a restaurant with a very small menu?",low:"Needs lots of choices",high:"Small menu is fine"},
{id:"food-103",category:"food",prompt:"How likely is {name} to add hot sauce before tasting the food?",low:"Taste first",high:"Adds it immediately"},
{id:"food-104",category:"food",prompt:"How much would {name} enjoy a fancy five-course dinner?",low:"Too much fuss",high:"Would love it"},
{id:"food-105",category:"food",prompt:"How likely is {name} to order an appetizer just for the table?",low:"Skip it",high:"Always get one"},
{id:"food-106",category:"food",prompt:"How disappointed would {name} be if a restaurant ran out of the meal they came to order?",low:"Pick something else",high:"Very disappointed"},
{id:"food-107",category:"food",prompt:"How likely is {name} to eat pizza cold the next morning?",low:"Needs reheating",high:"Cold is great"},
{id:"food-108",category:"food",prompt:"How much does presentation matter to {name} when the food tastes great?",low:"Taste is all that matters",high:"Presentation matters a lot"},
{id:"food-109",category:"food",prompt:"How likely is {name} to order something mainly because it looked good at another table?",low:"Never",high:"That looks good"},
{id:"food-110",category:"food",prompt:"How likely is {name} to finish everything on their plate even when they are full?",low:"Stops when full",high:"Cleans the plate"},
{id:"food-111",category:"food",prompt:"How much would {name} enjoy eating at a food truck instead of a sit-down restaurant?",low:"Prefers a table",high:"Food truck all day"},
{id:"food-112",category:"food",prompt:"How likely is {name} to eat something after the date on the package if it still seems fine?",low:"Throws it out",high:"Probably fine"},
{id:"food-113",category:"food",prompt:"How likely is {name} to choose the local specialty while traveling?",low:"Sticks to favorites",high:"Always tries local"},
{id:"food-114",category:"food",prompt:"How much would {name} enjoy making homemade bread from scratch?",low:"No interest",high:"Would love it"},
{id:"food-115",category:"food",prompt:"How likely is {name} to dip fries in a milkshake?",low:"Never",high:"Absolutely"},
{id:"food-116",category:"food",prompt:"How picky is {name} about a favorite drink being made exactly right?",low:"Anything works",high:"Very particular"},
{id:"food-117",category:"food",prompt:"How likely is {name} to order something they cannot pronounce?",low:"Avoids it",high:"Why not"},
{id:"food-118",category:"food",prompt:"How much would {name} enjoy an all-you-can-eat buffet?",low:"Not appealing",high:"Great idea"},
{id:"food-119",category:"food",prompt:"How likely is {name} to share dessert instead of getting their own?",low:"Own dessert",high:"Happy to share"},
{id:"food-120",category:"food",prompt:"How likely is {name} to save the best-looking bite for last?",low:"Eat it first",high:"Save the best"},
{id:"food-121",category:"food",prompt:"How much would {name} enjoy a meal where every course is a surprise?",low:"Needs to know",high:"Sounds fun"},
{id:"food-122",category:"food",prompt:"How likely is {name} to check restaurant reviews before trying somewhere new?",low:"Just walk in",high:"Checks first"},
{id:"food-123",category:"food",prompt:"How likely is {name} to put a favorite sauce on something other people think should not need it?",low:"Never",high:"Sauce goes everywhere"},
{id:"food-124",category:"food",prompt:"How much would {name} enjoy a cooking competition with friends?",low:"No thanks",high:"Very into it"},
{id:"food-125",category:"food",prompt:"How likely is {name} to grab a snack during a movie even after eating dinner?",low:"Already full",high:"Movie snack required"},
{id:"food-126",category:"food",prompt:"How likely is {name} to eat breakfast food at any time of day?",low:"Breakfast only",high:"Anytime"},
{id:"food-127",category:"food",prompt:"How much would {name} enjoy trying a restaurant chosen entirely by someone else?",low:"Wants a say",high:"Surprise me"},
{id:"food-128",category:"food",prompt:"How likely is {name} to pick a meal based on value for the money rather than what sounds best?",low:"Order what sounds best",high:"Value matters most"},
{id:"food-129",category:"food",prompt:"How likely is {name} to eat the same breakfast several days in a row?",low:"Needs variety",high:"Same thing is fine"},
{id:"food-130",category:"food",prompt:"How adventurous would {name} be at a restaurant serving food from a culture they have never tried?",low:"Very cautious",high:"Bring anything"},
{id:"food-131",category:"food",prompt:"How much would {name} enjoy spending an afternoon at a food festival?",low:"Not interested",high:"Perfect afternoon"},
{id:"food-132",category:"food",prompt:"How likely is {name} to choose a homemade meal over takeout after a long day?",low:"Order takeout",high:"Cook anyway"},
{id:"social-101",category:"social",prompt:"How likely is {name} to introduce themselves first when meeting a new group?",low:"Waits for others",high:"Goes first"},
{id:"social-102",category:"social",prompt:"How comfortable is {name} walking into a crowded event alone?",low:"Very uncomfortable",high:"Totally comfortable"},
{id:"social-103",category:"social",prompt:"How likely is {name} to tell someone they have food in their teeth?",low:"Says nothing",high:"Tells them immediately"},
{id:"social-104",category:"social",prompt:"How likely is {name} to make friends with someone sitting next to them on a long trip?",low:"Keeps to themselves",high:"Probably friends by arrival"},
{id:"social-105",category:"social",prompt:"How much would {name} enjoy being part of a surprise public stunt?",low:"Absolutely not",high:"Sounds great"},
{id:"social-106",category:"social",prompt:"How likely is {name} to correct someone who confidently says something wrong?",low:"Lets it go",high:"Has to correct it"},
{id:"social-107",category:"social",prompt:"How comfortable is {name} asking a stranger for a small favor?",low:"Very uncomfortable",high:"No problem"},
{id:"social-108",category:"social",prompt:"How likely is {name} to finish telling a story after realizing everyone has heard it before?",low:"Stops immediately",high:"Finishes the story"},
{id:"social-109",category:"social",prompt:"How much would {name} enjoy being seated with strangers at a community dinner?",low:"Would hate it",high:"Would enjoy it"},
{id:"social-110",category:"social",prompt:"How likely is {name} to give an honest opinion when a friend asks whether an outfit looks good?",low:"Keeps it gentle",high:"Completely honest"},
{id:"social-111",category:"social",prompt:"How likely is {name} to be the one who keeps a group conversation going?",low:"Lets others lead",high:"Keeps it moving"},
{id:"social-112",category:"social",prompt:"How comfortable is {name} receiving a big public compliment?",low:"Wants to disappear",high:"Loves it"},
{id:"social-113",category:"social",prompt:"How likely is {name} to invite someone new to join the group if they seem left out?",low:"Might not notice",high:"Definitely includes them"},
{id:"social-114",category:"social",prompt:"How likely is {name} to send a message first after meeting someone they liked?",low:"Waits for them",high:"Reaches out first"},
{id:"social-115",category:"social",prompt:"How much would {name} enjoy a reunion with people they have not seen in ten years?",low:"Would rather skip it",high:"Would love it"},
{id:"social-116",category:"social",prompt:"How likely is {name} to admit immediately when they have forgotten someone's name?",low:"Tries to hide it",high:"Just asks again"},
{id:"social-117",category:"social",prompt:"How comfortable is {name} being the only person in a group with a different opinion?",low:"Very uncomfortable",high:"Totally comfortable"},
{id:"social-118",category:"social",prompt:"How likely is {name} to laugh along at a joke they do not understand?",low:"Admits they missed it",high:"Laughs anyway"},
{id:"social-119",category:"social",prompt:"How likely is {name} to start organizing plans when nobody else will make a decision?",low:"Waits it out",high:"Takes over"},
{id:"social-120",category:"social",prompt:"How much would {name} enjoy spending an evening meeting a friend's extended family?",low:"Very uncomfortable",high:"Would enjoy it"},
{id:"social-121",category:"social",prompt:"How likely is {name} to tell a stranger they dropped money or something valuable?",low:"Might hesitate",high:"Immediately"},
{id:"social-122",category:"social",prompt:"How likely is {name} to sing karaoke if the whole table encourages them?",low:"No chance",high:"Grab the microphone"},
{id:"social-123",category:"social",prompt:"How comfortable is {name} eating alone at a restaurant?",low:"Very uncomfortable",high:"Completely fine"},
{id:"social-124",category:"social",prompt:"How likely is {name} to apologize first after an argument?",low:"Waits for the other person",high:"Usually goes first"},
{id:"social-125",category:"social",prompt:"How likely is {name} to keep chatting with someone even when they are ready to leave?",low:"Ends it quickly",high:"Gets stuck talking"},
{id:"social-126",category:"social",prompt:"How much would {name} enjoy hosting out-of-town guests for several days?",low:"Too much",high:"Would love it"},
{id:"social-127",category:"social",prompt:"How likely is {name} to say something when another person cuts in line?",low:"Lets it go",high:"Definitely says something"},
{id:"social-128",category:"social",prompt:"How comfortable is {name} asking for a discount or special accommodation in person?",low:"Very uncomfortable",high:"No problem asking"},
{id:"social-129",category:"social",prompt:"How likely is {name} to follow up on something personal someone told them weeks ago?",low:"Probably forgets",high:"Almost always remembers"},
{id:"social-130",category:"social",prompt:"How much does {name} enjoy friendly teasing from people they know well?",low:"Does not enjoy it",high:"Loves the banter"},
{id:"social-131",category:"social",prompt:"How likely is {name} to introduce two people because they think those people would get along?",low:"Rarely thinks of it",high:"Always connecting people"},
{id:"social-132",category:"social",prompt:"How comfortable is {name} giving a toast at a wedding or celebration?",low:"Terrifying",high:"Hand me the glass"},
{id:"money-101",category:"money",prompt:"How likely is {name} to spend more for something that will probably last twice as long?",low:"Cheapest option",high:"Pays for quality"},
{id:"money-102",category:"money",prompt:"How much would {name} enjoy tracking every dollar they spend for a month?",low:"Would hate it",high:"Would enjoy it"},
{id:"money-103",category:"money",prompt:"How likely is {name} to return an item because they found it cheaper somewhere else?",low:"Not worth the trouble",high:"Definitely returns it"},
{id:"money-104",category:"money",prompt:"How likely is {name} to lend money to a close friend who promises to repay it next month?",low:"Would not lend",high:"Absolutely"},
{id:"money-105",category:"money",prompt:"If {name} unexpectedly got $10,000, how likely are they to spend some of it on a trip?",low:"Save it all",high:"Book the trip"},
{id:"money-106",category:"money",prompt:"How bothered would {name} be by paying a convenience fee to avoid a long line?",low:"Worth it",high:"Refuses the fee"},
{id:"money-107",category:"money",prompt:"How likely is {name} to buy a used item instead of new if the savings are significant?",low:"Prefers new",high:"Used is smart"},
{id:"money-108",category:"money",prompt:"How likely is {name} to keep a gift card for months waiting for the perfect thing?",low:"Spends it quickly",high:"Waits for the right purchase"},
{id:"money-109",category:"money",prompt:"How likely is {name} to walk away from a purchase if the price feels unfair?",low:"Buys it anyway",high:"Walks away"},
{id:"money-110",category:"money",prompt:"How much would {name} enjoy shopping at yard sales or flea markets for a bargain?",low:"No interest",high:"Loves the hunt"},
{id:"money-111",category:"money",prompt:"How likely is {name} to tip extra when service is especially good?",low:"Standard tip",high:"Very generous"},
{id:"money-112",category:"money",prompt:"How likely is {name} to spend money on an experience instead of a physical gift for themselves?",low:"Prefers things",high:"Prefers experiences"},
{id:"money-113",category:"money",prompt:"How uncomfortable would {name} be carrying a large amount of cash?",low:"Totally fine",high:"Very uncomfortable"},
{id:"money-114",category:"money",prompt:"How likely is {name} to cancel a subscription as soon as they realize they are not using it?",low:"Keeps forgetting",high:"Cancels immediately"},
{id:"money-115",category:"money",prompt:"How likely is {name} to choose a cheaper hotel so there is more money for activities?",low:"Hotel matters most",high:"Save for experiences"},
{id:"money-116",category:"money",prompt:"How much would {name} enjoy negotiating at a flea market or yard sale?",low:"Pays the asking price",high:"Loves to bargain"},
{id:"money-117",category:"money",prompt:"How likely is {name} to buy the extended warranty on an expensive purchase?",low:"Never",high:"Usually"},
{id:"money-118",category:"money",prompt:"How likely is {name} to keep receipts just in case?",low:"Throws them away",high:"Keeps them organized"},
{id:"money-119",category:"money",prompt:"How willing is {name} to pay more for a brand they trust?",low:"Brand does not matter",high:"Pays for trusted brands"},
{id:"money-120",category:"money",prompt:"How likely is {name} to spend an unexpected tax refund on something fun?",low:"Save or pay bills",high:"Treat themselves"},
{id:"money-121",category:"money",prompt:"How likely is {name} to choose the cheaper flight even if it leaves at a terrible time?",low:"Pays for convenience",high:"Takes the cheap flight"},
{id:"money-122",category:"money",prompt:"How much would {name} enjoy having a strict monthly fun-money budget?",low:"Would hate the limit",high:"Likes the structure"},
{id:"money-123",category:"money",prompt:"How likely is {name} to spend extra on a really good seat at a concert or game?",low:"Any seat is fine",high:"Good seats matter"},
{id:"money-124",category:"money",prompt:"How likely is {name} to repair something rather than replace it?",low:"Replace it",high:"Fix it first"},
{id:"money-125",category:"money",prompt:"How likely is {name} to donate to a fundraiser when someone they know asks?",low:"Rarely",high:"Almost always"},
{id:"money-126",category:"money",prompt:"How comfortable is {name} discussing money openly with close family?",low:"Very private",high:"Very open"},
{id:"money-127",category:"money",prompt:"How likely is {name} to wait for a sale before buying something they want but do not need?",low:"Buys it now",high:"Waits for the deal"},
{id:"money-128",category:"money",prompt:"How much would {name} enjoy getting a surprise gift that is practical instead of fun?",low:"Would rather have fun",high:"Loves practical gifts"},
{id:"money-129",category:"money",prompt:"How likely is {name} to pay someone else to do a chore they strongly dislike?",low:"Does it themselves",high:"Happy to pay"},
{id:"money-130",category:"money",prompt:"How likely is {name} to keep using a cracked or worn item because it still technically works?",low:"Replace it",high:"Still works"},
{id:"money-131",category:"money",prompt:"How likely is {name} to choose a mystery envelope with either $5 or $500 instead of a guaranteed $100?",low:"Take the $100",high:"Take the mystery"},
{id:"money-132",category:"money",prompt:"How likely is {name} to research a major purchase for days before deciding?",low:"Decides quickly",high:"Researches everything"}
];