import "server-only";

import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { getSupabaseServerClient } from "@/lib/play-point-core/quick-score-supabase";

const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

type Scenario = {
  id: string;
  title: string;
  setup: string;
  choices: string[];
  pick: number;
  required: number[];
};

const SCENARIOS: Scenario[] = [
  {id:"sinking-boat",title:"Sinking Boat",setup:"Your boat is taking on water. You can save only three items before abandoning ship.",choices:["Fresh water","Flare gun","First-aid kit","Fishing rod","Portable speaker","Heavy toolbox"],pick:3,required:[0,1,2]},
  {id:"desert-breakdown",title:"Desert Breakdown",setup:"Your vehicle dies in the desert. Take three things before you start walking toward help.",choices:["Water jug","Sun shade","Signal mirror","Laptop","Cast-iron skillet","Extra shoes"],pick:3,required:[0,1,2]},
  {id:"blizzard-cabin",title:"Blizzard Cabin",setup:"A blizzard knocks out power overnight. Choose three supplies to keep the group safe until morning.",choices:["Blankets","Firewood","Battery radio","Board game","Ice cream","Power drill"],pick:3,required:[0,1,2]},
  {id:"wildfire-evacuation",title:"Wildfire Evacuation",setup:"You have two minutes to leave a wildfire zone. Choose three things for the car.",choices:["Water","Medication kit","Phone charger","Photo albums","Television","Patio furniture"],pick:3,required:[0,1,2]},
  {id:"flooded-town",title:"Flooded Town",setup:"Floodwater is rising and your group has one small rescue boat. Choose three essentials.",choices:["Life jackets","Drinking water","Flashlight","Cooler of soda","Gaming console","Lawn chairs"],pick:3,required:[0,1,2]},
  {id:"power-blackout",title:"City Blackout",setup:"A citywide blackout may last three days. Pick three items to carry home.",choices:["Flashlight","Bottled water","Battery bank","Hair dryer","Table lamp","Frozen pizza"],pick:3,required:[0,1,2]},
  {id:"mountain-rescue",title:"Mountain Rescue",setup:"A hiker is injured above the tree line. Your team can carry only three pieces of gear.",choices:["First-aid kit","Emergency blanket","Satellite beacon","Portable grill","Extra camera lens","Camping stool"],pick:3,required:[0,1,2]},
  {id:"cave-collapse",title:"Cave Collapse",setup:"A cave passage has partially collapsed. Choose three tools before attempting the exit route.",choices:["Headlamps","Rope","Chalk markers","Bluetooth speaker","Deck of cards","Large cooking pot"],pick:3,required:[0,1,2]},
  {id:"jungle-river",title:"Jungle River",setup:"Your raft is damaged deep in the jungle. Pick three things to keep.",choices:["Water purifier","Machete","Emergency beacon","Dress shoes","Book collection","Coffee maker"],pick:3,required:[0,1,2]},
  {id:"island-shelter",title:"Island Shelter",setup:"You are stranded overnight on a small island. Choose three priorities before sunset.",choices:["Build shelter","Find fresh water","Make a signal fire","Collect seashells","Make a volleyball court","Write a journal"],pick:3,required:[0,1,2]},
  {id:"space-oxygen",title:"Oxygen Failure",setup:"A spacecraft loses life support. Choose three systems to restore first.",choices:["Oxygen scrubbers","Power grid","Navigation","Entertainment system","Coffee machine","Cabin lighting"],pick:3,required:[0,1,2]},
  {id:"mars-colony",title:"Mars Colony",setup:"A dust storm damages your colony. Choose three modules to protect.",choices:["Life support","Water recycler","Communications","Gym","Movie archive","Decorative greenhouse"],pick:3,required:[0,1,2]},
  {id:"alien-signal",title:"Alien Signal",setup:"You receive an unknown signal from deep space. Pick three actions before responding.",choices:["Verify the source","Record everything","Alert mission control","Broadcast your location","Delete the logs","Reply immediately"],pick:3,required:[0,1,2]},
  {id:"station-fire",title:"Station Fire",setup:"Fire breaks out on an orbital station. Pick three emergency priorities.",choices:["Seal the section","Evacuate crew","Protect life support","Save the trophy case","Finish dinner","Keep filming"],pick:3,required:[0,1,2]},
  {id:"ai-malfunction",title:"AI Malfunction",setup:"The ship AI begins issuing conflicting commands. Choose three safeguards.",choices:["Isolate its controls","Verify sensor data","Switch critical systems manual","Give it full access","Erase crew logs","Ignore the warnings"],pick:3,required:[0,1,2]},
  {id:"bank-heist",title:"The Getaway",setup:"A fictional heist has gone sideways. Choose the three safest getaway decisions.",choices:["Abandon marked cash","Change vehicles","Split communication channels","Return to the scene","Post online","Take the busiest highway"],pick:3,required:[0,1,2]},
  {id:"museum-heist",title:"Museum Escape",setup:"Security shutters are closing in a fictional caper. Pick three escape priorities.",choices:["Leave bulky loot","Use the planned exit","Destroy fake credentials","Stop for souvenirs","Argue about the split","Call a reporter"],pick:3,required:[0,1,2]},
  {id:"mystery-mansion",title:"Mystery Mansion",setup:"A valuable object disappears during dinner. Choose three places to investigate first.",choices:["Security footage","Guest timeline","Locked study","Garden fountain","Dessert cart","Attic decorations"],pick:3,required:[0,1,2]},
  {id:"missing-key",title:"The Missing Key",setup:"A key vanishes before everyone can leave. Pick three useful next steps.",choices:["Retrace movements","Check shared spaces","Ask who last used it","Search the refrigerator","Order pizza","Blame the newest person"],pick:3,required:[0,1,2]},
  {id:"hotel-mystery",title:"Hotel Mystery",setup:"A guest reports a suspicious noise and missing bag. Choose three leads to follow.",choices:["Door access log","Hallway cameras","Front desk timeline","Pool temperature","Breakfast menu","Lobby music"],pick:3,required:[0,1,2]},
  {id:"road-trip",title:"Road Trip Trouble",setup:"Your car develops a warning light far from home. Pick three smart responses.",choices:["Pull over safely","Check the manual","Call roadside help","Turn the radio louder","Keep speeding","Ignore the temperature gauge"],pick:3,required:[0,1,2]},
  {id:"lost-phone",title:"Lost Phone",setup:"Someone loses a phone in a huge theme park. Choose three first moves.",choices:["Use Find My device","Call the phone","Check lost and found","Buy a new hat","Ride the coaster again","Post the passcode publicly"],pick:3,required:[0,1,2]},
  {id:"wedding-crisis",title:"Wedding Crisis",setup:"The wedding venue loses power an hour before the ceremony. Choose three priorities.",choices:["Contact venue staff","Protect food refrigeration","Set up battery lighting","Rearrange centerpieces","Change the cake flavor","Start karaoke"],pick:3,required:[0,1,2]},
  {id:"restaurant-rush",title:"Restaurant Rush",setup:"A restaurant gets slammed unexpectedly. Choose three actions to stabilize service.",choices:["Simplify the menu","Communicate wait times","Reassign staff","Hide from customers","Add ten specials","Stop taking drink orders"],pick:3,required:[0,1,2]},
  {id:"family-vacation",title:"Vacation Mix-Up",setup:"Your rental house is double-booked late at night. Pick three sensible actions.",choices:["Call the host","Document the booking","Find backup lodging","Sleep in the driveway","Delete the reservation email","Argue with the neighbors"],pick:3,required:[0,1,2]},
  {id:"office-launch",title:"Product Launch",setup:"A major presentation starts in an hour and the demo is broken. Pick three priorities.",choices:["Prepare a backup demo","Tell the team the risk","Test the critical path","Add more features","Hide the bug","Rewrite the whole product"],pick:3,required:[0,1,2]},
  {id:"budget-cut",title:"Budget Crunch",setup:"A small company must reduce spending without damaging its core service. Choose three cuts.",choices:["Unused subscriptions","Nonessential travel","Low-value perks","Customer support","Security backups","Payroll taxes"],pick:3,required:[0,1,2]},
  {id:"event-rain",title:"Festival Rain",setup:"A community festival gets hit by heavy rain. Choose three things to protect first.",choices:["Electrical equipment","Medical tent","Covered evacuation route","Balloon arch","Photo booth props","Prize ribbons"],pick:3,required:[0,1,2]},
  {id:"school-trip",title:"School Trip",setup:"A group gets separated during a museum trip. Choose three actions.",choices:["Contact staff","Return to meeting point","Call the missing group","Keep touring","Leave the building","Post jokes online"],pick:3,required:[0,1,2]},
  {id:"campout",title:"Campout Storm",setup:"A thunderstorm rolls into camp after dark. Choose three safety moves.",choices:["Move away from tall isolated trees","Get into vehicles","Secure loose gear","Stand on the hilltop","Hold metal poles","Keep swimming"],pick:3,required:[0,1,2]},
  {id:"football-final",title:"Final Drive",setup:"Your team trails by four with little time left. Choose three priorities for the drive.",choices:["Protect the quarterback","Manage the clock","Get out of bounds when useful","Burn time intentionally","Use all timeouts immediately","Run backward to create space"],pick:3,required:[0,1,2]},
  {id:"basketball-final",title:"Last Possession",setup:"Tie game, final possession. Choose three things your team should emphasize.",choices:["Get a clean shot","Protect the ball","Know the clock","Force a wild three","Hold the ball past the buzzer","Ignore the hot shooter"],pick:3,required:[0,1,2]},
  {id:"baseball-ninth",title:"Bottom of the Ninth",setup:"One run ties the game with a runner on base. Choose three priorities.",choices:["Advance the runner","Avoid an easy double play","Make contact","Swing at every pitch","Ignore signs","Try a trick play no one practiced"],pick:3,required:[0,1,2]},
  {id:"soccer-extra",title:"Extra Time",setup:"Your team is exhausted in extra time. Choose three strategic priorities.",choices:["Keep defensive shape","Use fresh substitutes","Protect possession","Send everyone forward","Stop communicating","Waste possession"],pick:3,required:[0,1,2]},
  {id:"golf-playoff",title:"Playoff Hole",setup:"You are tied entering a golf playoff. Choose three smart priorities.",choices:["Play the shot you trust","Know the safe miss","Commit to the putt","Try a swing you never practice","Ignore wind","Change clubs mid-swing"],pick:3,required:[0,1,2]},
  {id:"dragon-gate",title:"Dragon at the Gate",setup:"A dragon blocks the only road to your fantasy village. Choose three approaches.",choices:["Learn what it wants","Protect the villagers","Prepare a safe retreat","Insult it loudly","Offer the village treasure blindly","Set your own gate on fire"],pick:3,required:[0,1,2]},
  {id:"cursed-forest",title:"Cursed Forest",setup:"Your party is lost in an enchanted forest. Choose three actions before nightfall.",choices:["Mark your path","Stay together","Follow reliable landmarks","Split into pairs","Eat glowing berries","Chase mysterious voices"],pick:3,required:[0,1,2]},
  {id:"castle-siege",title:"Castle Siege",setup:"A castle is under siege. Choose three defenses to prioritize.",choices:["Secure water","Protect the gates","Maintain communications","Fire the cooks","Open every gate","Use all arrows at once"],pick:3,required:[0,1,2]},
  {id:"magic-artifact",title:"Unstable Artifact",setup:"A magical artifact begins pulsing with dangerous energy. Choose three responses.",choices:["Clear the room","Consult the keeper","Contain it safely","Touch it together","Sell tickets","Throw it in the well"],pick:3,required:[0,1,2]},
  {id:"treasure-map",title:"Treasure Map",setup:"You find a map with three possible routes to buried treasure. Choose three preparations before leaving.",choices:["Verify the map","Pack water","Tell someone your route","Leave at midnight alone","Bring only gold bags","Ignore weather"],pick:3,required:[0,1,2]},
  {id:"alien-dinner",title:"Dinner With Aliens",setup:"Aliens arrive for a first-contact dinner. Choose three things that make the best impression.",choices:["Learn their customs","Offer several food options","Use careful translation","Challenge them to arm wrestling","Serve one mystery dish","Ask for their spaceship keys"],pick:3,required:[0,1,2]},
  {id:"llama-farm",title:"Llama Stampede",setup:"A gate opens at a llama farm and chaos begins. Choose three responses.",choices:["Close outer gates","Move people to safety","Use feed to guide the herd","Start chasing llamas","Open more gates","Set off fireworks"],pick:3,required:[0,1,2]},
  {id:"theme-park",title:"Theme Park Meltdown",setup:"A ride stops and a storm rolls in at the same time. Choose three priorities.",choices:["Secure riders","Follow emergency procedures","Move guests to shelter","Keep selling photos","Start another ride","Turn up the music"],pick:3,required:[0,1,2]},
  {id:"bachelor-party",title:"Bachelor Party Rescue",setup:"Half the group is lost in an unfamiliar city and one phone has 5% battery. Pick three moves.",choices:["Choose a meeting point","Send one clear location","Save battery","Start a group livestream","Keep changing bars","Turn the phone flashlight on permanently"],pick:3,required:[0,1,2]},
  {id:"neighborhood-dog",title:"Runaway Dog",setup:"A neighbor's dog slips out near a busy road. Pick three good responses.",choices:["Block traffic safely","Use treats and a calm voice","Call the owner","Chase it while yelling","Drive beside it honking","Open another gate"],pick:3,required:[0,1,2]},
  {id:"birthday-surprise",title:"Surprise Party Leak",setup:"The guest of honor is about to discover the surprise. Pick three ways to save it.",choices:["Create a believable distraction","Coordinate quietly","Move obvious decorations","Send ten conflicting texts","Cancel everything","Tell them there is definitely no party"],pick:3,required:[0,1,2]},
  {id:"zombie-shelter",title:"Zombie Shelter",setup:"Purely fictional zombies are approaching your shelter. Choose three defenses.",choices:["Secure entrances","Ration supplies","Set a watch schedule","Turn on every light","Play loud music","Leave doors unlocked"],pick:3,required:[0,1,2]},
  {id:"time-machine",title:"Time Machine",setup:"A time machine activates unexpectedly. Pick three rules before anyone uses it.",choices:["Record the departure time","Set a return protocol","Limit interference","Bring lottery numbers","Change major history","Leave no one monitoring"],pick:3,required:[0,1,2]},
  {id:"pirate-ship",title:"Pirate Storm",setup:"Your fictional pirate ship enters a violent storm. Choose three priorities.",choices:["Reef the sails","Secure loose cargo","Keep a lookout","Count treasure","Hold a dance contest","Fire the cannons"],pick:3,required:[0,1,2]},
  {id:"submarine",title:"Submarine Leak",setup:"A research submarine reports a slow leak. Choose three immediate priorities.",choices:["Locate the leak","Isolate the compartment","Begin controlled ascent","Continue the tour","Open another hatch","Turn off depth gauges"],pick:3,required:[0,1,2]},
  {id:"arctic-station",title:"Arctic Station",setup:"An arctic research station loses heat. Pick three priorities.",choices:["Conserve warmth","Restore power","Check everyone for cold stress","Open exterior doors","Take showers","Move supplies outside"],pick:3,required:[0,1,2]},
  {id:"train-delay",title:"Stranded Train",setup:"A train stops for hours in severe weather. Choose three actions for the group.",choices:["Follow crew instructions","Conserve phone batteries","Share reliable updates","Force open doors","Walk the tracks","Spread rumors"],pick:3,required:[0,1,2]},
  {id:"airport-cancel",title:"Airport Cancellation",setup:"Your flight is cancelled and seats on alternatives are disappearing. Choose three moves.",choices:["Join the rebooking queue","Check the airline app","Look at nearby airports","Wait without checking","Book three nonrefundable hotels","Argue with security"],pick:3,required:[0,1,2]},
  {id:"concert-evac",title:"Concert Evacuation",setup:"A venue announces an emergency evacuation. Choose three priorities.",choices:["Follow marked exits","Stay with your group","Help anyone who falls","Run toward the stage","Stop for merchandise","Block the exit filming"],pick:3,required:[0,1,2]},
  {id:"boat-race",title:"Boat Race Trouble",setup:"A racing boat loses engine power near worsening weather. Choose three actions.",choices:["Put on life jackets","Call for assistance","Secure the boat","Keep racing under sail you do not have","Jump overboard","Ignore the forecast"],pick:3,required:[0,1,2]},
  {id:"movie-set",title:"Movie Set Crisis",setup:"A key prop fails minutes before filming. Choose three production priorities.",choices:["Use a safe substitute","Adjust the shot list","Tell the director immediately","Hide the failure","Use unsafe improvisation","Cancel the whole production"],pick:3,required:[0,1,2]},
  {id:"newsroom",title:"Breaking News",setup:"A newsroom gets a huge tip that has not been verified. Choose three steps before publishing.",choices:["Verify with another source","Check primary evidence","Get editorial review","Publish first and fix later","Guess missing details","Ignore corrections"],pick:3,required:[0,1,2]},
  {id:"community-shelter",title:"Community Shelter",setup:"A storm shelter is filling quickly. Choose three priorities.",choices:["Account for people","Organize medical needs","Keep emergency exits clear","Reserve seats for luggage","Turn off all communication","Lock late arrivals outside"],pick:3,required:[0,1,2]},
  {id:"farm-storm",title:"Farm Storm",setup:"A severe storm is ten minutes away. Choose three farm priorities.",choices:["Get people to shelter","Secure animals where safe","Shut down exposed equipment","Mow one more field","Open every barn door","Stand outside watching"],pick:3,required:[0,1,2]},
  {id:"lake-storm",title:"Lake Storm",setup:"Lightning appears while your group is on the lake. Choose three actions.",choices:["Head to shore","Put on life jackets","Avoid exposed high points","Keep swimming","Hold fishing rods overhead","Race the storm"],pick:3,required:[0,1,2]},
];

type Player = { id:string; name:string; tokenHash:string; seat:number; score:number; accusationUsed:boolean };
type Phase = "lobby"|"mission"|"reveal"|"accusation"|"trial"|"finished";
type State = {
  code:string; phase:Phase; hostPlayerId:string; players:Player[]; insideManId:string|null;
  round:number; maxRounds:number; missionOrder:string[]; missionVotes:Record<string,number[]>;
  groupSelection:number[]; missionSuccess:boolean|null; crewPoints:number; sabotagePoints:number;
  privateObjectives:Record<string,string>; personalTargets:Record<string,number>;
  accusations:Record<string,string|null>; trialTargetId:string|null; trialVotes:Record<string,"guilty"|"not_guilty">;
  message:string; winner:"crew"|"inside_man"|null;
};
type Row = { code:string; state:State; version:number };

const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function tokenMatches(expected:string,token:string){const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
function cleanName(v:unknown){const n=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!n||n.length>24)throw new Error("Enter a name up to 24 characters.");return n}
function cleanCode(v:unknown){const c=typeof v==="string"?v.trim().toUpperCase():"";if(!/^[A-Z2-9]{6}$/.test(c))throw new Error("Enter a valid 6-character room code.");return c}
function roomCode(){const b=randomBytes(6);return Array.from(b,x=>ALPHABET[x%ALPHABET.length]).join("")}
function playerToken(){return randomBytes(32).toString("base64url")}
function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function scenarioFor(state:State){const id=state.missionOrder[state.round];return SCENARIOS.find(s=>s.id===id)??SCENARIOS[0]}
async function read(code:string):Promise<Row|null>{const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_inside_man_rooms").select("code,state,version").eq("code",code).maybeSingle();if(error)throw new Error(error.message);return data as Row|null}
async function save(row:Row,state:State){const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_inside_man_rooms").update({state,version:row.version+1,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}).eq("code",row.code).eq("version",row.version).select("code,state,version").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("The room changed. Try again.");return data as Row}
function auth(state:State,id:string,token:string){const p=state.players.find(x=>x.id===id);if(!p||!tokenMatches(p.tokenHash,token))throw new Error("Invalid player session.");return p}
function assignObjectives(state:State){const s=scenarioFor(state);state.privateObjectives={};state.personalTargets={};const bad=s.choices.map((_,i)=>i).filter(i=>!s.required.includes(i));const good=[...s.required];for(const p of state.players){if(p.id===state.insideManId){const target=bad[Math.floor(Math.random()*bad.length)]??bad[0]??0;state.personalTargets[p.id]=target;state.privateObjectives[p.id]=`SABOTAGE: Get “${s.choices[target]}” into the group’s final ${s.pick}.`; }else{const target=good[Math.floor(Math.random()*good.length)]??good[0]??0;state.personalTargets[p.id]=target;state.privateObjectives[p.id]=`PERSONAL OBJECTIVE: Help get “${s.choices[target]}” into the group’s final ${s.pick}.`;}}
}
function project(state:State,viewer:string){const s=scenarioFor(state);const me=state.players.find(p=>p.id===viewer);const showRoles=state.phase==="finished";return{...state,players:state.players.map(({tokenHash:_,...p})=>({...p,role:showRoles?(p.id===state.insideManId?"inside_man":"crew"):undefined})),insideManId:showRoles?state.insideManId:null,missionVotes:state.phase==="reveal"||state.phase==="accusation"||state.phase==="trial"||state.phase==="finished"?state.missionVotes:(state.missionVotes[viewer]?{[viewer]:state.missionVotes[viewer]}:{}),privateObjectives:me?{[viewer]:state.privateObjectives[viewer]??""}:{},personalTargets:{},trialVotes:state.phase==="finished"?state.trialVotes:(state.trialVotes[viewer]?{[viewer]:state.trialVotes[viewer]}:{}),scenario:s,me:me?{id:viewer,isHost:state.hostPlayerId===viewer,role:state.insideManId===viewer?"inside_man":"crew",objective:state.privateObjectives[viewer]??""}:null,submittedCount:Object.keys(state.missionVotes).length,accusedCount:Object.keys(state.accusations).length,trialVoteCount:Object.keys(state.trialVotes).length}}
function resetMission(state:State){state.missionVotes={};state.groupSelection=[];state.missionSuccess=null;state.accusations={};state.trialTargetId=null;state.trialVotes={};assignObjectives(state);state.phase="mission";state.message="Discuss at the table, then lock your private choices."}
function finish(state:State,winner:"crew"|"inside_man",message:string){state.phase="finished";state.winner=winner;state.message=message}

export async function createInsideManRoom(nameValue:unknown){const name=cleanName(nameValue);for(let i=0;i<8;i++){const code=roomCode(),token=playerToken(),id=randomUUID();const state:State={code,phase:"lobby",hostPlayerId:id,players:[{id,name,tokenHash:hash(token),seat:0,score:0,accusationUsed:false}],insideManId:null,round:0,maxRounds:5,missionOrder:shuffle(SCENARIOS.map(s=>s.id)).slice(0,5),missionVotes:{},groupSelection:[],missionSuccess:null,crewPoints:0,sabotagePoints:0,privateObjectives:{},personalTargets:{},accusations:{},trialTargetId:null,trialVotes:{},message:"Invite the table. One of you will secretly work against the group.",winner:null};const s=getSupabaseServerClient();const{error}=await s.from("ppl_inside_man_rooms").insert({code,state,version:1});if(!error)return{code,playerId:id,token,state:project(state,id)}}throw new Error("Unable to create a room.")}
export async function joinInsideManRoom(codeValue:unknown,nameValue:unknown){const code=cleanCode(codeValue),name=cleanName(nameValue),row=await read(code);if(!row)throw new Error("Room not found.");if(row.state.phase!=="lobby")throw new Error("That game has already started.");if(row.state.players.length>=10)throw new Error("That room is full.");const token=playerToken(),id=randomUUID();row.state.players.push({id,name,tokenHash:hash(token),seat:row.state.players.length,score:0,accusationUsed:false});const saved=await save(row,row.state);return{code,playerId:id,token,state:project(saved.state,id)}}
export async function getInsideManRoom(codeValue:unknown,id:string,token:string){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");auth(row.state,id,token);return{state:project(row.state,id)}}

export async function actInsideManRoom(codeValue:unknown,id:string,token:string,action:string,payload:Record<string,unknown>={}){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");const state=row.state;const player=auth(state,id,token);
 if(action==="start"){if(state.hostPlayerId!==id)throw new Error("Only the host can start.");if(state.players.length<4)throw new Error("Inside Man needs at least 4 players.");state.insideManId=shuffle(state.players)[0].id;state.round=0;state.crewPoints=0;state.sabotagePoints=0;state.winner=null;state.players.forEach(p=>{p.score=0;p.accusationUsed=false});resetMission(state)}
 else if(action==="vote"){if(state.phase!=="mission")throw new Error("This mission is not accepting votes.");if(state.missionVotes[id])throw new Error("Your vote is already locked.");const s=scenarioFor(state);const picks=Array.isArray(payload.picks)?payload.picks.map(Number):[];if(picks.length!==s.pick||new Set(picks).size!==s.pick||picks.some(x=>!Number.isInteger(x)||x<0||x>=s.choices.length))throw new Error(`Choose exactly ${s.pick} different options.`);state.missionVotes[id]=picks;state.message=`${Object.keys(state.missionVotes).length}/${state.players.length} votes locked.`;if(Object.keys(state.missionVotes).length===state.players.length){const counts=s.choices.map(()=>0);for(const vote of Object.values(state.missionVotes))for(const idx of vote)counts[idx]++;state.groupSelection=counts.map((count,idx)=>({count,idx})).sort((a,b)=>b.count-a.count||a.idx-b.idx).slice(0,s.pick).map(x=>x.idx).sort((a,b)=>a-b);state.missionSuccess=s.required.every(x=>state.groupSelection.includes(x))&&state.groupSelection.every(x=>s.required.includes(x));if(state.missionSuccess)state.crewPoints++;else state.sabotagePoints++;for(const p of state.players){if(state.groupSelection.includes(state.personalTargets[p.id]))p.score++}state.phase="reveal";state.message=state.missionSuccess?"MISSION SUCCESS — the Crew moved one step closer.":"MISSION FAILED — the Inside Man moved one step closer.";if(state.crewPoints>=3)finish(state,"crew","The Crew completed three missions before the operation collapsed.");else if(state.sabotagePoints>=3)finish(state,"inside_man","The Inside Man sabotaged three missions and broke the operation.")}}
 else if(action==="open_accusations"){if(state.hostPlayerId!==id)throw new Error("Only the host can open accusations.");if(state.phase!=="reveal")throw new Error("Accusations are not ready.");state.phase="accusation";state.accusations={};state.message="Use your one accusation carefully—or keep watching."}
 else if(action==="accuse"){if(state.phase!=="accusation")throw new Error("Accusations are closed.");if(state.accusations[id]!==undefined)throw new Error("Your decision is already locked.");const target=typeof payload.targetId==="string"?payload.targetId:null;if(target&&target===id)throw new Error("You cannot accuse yourself.");if(target&&!state.players.some(p=>p.id===target))throw new Error("Choose a player at this table.");if(target&&player.accusationUsed)throw new Error("You already used your accusation this game.");if(target)player.accusationUsed=true;state.accusations[id]=target;state.message=`${Object.keys(state.accusations).length}/${state.players.length} accusation decisions locked.`;if(Object.keys(state.accusations).length===state.players.length){const tally:Record<string,number>={};for(const targetId of Object.values(state.accusations))if(targetId)tally[targetId]=(tally[targetId]??0)+1;const ranked=Object.entries(tally).sort((a,b)=>b[1]-a[1]);if(ranked.length&&ranked[0][1]>=2&&(ranked.length===1||ranked[0][1]>ranked[1][1])){state.trialTargetId=ranked[0][0];state.trialVotes={};state.phase="trial";state.message=`${state.players.find(p=>p.id===state.trialTargetId)?.name??"A player"} is on trial. Defend yourself aloud.`}else{state.phase="reveal";state.message="No clear accusation reached trial."}}}
 else if(action==="trial_vote"){if(state.phase!=="trial"||!state.trialTargetId)throw new Error("No trial is active.");if(state.trialVotes[id])throw new Error("Your trial vote is locked.");const vote=payload.vote;if(vote!=="guilty"&&vote!=="not_guilty")throw new Error("Choose guilty or not guilty.");state.trialVotes[id]=vote;const eligible=state.players.filter(p=>p.id!==state.trialTargetId);if(Object.keys(state.trialVotes).filter(pid=>pid!==state.trialTargetId).length>=eligible.length){const guilty=eligible.filter(p=>state.trialVotes[p.id]==="guilty").length;const convicted=guilty>eligible.length/2;if(convicted&&state.trialTargetId===state.insideManId)finish(state,"crew","The table exposed the Inside Man.");else if(convicted){state.sabotagePoints++;state.phase="reveal";state.message="Wrong conviction. The Inside Man gains a sabotage point.";if(state.sabotagePoints>=3)finish(state,"inside_man","Three failures—including a wrong conviction—gave the Inside Man the win.")}else{state.phase="reveal";state.message="The table voted NOT GUILTY. The mission continues."}}}
 else if(action==="next"){if(state.hostPlayerId!==id)throw new Error("Only the host can continue.");if(state.phase!=="reveal")throw new Error("Finish the reveal or trial first.");if(state.round+1>=state.maxRounds){if(state.crewPoints>state.sabotagePoints)finish(state,"crew","The Crew survived the full operation with the stronger mission record.");else finish(state,"inside_man","The Inside Man survived the full operation and did enough damage to win.")}else{state.round++;resetMission(state)}}
 else if(action==="restart"){if(state.hostPlayerId!==id)throw new Error("Only the host can restart.");state.phase="lobby";state.insideManId=null;state.round=0;state.missionOrder=shuffle(SCENARIOS.map(s=>s.id)).slice(0,5);state.missionVotes={};state.groupSelection=[];state.missionSuccess=null;state.crewPoints=0;state.sabotagePoints=0;state.privateObjectives={};state.personalTargets={};state.accusations={};state.trialTargetId=null;state.trialVotes={};state.winner=null;state.players.forEach(p=>{p.score=0;p.accusationUsed=false});state.message="Ready for another operation."}
 else throw new Error("Unknown action.");const saved=await save(row,state);return{state:project(saved.state,id)}}
