import "server-only";

import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { getSupabaseServerClient } from "@/lib/play-point-core/quick-score-supabase";

const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

type Scenario = { id:string; title:string; setup:string; choices:string[]; pick:number; required:number[] };

const SCENARIOS: Scenario[] = [
  {id:"sinking-boat",title:"Sinking Boat",setup:"Your damaged boat will stay afloat for about twenty minutes and rescue crews know your general area. Choose the TWO items most likely to keep everyone alive until they find you.",choices:["Fresh water","Flare gun","First-aid kit","Fishing gear","Waterproof blankets","Toolbox"],pick:2,required:[1,4]},
  {id:"desert-breakdown",title:"Desert Breakdown",setup:"Your vehicle dies on a remote desert road. It is 105°F, you have some water, and someone is expected to notice you are late. Choose the ONE plan the group should follow.",choices:["Stay with the vehicle and create shade","Walk toward a gas station you passed an hour ago","Split into two search groups","Wait until sunset, then walk","Follow tire tracks toward the horizon"],pick:1,required:[0]},
  {id:"blizzard-cabin",title:"Blizzard Cabin",setup:"A cabin loses power during a blizzard. The fireplace works, but the indoor temperature is dropping quickly. Choose the TWO priorities for the next hour.",choices:["Move everyone into one insulated room","Start and maintain the fireplace safely","Use the car heater in the attached garage","Open doors periodically to check the storm","Use candles throughout every room","Cook a large meal before food spoils"],pick:2,required:[0,1]},
  {id:"wildfire-evacuation",title:"Wildfire Evacuation",setup:"An evacuation warning becomes an order. You have ten minutes before leaving and the road is already getting crowded. Choose the TWO things that matter most.",choices:["Load family photo boxes","Gather essential medications","Wet down the roof","Leave immediately by the designated route","Pack three days of clothes","Wait for a neighbor before leaving"],pick:2,required:[1,3]},
  {id:"flooded-town",title:"Flooded Town",setup:"Floodwater is rising around your neighborhood and officials tell residents not to drive through standing water. Choose the ONE safest plan.",choices:["Drive the shortest road even though water covers it","Move to the designated higher-ground shelter","Stay downstairs to watch the water level","Walk through the drainage ditch","Use a pickup truck to test each flooded road"],pick:1,required:[1]},
  {id:"mountain-rescue",title:"Mountain Rescue",setup:"A hiker has a serious leg injury above the tree line and weather is deteriorating. Your team can carry only THREE pieces of rescue gear.",choices:["Emergency blanket","Satellite communicator","Compact first-aid kit","Extra climbing shoes","Camp stove","Camera drone"],pick:3,required:[0,1,2]},
  {id:"missing-wallet",title:"The Missing Wallet",setup:"A wallet disappears during a crowded dinner party. Nobody has left yet. Choose the TWO first steps most likely to solve it without turning the room against itself.",choices:["Ask everyone to empty their pockets","Retrace where the owner used it last","Quietly check shared rooms and coat areas","Accuse the person sitting closest","Search every guest's bag","Ask the host whether anything was moved"],pick:2,required:[1,5]},
  {id:"hotel-noise",title:"Hotel Mystery",setup:"At 2 a.m. you hear repeated crashing from the room next door, followed by silence. Choose the ONE best next move.",choices:["Knock on the door yourself","Call the front desk and report exactly what you heard","Post about it in the hotel group chat","Ignore it unless you hear it again","Pull the fire alarm"],pick:1,required:[1]},
  {id:"office-leak",title:"The Office Leak",setup:"Confidential plans appear online hours before a product announcement. Choose the TWO things the team should do before accusing anyone.",choices:["Preserve access logs and file history","Interview the newest employee first","Confirm exactly which documents leaked","Lock every employee out immediately","Search personal phones","Delay the launch without explanation"],pick:2,required:[0,2]},
  {id:"mystery-mansion",title:"Mystery Mansion",setup:"A valuable necklace vanishes between dinner and dessert. Choose the THREE evidence sources that can establish who actually had opportunity.",choices:["Door and hallway camera footage","Guest movement timeline","Who disliked the owner most","Electronic door-access records","Which guest needs money","Who told the strangest story"],pick:3,required:[0,1,3]},
  {id:"runaway-dog",title:"Runaway Dog",setup:"A frightened dog slips its leash beside a busy neighborhood road. Choose the TWO actions most likely to get it back safely.",choices:["Chase it on foot","Slow nearby traffic if it can be done safely","Use familiar treats and a calm voice","Drive behind it with hazard lights","Call several people to surround it","Keep yelling its name from different directions"],pick:2,required:[1,2]},
  {id:"theme-park-search",title:"Separated at the Park",setup:"Your group becomes separated in a huge theme park and one person's phone is dead. Everyone agreed on a meeting point earlier. Choose the TWO best moves.",choices:["Return to the agreed meeting point","Have everyone independently search the park","Notify guest services","Keep moving toward the next ride","Post the missing person's description publicly","Split into pairs and cover different lands"],pick:2,required:[0,2]},
  {id:"wedding-seating",title:"Wedding Table Trouble",setup:"Two relatives who refuse to sit together discover they have adjacent seats ten minutes before dinner. Choose the TWO best ways to fix it without creating a bigger scene.",choices:["Quietly swap one seat with a willing nearby guest","Ask both relatives to work it out at the table","Have a coordinator make the change privately","Move an entire table","Announce a seating mistake to the room","Tell one relative there are no other seats"],pick:2,required:[0,2]},
  {id:"vacation-double-booked",title:"Vacation Mix-Up",setup:"Your rental house is double-booked and another family is already inside. It is late, raining, and both parties have valid confirmations. Choose the ONE best first move.",choices:["Demand the other family leave","Contact the booking platform or host while documenting both reservations","Call police and report trespassing","Find a hotel first and sort it out tomorrow","Offer the other family cash to leave"],pick:1,required:[1]},
  {id:"restaurant-dispute",title:"Dinner Reservation",setup:"A restaurant cannot find your reservation for eight people on a packed Saturday night. Choose the TWO responses most likely to get the group seated without making things worse.",choices:["Show the confirmation calmly","Ask what realistic alternatives they can offer","Insist they remove another party","Call the manager's personal number","Split up and take any open tables without telling staff","Leave a bad review while standing at the host stand"],pick:2,required:[0,1]},
  {id:"surprise-party",title:"Surprise Party Leak",setup:"The guest of honor is heading toward the venue forty minutes early. Choose the ONE move most likely to preserve the surprise.",choices:["Send several people to invent different excuses","Have one trusted person redirect them with a believable errand","Move the entire party to another building","Text them not to come yet","Turn off every light and hope they drive past"],pick:1,required:[1]},
  {id:"road-trip-route",title:"Road Trip Detour",setup:"A major interstate closes ahead. One route is 35 minutes longer but confirmed open; another is shorter but has unverified reports of flooding. Choose the TWO pieces of information that should drive the decision.",choices:["Verified road-closure data","Which route has better restaurants","Current weather and flood warnings","Which driver likes mountain roads","Fuel prices along each route","The route everyone originally voted for"],pick:2,required:[0,2]},
  {id:"neighbor-noise",title:"The Loud Neighbor",setup:"A neighbor's late-night music has kept several homes awake for three nights. Choose the TWO best first responses before escalating the dispute.",choices:["Speak to the neighbor calmly during the day","Post their address online","Agree among affected neighbors on the specific problem","Call authorities without ever speaking to them","Blast music back the next morning","Leave an anonymous threatening note"],pick:2,required:[0,2]},
  {id:"product-launch",title:"Product Launch",setup:"A live customer demo starts in one hour and the newest feature is unstable. Choose the TWO priorities that protect the launch best.",choices:["Prepare a known-good fallback demo","Keep adding fixes until presentation time","Tell the presenting team exactly what is unreliable","Hide the problem unless it crashes","Remove every feature added this month","Cancel the entire event"],pick:2,required:[0,2]},
  {id:"budget-crunch",title:"Budget Crunch",setup:"A small company must cut expenses this quarter without weakening customer service or security. Choose the THREE cuts with the least operational damage.",choices:["Unused software subscriptions","Optional executive travel","Security monitoring","Low-use office perks","Customer support coverage","Automated backups"],pick:3,required:[0,1,3]},
  {id:"final-hire",title:"Final Hire",setup:"Two finalists are equally likable. One has stronger interview chemistry; the other performed clearly better on the job simulation and references. Choose the ONE factor that should break the tie.",choices:["Who the manager enjoyed talking with most","The stronger evidence from job-relevant performance and references","Who asked for less salary","Who lives closer to the office","Who sent the better thank-you note"],pick:1,required:[1]},
  {id:"client-crisis",title:"Angry Client",setup:"A major client reports a serious failure that your team cannot yet reproduce. Choose the TWO immediate responses that build trust while the cause is investigated.",choices:["Acknowledge the impact and assign an owner","Promise it will be fixed within an hour","Collect exact examples and timestamps","Explain why the client probably caused it","Wait until engineering confirms a bug before responding","Offer a refund before understanding the issue"],pick:2,required:[0,2]},
  {id:"restaurant-rush",title:"Restaurant Rush",setup:"A restaurant is suddenly forty minutes behind and the kitchen is overloaded. Choose the THREE moves most likely to stabilize service.",choices:["Temporarily simplify the menu","Give accurate wait times","Add more specials to increase choice","Reassign staff to the bottleneck","Keep seating at the normal pace","Stop communicating delays until they improve"],pick:3,required:[0,1,3]},
  {id:"festival-rain",title:"Festival Rain",setup:"Heavy rain hits an outdoor festival with lightning nearby. Choose the TWO first priorities.",choices:["Protect merchandise tents","Move guests to the established safe shelter areas","Secure electrical equipment and shut down exposed power","Keep the headline act on schedule","Move food vendors closer together","Ask attendees to wait under trees"],pick:2,required:[1,2]},
  {id:"final-drive",title:"Final Drive",setup:"Your football team trails by four with 42 seconds left, one timeout, and the ball near midfield. Choose the ONE offensive priority that matters most.",choices:["Use only sideline throws","Preserve enough time while still attacking for a touchdown","Run the ball on every snap","Use the timeout immediately before the first play","Take a deep shot every play"],pick:1,required:[1]},
  {id:"last-possession",title:"Last Possession",setup:"Tie basketball game, 18 seconds left, and your team has the ball. Choose the ONE best overall approach.",choices:["Shoot immediately before the defense is set","Use the clock to create one high-quality final attempt while protecting against a turnover","Hold the ball until the buzzer","Force the ball to the leading scorer regardless of coverage","Call timeout after every pass"],pick:1,required:[1]},
  {id:"bottom-ninth",title:"Bottom of the Ninth",setup:"Tie baseball game, bottom of the ninth, runner on second, no outs. Choose the ONE offensive goal that best improves the chance of scoring the winning run.",choices:["Advance the runner without giving away unnecessary outs","Swing for a home run regardless of pitch","Attempt a steal on the first pitch no matter the catcher","Take every pitch until two strikes","Have the runner leave early on contact"],pick:1,required:[0]},
  {id:"golf-playoff",title:"Playoff Hole",setup:"You are tied in a golf playoff on a hole with water guarding the right side of the green. Choose the ONE best strategic principle.",choices:["Aim directly at the flag regardless of pin position","Choose the shot and miss that remove the big penalty from play","Change to a new swing thought for extra distance","Match whatever club your opponent hits","Always lay up even from normal scoring range"],pick:1,required:[1]},
  {id:"soccer-extra",title:"Extra Time",setup:"Your soccer team is exhausted in extra time and still tied. Choose the TWO priorities most likely to keep you dangerous without giving the game away.",choices:["Maintain defensive shape","Send every player forward","Use fresh substitutes in high-work-rate positions","Slow every restart deliberately","Stop pressing altogether","Take low-percentage shots early"],pick:2,required:[0,2]},
  {id:"relay-injury",title:"Relay Decision",setup:"A relay runner reports a tightening hamstring during warmups. A healthy alternate is slightly slower but fully prepared. Choose the ONE best team decision.",choices:["Keep the faster runner because the race matters","Use the healthy alternate and protect the injured runner","Let the injured runner decide privately with no coach input","Have both warm up until seconds before the race","Skip the relay"],pick:1,required:[1]},
  {id:"oxygen-failure",title:"Oxygen Failure",setup:"A spacecraft suffers cascading system failures. Oxygen reserves are falling and the ship is drifting off course. Choose the TWO systems to restore first.",choices:["Cabin entertainment","Oxygen scrubbers","Navigation control","Galley refrigeration","Research archive","Interior lighting"],pick:2,required:[1,2]},
  {id:"alien-signal",title:"Alien Signal",setup:"A deep-space probe receives a structured signal that may be artificial. Choose the TWO actions that best preserve evidence before any reply is sent.",choices:["Broadcast Earth's location immediately","Record the raw signal and metadata","Verify the signal independently through other instruments","Translate it and answer before it stops","Delete noisy portions of the recording","Announce first contact publicly"],pick:2,required:[1,2]},
  {id:"ai-malfunction",title:"AI Malfunction",setup:"The ship AI gives two contradictory navigation commands and begins locking crew out of controls. Choose the THREE safeguards to activate.",choices:["Isolate the AI from propulsion controls","Give it broader access so it can self-correct","Verify sensor data independently","Switch critical systems to manual control","Erase all logs to prevent confusion","Continue following whichever command came first"],pick:3,required:[0,2,3]},
  {id:"mars-storm",title:"Mars Dust Storm",setup:"A dust storm will block solar power for two days. Choose the TWO colony systems that receive protected power first.",choices:["Life support","Vehicle charging","Water recycling","Science lab freezers","Gym equipment","External lighting"],pick:2,required:[0,2]},
  {id:"time-machine",title:"Time Machine",setup:"A working time machine can send one person back for ten minutes. Choose the TWO rules that most reduce the chance of losing track of the traveler or changing history accidentally.",choices:["Record exact departure and return coordinates","Allow souvenirs if they are small","Set a strict non-interference rule","Let the traveler improvise if circumstances change","Send them without outside monitoring","Use the trip to test a major historical change"],pick:2,required:[0,2]},
  {id:"space-debris",title:"Debris Field",setup:"A cloud of orbital debris will intersect your station's path. Tracking data gives one maneuver a high-confidence safe corridor and another a slightly shorter burn with uncertain debris coverage. Choose the ONE plan.",choices:["Take the shorter uncertain burn","Use the verified safe-corridor maneuver","Wait until debris is visible","Shut down tracking to save power","Split the difference between both maneuvers"],pick:1,required:[1]},
  {id:"dragon-gate",title:"Dragon at the Gate",setup:"A dragon blocks the only mountain pass but has not attacked anyone. Scouts report it has been taking livestock and guarding an injured hatchling. Choose the ONE first approach.",choices:["Launch an immediate attack","Send a guarded delegation to learn what it needs","Abandon the village","Offer all village treasure without conditions","Try to sneak the entire village past at night"],pick:1,required:[1]},
  {id:"cursed-forest",title:"Cursed Forest",setup:"Your party is lost in an enchanted forest where paths appear to move after sunset. Choose the TWO rules most likely to keep everyone together and oriented.",choices:["Mark each confirmed turn","Split up to cover more ground","Stay together","Follow any light that appears ahead","Change direction whenever someone hears a voice","Move only downhill"],pick:2,required:[0,2]},
  {id:"castle-siege",title:"Castle Siege",setup:"A castle may face a week-long siege. Choose the THREE resources that must be protected before anything else.",choices:["Ceremonial armor","Fresh water supply","Gate and wall defenses","Messenger and signal network","Banquet hall","Royal art collection"],pick:3,required:[1,2,3]},
  {id:"unstable-artifact",title:"Unstable Artifact",setup:"A magical artifact begins emitting heat and causing nearby metal objects to move. Nobody knows why. Choose the TWO first responses.",choices:["Clear nonessential people from the room","Carry it outdoors immediately","Consult the keeper who understands its history","Strike it to interrupt the pulse","Cover it with water","Invite witnesses before it stops"],pick:2,required:[0,2]},
  {id:"treasure-map",title:"Treasure Map",setup:"An old map marks a ruin three days away in rough country. Choose the TWO preparations that most reduce the chance the expedition disappears.",choices:["Verify the map against current landmarks","Travel without telling anyone to protect the secret","Leave a route and return plan with someone reliable","Carry extra empty bags for treasure","Depart at night to save time","Avoid checking the weather so nobody backs out"],pick:2,required:[0,2]},
  {id:"royal-message",title:"The Sealed Message",setup:"Two messengers arrive with contradictory sealed orders, each claiming the other is forged. Choose the ONE action the castle should take first.",choices:["Obey the messenger who arrived first","Verify the seals and authenticate through an independent channel","Detain both messengers indefinitely","Destroy both messages","Follow whichever order is easier"],pick:1,required:[1]},
  {id:"llama-stampede",title:"Llama Stampede",setup:"A gate fails at a llama farm during a crowded family event. The herd is loose but not aggressive. Choose the TWO best responses.",choices:["Have visitors chase the animals toward the barn","Move guests behind a secure barrier","Close outer exits to contain the herd","Start vehicles to herd them from both sides","Scatter feed in several directions","Open another gate to reduce crowding"],pick:2,required:[1,2]},
  {id:"bachelor-party",title:"Bachelor Party Rescue",setup:"Half the group is lost in an unfamiliar city. The only working phone in that half has 5% battery. Choose the TWO moves most likely to reunite everyone.",choices:["Pick one fixed meeting point","Keep calling every thirty seconds","Send one precise location message","Turn on a video livestream","Keep moving toward the hotel while texting updates","Use the flashlight so the group is easier to spot"],pick:2,required:[0,2]},
  {id:"mascot-missing",title:"Missing Mascot",setup:"A school's costume mascot disappears thirty minutes before a rivalry game. Choose the TWO fastest ways to determine whether it was moved, borrowed, or stolen.",choices:["Check who signed out equipment and keys","Search every student's locker","Review the last known location and nearby cameras","Post an accusation against the rival school","Cancel the mascot appearance","Offer a reward before checking storage"],pick:2,required:[0,2]},
  {id:"cookout-rain",title:"Cookout Downpour",setup:"A huge family cookout is hit by a sudden downpour. Food is on the grill, electrical cords run across the patio, and everyone is crowding under one small awning. Choose the TWO first priorities.",choices:["Move people away from exposed electrical equipment","Save the desserts","Shut down and secure unsafe outdoor power","Move the grill into the garage","Cover every table before moving people","Keep cooking so the food is not wasted"],pick:2,required:[0,2]},
  {id:"alien-dinner",title:"Dinner With Aliens",setup:"First contact happens over dinner, and nobody knows whether the visitors can safely eat human food. Choose the TWO best ways to avoid an accidental insult or medical disaster.",choices:["Offer a large plate of the host's favorite food","Use careful translation to ask about dietary needs","Explain ingredients before anything is served","Let them copy what humans eat","Avoid mentioning food differences","Serve one mystery dish as a gesture of trust"],pick:2,required:[1,2]},
  {id:"escape-room",title:"Escape Room Chaos",setup:"A team has eight minutes left in a difficult escape room. Three people are working on the same puzzle while two discovered unopened clues elsewhere. Choose the TWO best team adjustments.",choices:["Assign people to unresolved clue areas","Keep everyone on the hardest puzzle until it breaks","Share discoveries aloud so clues can connect","Hide partial answers to avoid confusion","Start guessing lock combinations","Restart every solved puzzle to check mistakes"],pick:2,required:[0,2]},
  {id:"airport-cancel",title:"Airport Cancellation",setup:"Your flight is cancelled during a regional storm and replacement seats are disappearing. Choose the TWO actions most likely to get you moving without creating duplicate bookings.",choices:["Join the airline's rebooking channel","Book several refundable flights at once without checking rules","Check nearby airports and alternate routes","Wait at the gate for the original flight to return","Drive to another airport before confirming any flight","Call every hotel first"],pick:2,required:[0,2]},
  {id:"stranded-train",title:"Stranded Train",setup:"A train stops between stations during severe winter weather. Crew says tracks are unsafe to walk and updates may take time. Choose the TWO best actions for your group.",choices:["Follow crew instructions and remain aboard","Conserve phone batteries","Open an exterior door for fresh air","Walk the tracks toward the next station","Share unconfirmed social-media reports","Use emergency equipment for comfort"],pick:2,required:[0,1]},
  {id:"missed-port",title:"Missed the Ship",setup:"Your cruise ship departs in ninety minutes, but traffic has stopped twenty miles from port. Choose the TWO things your group should do immediately.",choices:["Contact the cruise line or port agent","Leave luggage in the car and start walking","Confirm realistic alternate transportation and timing","Ask the driver to use the shoulder","Wait until the ship's departure time before calling","Book a flight to the next port before confirming the itinerary"],pick:2,required:[0,2]},
  {id:"lost-luggage",title:"Lost Luggage",setup:"Your checked bag never appears after an international flight. Choose the TWO steps that matter most before leaving the airport.",choices:["File a baggage report with the airline","Buy replacement clothes before reporting it","Confirm the bag tag and delivery contact information","Search baggage belts in other terminals","Post a photo of the baggage claim online","Leave and call tomorrow"],pick:2,required:[0,2]},
  {id:"flat-tire",title:"Roadside Flat",setup:"You get a flat tire at night on a narrow highway shoulder. Choose the TWO priorities before deciding whether to change it yourself.",choices:["Make the vehicle as visible as possible","Begin removing the wheel immediately","Get occupants to the safest available location","Drive slowly on the flat to the next exit","Stand behind the vehicle to warn traffic","Turn off all lights to save the battery"],pick:2,required:[0,2]},
  {id:"missing-passport",title:"Missing Passport",setup:"You discover your passport is missing the morning of an international flight. Choose the TWO first steps that give you the best chance of resolving it correctly.",choices:["Retrace the last verified place you had it","Use a photo of the passport and go straight to security","Contact the airline and appropriate passport authority for options","Borrow a relative's passport","Report it stolen before checking whether it is misplaced","Book a second flight under a nickname"],pick:2,required:[0,2]},
  {id:"community-shelter",title:"Community Shelter",setup:"A storm shelter reaches near capacity as more families arrive. Choose the THREE operating priorities that keep the shelter safest and most functional.",choices:["Keep exits and aisles clear","Track who is present and who has medical needs","Reserve floor space for luggage","Maintain reliable emergency updates","Allow each family to claim a private area","Turn away anyone arriving after the first warning"],pick:3,required:[0,1,3]},
  {id:"generator-priority",title:"Generator Power",setup:"A community center has one generator and can power only TWO circuits during a prolonged outage. Choose the two that should stay on.",choices:["Medical refrigeration","Decorative exterior lighting","Emergency communications and charging station","Kitchen television","Gym air-conditioning","Vending machines"],pick:2,required:[0,2]},
  {id:"water-contamination",title:"Water Warning",setup:"Officials announce possible contamination in the town water supply while tests are pending. Choose the TWO most responsible community responses.",choices:["Share the official advisory and safe-water instructions","Tell everyone the water is definitely poisoned","Provide verified sources for updates","Encourage people to test water by tasting it","Buy all bottled water before neighbors hear","Ignore the warning until illness is confirmed"],pick:2,required:[0,2]},
  {id:"newsroom-tip",title:"Breaking News",setup:"A newsroom receives a sensational anonymous tip with one screenshot and no independent confirmation. Choose the THREE steps required before treating it as publishable fact.",choices:["Verify with an independent source","Confirm the underlying primary evidence","Publish a teaser before competitors","Get editorial review of what is actually known","Fill gaps with likely details","Use the screenshot alone if it looks authentic"],pick:3,required:[0,1,3]},
  {id:"cyber-incident",title:"System Breach",setup:"A company sees unusual logins and one employee computer begins encrypting files. Choose the THREE immediate incident-response priorities.",choices:["Isolate affected systems","Preserve logs and evidence","Delete every suspicious file immediately","Notify the incident-response team","Keep affected machines online so work continues","Post details publicly before confirming scope"],pick:3,required:[0,1,3]},
  {id:"school-trip",title:"School Trip Split",setup:"During a museum field trip, one chaperone realizes three students are not with either assigned group. Choose the TWO first actions.",choices:["Notify museum staff and trip leadership","Send students out in pairs to search","Return remaining students to the established meeting point","Keep the tour moving while one adult searches","Post student names publicly","Wait ten minutes in case they reappear"],pick:2,required:[0,2]},
  {id:"movie-set",title:"Movie Set Crisis",setup:"A mechanical prop fails minutes before filming. The replacement shot can be staged safely, but it will require changing the camera plan. Choose the TWO best production decisions.",choices:["Use the safe substitute","Attempt the original effect manually","Adjust the shot plan around the substitute","Hide the malfunction from the director","Keep testing the failed mechanism during takes","Cancel the entire production day"],pick:2,required:[0,2]},
  {id:"lake-storm",title:"Lake Storm",setup:"Lightning is visible while your group is fishing from a small boat two miles from the launch. Choose the TWO immediate priorities.",choices:["Head toward safe shore or the launch","Keep fishing until thunder is audible","Put on life jackets","Stand to watch the storm direction","Hold rods low and continue trolling","Race another boat back"],pick:2,required:[0,2]},
  {id:"farm-storm",title:"Farm Storm",setup:"A severe thunderstorm warning gives a farm ten minutes before damaging winds arrive. Choose the THREE priorities.",choices:["Get people to proper shelter","Secure animals only where it can be done quickly and safely","Finish moving expensive equipment first","Shut down exposed machinery and power where practical","Open barn doors to equalize pressure","Stand outside to watch the sky"],pick:3,required:[0,1,3]},
];

type Player = { id:string; name:string; tokenHash:string; seat:number; score:number; accusationUsed:boolean };
type Phase = "lobby"|"mission"|"reveal"|"accusation"|"trial"|"finished";
type State = { code:string; phase:Phase; hostPlayerId:string; players:Player[]; insideManId:string|null; round:number; maxRounds:number; missionOrder:string[]; missionVotes:Record<string,number[]>; groupSelection:number[]; missionSuccess:boolean|null; crewPoints:number; sabotagePoints:number; privateObjectives:Record<string,string>; personalTargets:Record<string,number>; accusations:Record<string,string|null>; trialTargetId:string|null; trialVotes:Record<string,"guilty"|"not_guilty">; message:string; winner:"crew"|"inside_man"|null };
type Row = { code:string; state:State; version:number };

const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
function tokenMatches(expected:string,token:string){const a=Buffer.from(hash(token),"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
function cleanName(v:unknown){const n=typeof v==="string"?v.trim().replace(/\s+/g," "):"";if(!n||n.length>24)throw new Error("Enter a name up to 24 characters.");return n}
function cleanCode(v:unknown){const c=typeof v==="string"?v.trim().toUpperCase():"";if(!/^[A-Z2-9]{6}$/.test(c))throw new Error("Enter a valid 6-character room code.");return c}
function roomCode(){const b=randomBytes(6);return Array.from(b,x=>ALPHABET[x%ALPHABET.length]).join("")}
function playerToken(){return randomBytes(32).toString("base64url")}
function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function scenarioFor(state:State){const id=state.missionOrder[state.round];return SCENARIOS.find(s=>s.id===id)??SCENARIOS[0]}
async function read(code:string):Promise<Row|null>{const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_inside_man_rooms").select("code,state,version").eq("code",code).maybeSingle();if(error)throw new Error(error.message);return data as Row|null}
async function save(row:Row,state:State){const s=getSupabaseServerClient();const{data,error}=await s.from("ppl_inside_man_rooms").update({state,version:row.version+1,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()}).eq("code",row.code).eq("version",row.version).select("code,state,version").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("The room changed. Try again.");return data as Row}
function auth(state:State,id:string,token:string){const p=state.players.find(x=>x.id===id);if(!p||!tokenMatches(p.tokenHash,token))throw new Error("Invalid player session.");return p}
function assignObjectives(state:State){const s=scenarioFor(state);state.privateObjectives={};state.personalTargets={};const bad=s.choices.map((_,i)=>i).filter(i=>!s.required.includes(i));for(const p of state.players){if(p.id===state.insideManId){const target=bad[Math.floor(Math.random()*bad.length)]??0;state.personalTargets[p.id]=target;state.privateObjectives[p.id]=`SABOTAGE: Get “${s.choices[target]}” into the group’s final ${s.pick}.`;continue}const suspicious=Math.random()<0.35&&bad.length>0;const pool=suspicious?bad:s.required;const target=pool[Math.floor(Math.random()*pool.length)]??s.required[0]??0;state.personalTargets[p.id]=target;state.privateObjectives[p.id]=suspicious?`SIDE OBJECTIVE: Get “${s.choices[target]}” into the group’s final ${s.pick}. It may not be the safest choice, but earning it gives you a personal point.`:`PERSONAL OBJECTIVE: Help get “${s.choices[target]}” into the group’s final ${s.pick}.`;}}
function project(state:State,viewer:string){const s=scenarioFor(state);const me=state.players.find(p=>p.id===viewer);const showRoles=state.phase==="finished";return{...state,players:state.players.map(({tokenHash:_,...p})=>({...p,role:showRoles?(p.id===state.insideManId?"inside_man":"crew"):undefined})),insideManId:showRoles?state.insideManId:null,missionVotes:state.phase==="reveal"||state.phase==="accusation"||state.phase==="trial"||state.phase==="finished"?state.missionVotes:(state.missionVotes[viewer]?{[viewer]:state.missionVotes[viewer]}:{}),privateObjectives:me?{[viewer]:state.privateObjectives[viewer]??""}:{},personalTargets:{},trialVotes:state.phase==="finished"?state.trialVotes:(state.trialVotes[viewer]?{[viewer]:state.trialVotes[viewer]}:{}),scenario:s,me:me?{id:viewer,isHost:state.hostPlayerId===viewer,role:state.insideManId===viewer?"inside_man":"crew",objective:state.privateObjectives[viewer]??""}:null,submittedCount:Object.keys(state.missionVotes).length,accusedCount:Object.keys(state.accusations).length,trialVoteCount:Object.keys(state.trialVotes).length}}
function resetMission(state:State){state.missionVotes={};state.groupSelection=[];state.missionSuccess=null;state.accusations={};state.trialTargetId=null;state.trialVotes={};assignObjectives(state);state.phase="mission";state.message="Discuss at the table, then lock your private choices."}
function finish(state:State,winner:"crew"|"inside_man",message:string){state.phase="finished";state.winner=winner;state.message=message}

export async function createInsideManRoom(nameValue:unknown){const name=cleanName(nameValue);for(let i=0;i<8;i++){const code=roomCode(),token=playerToken(),id=randomUUID();const state:State={code,phase:"lobby",hostPlayerId:id,players:[{id,name,tokenHash:hash(token),seat:0,score:0,accusationUsed:false}],insideManId:null,round:0,maxRounds:5,missionOrder:shuffle(SCENARIOS.map(s=>s.id)).slice(0,5),missionVotes:{},groupSelection:[],missionSuccess:null,crewPoints:0,sabotagePoints:0,privateObjectives:{},personalTargets:{},accusations:{},trialTargetId:null,trialVotes:{},message:"Invite the table. One of you will secretly work against the group.",winner:null};const s=getSupabaseServerClient();const{error}=await s.from("ppl_inside_man_rooms").insert({code,state,version:1});if(!error)return{code,playerId:id,token,state:project(state,id)}}throw new Error("Unable to create a room.")}
export async function joinInsideManRoom(codeValue:unknown,nameValue:unknown){const code=cleanCode(codeValue),name=cleanName(nameValue),row=await read(code);if(!row)throw new Error("Room not found.");if(row.state.phase!=="lobby")throw new Error("That game has already started.");if(row.state.players.length>=10)throw new Error("That room is full.");const token=playerToken(),id=randomUUID();row.state.players.push({id,name,tokenHash:hash(token),seat:row.state.players.length,score:0,accusationUsed:false});const saved=await save(row,row.state);return{code,playerId:id,token,state:project(saved.state,id)}}
export async function getInsideManRoom(codeValue:unknown,id:string,token:string){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");auth(row.state,id,token);return{state:project(row.state,id)}}

export async function actInsideManRoom(codeValue:unknown,id:string,token:string,action:string,payload:Record<string,unknown>={}){const code=cleanCode(codeValue),row=await read(code);if(!row)throw new Error("Room not found.");const state=row.state;const player=auth(state,id,token);
 if(action==="start"){if(state.hostPlayerId!==id)throw new Error("Only the host can start.");if(state.players.length<4)throw new Error("Inside Man needs at least 4 players.");state.insideManId=shuffle(state.players)[0].id;state.round=0;state.crewPoints=0;state.sabotagePoints=0;state.winner=null;state.players.forEach(p=>{p.score=0;p.accusationUsed=false});resetMission(state)}
 else if(action==="vote"){if(state.phase!=="mission")throw new Error("This mission is not accepting votes.");if(state.missionVotes[id])throw new Error("Your vote is already locked.");const s=scenarioFor(state);const picks=Array.isArray(payload.picks)?payload.picks.map(Number):[];if(picks.length!==s.pick||new Set(picks).size!==s.pick||picks.some(x=>!Number.isInteger(x)||x<0||x>=s.choices.length))throw new Error(`Choose exactly ${s.pick} different options.`);state.missionVotes[id]=picks;state.message=`${Object.keys(state.missionVotes).length}/${state.players.length} votes locked.`;if(Object.keys(state.missionVotes).length===state.players.length){const counts=s.choices.map(()=>0);for(const vote of Object.values(state.missionVotes))for(const idx of vote)counts[idx]++;state.groupSelection=counts.map((count,idx)=>({count,idx})).sort((a,b)=>b.count-a.count||a.idx-b.idx).slice(0,s.pick).map(x=>x.idx).sort((a,b)=>a-b);state.missionSuccess=s.required.every(x=>state.groupSelection.includes(x))&&state.groupSelection.every(x=>s.required.includes(x));if(state.missionSuccess)state.crewPoints++;else state.sabotagePoints++;for(const p of state.players){if(state.groupSelection.includes(state.personalTargets[p.id]))p.score++}state.phase="reveal";state.message=state.missionSuccess?"MISSION SUCCESS — the Crew moved one step closer.":"MISSION FAILED — the Inside Man moved one step closer.";if(state.crewPoints>=3)finish(state,"crew","The Crew completed three missions before the operation collapsed.");else if(state.sabotagePoints>=3)finish(state,"inside_man","The Inside Man sabotaged three missions and broke the operation.")}}
 else if(action==="open_accusations"){if(state.hostPlayerId!==id)throw new Error("Only the host can open accusations.");if(state.phase!=="reveal")throw new Error("Accusations are not ready.");state.phase="accusation";state.accusations={};state.message="Use your one accusation carefully—or keep watching."}
 else if(action==="accuse"){if(state.phase!=="accusation")throw new Error("Accusations are closed.");if(state.accusations[id]!==undefined)throw new Error("Your decision is already locked.");const target=typeof payload.targetId==="string"?payload.targetId:null;if(target&&target===id)throw new Error("You cannot accuse yourself.");if(target&&!state.players.some(p=>p.id===target))throw new Error("Choose a player at this table.");if(target&&player.accusationUsed)throw new Error("You already used your accusation this game.");if(target)player.accusationUsed=true;state.accusations[id]=target;state.message=`${Object.keys(state.accusations).length}/${state.players.length} accusation decisions locked.`;if(Object.keys(state.accusations).length===state.players.length){const tally:Record<string,number>={};for(const targetId of Object.values(state.accusations))if(targetId)tally[targetId]=(tally[targetId]??0)+1;const ranked=Object.entries(tally).sort((a,b)=>b[1]-a[1]);if(ranked.length&&ranked[0][1]>=2&&(ranked.length===1||ranked[0][1]>ranked[1][1])){state.trialTargetId=ranked[0][0];state.trialVotes={};state.phase="trial";state.message=`${state.players.find(p=>p.id===state.trialTargetId)?.name??"A player"} is on trial. Defend yourself aloud.`}else{state.phase="reveal";state.message="No clear accusation reached trial."}}}
 else if(action==="trial_vote"){if(state.phase!=="trial"||!state.trialTargetId)throw new Error("No trial is active.");if(state.trialVotes[id])throw new Error("Your trial vote is locked.");const vote=payload.vote;if(vote!=="guilty"&&vote!=="not_guilty")throw new Error("Choose guilty or not guilty.");state.trialVotes[id]=vote;const eligible=state.players.filter(p=>p.id!==state.trialTargetId);if(Object.keys(state.trialVotes).filter(pid=>pid!==state.trialTargetId).length>=eligible.length){const guilty=eligible.filter(p=>state.trialVotes[p.id]==="guilty").length;const convicted=guilty>eligible.length/2;if(convicted&&state.trialTargetId===state.insideManId)finish(state,"crew","The table exposed the Inside Man.");else if(convicted){state.sabotagePoints++;state.phase="reveal";state.message="Wrong conviction. The Inside Man gains a sabotage point.";if(state.sabotagePoints>=3)finish(state,"inside_man","Three failures—including a wrong conviction—gave the Inside Man the win.")}else{state.phase="reveal";state.message="The table voted NOT GUILTY. The mission continues."}}}
 else if(action==="next"){if(state.hostPlayerId!==id)throw new Error("Only the host can continue.");if(state.phase!=="reveal")throw new Error("Finish the reveal or trial first.");if(state.round+1>=state.maxRounds){if(state.crewPoints>state.sabotagePoints)finish(state,"crew","The Crew survived the full operation with the stronger mission record.");else finish(state,"inside_man","The Inside Man survived the full operation and did enough damage to win.")}else{state.round++;resetMission(state)}}
 else if(action==="restart"){if(state.hostPlayerId!==id)throw new Error("Only the host can restart.");state.phase="lobby";state.insideManId=null;state.round=0;state.missionOrder=shuffle(SCENARIOS.map(s=>s.id)).slice(0,5);state.missionVotes={};state.groupSelection=[];state.missionSuccess=null;state.crewPoints=0;state.sabotagePoints=0;state.privateObjectives={};state.personalTargets={};state.accusations={};state.trialTargetId=null;state.trialVotes={};state.winner=null;state.players.forEach(p=>{p.score=0;p.accusationUsed=false});state.message="Ready for another operation."}
 else throw new Error("Unknown action.");const saved=await save(row,state);return{state:project(saved.state,id)}}
