import { settleLiveCrapsBets, type LiveCrapsBankroll, type LiveCrapsBet, type LiveCrapsBetSettlement } from "./live-craps-bets";
import { liveCrapsAtsCredit, recordLiveCrapsAtsRoll, type LiveCrapsAtsBet, type LiveCrapsAtsState } from "./live-craps-ats";
import { settleLiveCrapsComeBets, type LiveCrapsComeBet, type LiveCrapsComeSettlement } from "./live-craps-come";
import { settleLiveCrapsOdds, type LiveCrapsOddsBet, type LiveCrapsOddsSettlement } from "./live-craps-odds";
import { settleLiveCrapsBuyLay, type LiveCrapsBuyLayBet, type LiveCrapsBuyLaySettlement } from "./live-craps-buy-lay";
import { settleLiveCrapsHardways, type LiveCrapsHardwayBet, type LiveCrapsHardwayReceipt } from "./live-craps-hardways";
import { settlePendingLiveCrapsRoll, submitLiveCrapsRoll, type LiveCrapsTable } from "./live-craps";
import type { LiveCrapsDiceEntry } from "./live-craps-dice-entry";

export type LiveCrapsAtsSettlement = { betId:string; playerId:string; kind:LiveCrapsAtsBet["kind"]; stake:number; status:"won"|"lost"; credit:number; profit:number };
export type LiveCrapsPlayerRollResult = { playerId:string; bankrollBefore:number; bankrollAfter:number; regularCredit:number; regularProfit:number; comeCredit:number; comeProfit:number; oddsCredit:number; oddsProfit:number; buyLayCredit:number; buyLayProfit:number; hardwayCredit:number; hardwayProfit:number; atsCredit:number; atsProfit:number; totalCredit:number; rollProfit:number };
export type LiveCrapsPublicPayout = { playerId:string; playerName:string; seat:number; payout:number; profit:number; result:"won"|"lost"|"push-or-working" };
export type LiveCrapsSettlementState = { table:LiveCrapsTable; bets:LiveCrapsBet[]; comeBets:LiveCrapsComeBet[]; odds:LiveCrapsOddsBet[]; buyLayBets:LiveCrapsBuyLayBet[]; hardwayBets:LiveCrapsHardwayBet[]; bankrolls:LiveCrapsBankroll[]; ats:LiveCrapsAtsState };
export type LiveCrapsSettlementResult = LiveCrapsSettlementState & { roll:{id:string;shooterId:string;die1:number;die2:number;total:number}; regularSettlements:LiveCrapsBetSettlement[]; comeSettlements:LiveCrapsComeSettlement[]; oddsSettlements:LiveCrapsOddsSettlement[]; buyLaySettlements:LiveCrapsBuyLaySettlement[]; hardwaySettlements:LiveCrapsHardwayReceipt[]; atsSettlements:LiveCrapsAtsSettlement[]; playerResults:LiveCrapsPlayerRollResult[]; publicPayouts:LiveCrapsPublicPayout[] };
function atsSettlement(bet:LiveCrapsAtsBet,status:"won"|"lost"):LiveCrapsAtsSettlement { const credit=status==="won"?liveCrapsAtsCredit(bet):0; return {betId:bet.id,playerId:bet.playerId,kind:bet.kind,stake:bet.amount,status,credit,profit:status==="won"?credit-bet.amount:-bet.amount}; }
function sumForPlayer<T extends {playerId:string}>(items:T[],playerId:string,value:(item:T)=>number){return items.reduce((sum,item)=>item.playerId===playerId?sum+value(item):sum,0);}
function addCredits(bankrolls:LiveCrapsBankroll[], receipts:{playerId:string;credit:number}[]){const credits=new Map<string,number>();for(const r of receipts)if(r.credit>0)credits.set(r.playerId,(credits.get(r.playerId)??0)+r.credit);return bankrolls.map(b=>({...b,chips:b.chips+(credits.get(b.playerId)??0)}));}

export function settleConfirmedLiveCrapsPhysicalRoll(state:LiveCrapsSettlementState,entry:LiveCrapsDiceEntry):LiveCrapsSettlementResult{
 if(!entry.confirmed||entry.die1===null||entry.die2===null)throw new Error("Physical dice must be confirmed before settlement.");
 const shooter=state.table.players.find(p=>p.seat===state.table.shooterSeat); if(!shooter||shooter.id!==entry.shooterId)throw new Error("Confirmed dice do not belong to the current shooter."); if(state.ats.shooterId!==entry.shooterId)throw new Error("ATS state does not belong to the current shooter.");
 const before=new Map(state.bankrolls.map(b=>[b.playerId,b.chips])); const pointBefore=state.table.point; const submitted=submitLiveCrapsRoll(state.table,{shooterId:entry.shooterId,die1:entry.die1,die2:entry.die2}); const pending=submitted.pendingRoll!;
 const regular=settleLiveCrapsBets({bets:state.bets,bankrolls:state.bankrolls,total:pending.total,pointBefore});
 const come=settleLiveCrapsComeBets({bets:state.comeBets,bankrolls:regular.bankrolls,total:pending.total});
 const survivingParentIds=new Set<string>([...regular.bets.map(b=>b.id),...come.bets.map(b=>b.id)]);
 const odds=settleLiveCrapsOdds({odds:state.odds,bankrolls:come.bankrolls,total:pending.total,tablePointBefore:pointBefore,survivingParentBetIds:survivingParentIds});
 const buyLay=settleLiveCrapsBuyLay({bets:state.buyLayBets,bankrolls:odds.bankrolls,total:pending.total,tablePointBefore:pointBefore});
 const hardways=settleLiveCrapsHardways({bets:state.hardwayBets,die1:entry.die1,die2:entry.die2,tablePointBefore:pointBefore});
 let afterHardways=addCredits(buyLay.bankrolls,hardways.receipts);
 const atsResult=recordLiveCrapsAtsRoll(state.ats,pending.total); const atsSettlements:LiveCrapsAtsSettlement[]=[...atsResult.wins.map(b=>atsSettlement(b,"won")),...atsResult.losses.map(b=>atsSettlement(b,"lost"))];
 const bankrolls=addCredits(afterHardways,atsSettlements); const table=settlePendingLiveCrapsRoll(submitted); const history=table.history[table.history.length-1]; const nextShooter=table.players.find(p=>p.seat===table.shooterSeat)!; const ats=history.outcome==="seven-out"?{shooterId:nextShooter.id,covered:[],bets:[]}:atsResult.state;
 const playerResults=bankrolls.map(bankroll=>{const id=bankroll.playerId;const regularCredit=sumForPlayer(regular.settlements,id,r=>r.credit),regularProfit=sumForPlayer(regular.settlements,id,r=>r.profit),comeCredit=sumForPlayer(come.settlements,id,r=>r.credit),comeProfit=sumForPlayer(come.settlements,id,r=>r.profit),oddsCredit=sumForPlayer(odds.settlements,id,r=>r.credit),oddsProfit=sumForPlayer(odds.settlements,id,r=>r.profit),buyLayCredit=sumForPlayer(buyLay.settlements,id,r=>r.credit),buyLayProfit=sumForPlayer(buyLay.settlements,id,r=>r.netProfit),hardwayCredit=sumForPlayer(hardways.receipts,id,r=>r.credit),hardwayProfit=sumForPlayer(hardways.receipts,id,r=>r.profit),atsCredit=sumForPlayer(atsSettlements,id,r=>r.credit),atsProfit=sumForPlayer(atsSettlements,id,r=>r.profit);return{playerId:id,bankrollBefore:before.get(id)??bankroll.chips,bankrollAfter:bankroll.chips,regularCredit,regularProfit,comeCredit,comeProfit,oddsCredit,oddsProfit,buyLayCredit,buyLayProfit,hardwayCredit,hardwayProfit,atsCredit,atsProfit,totalCredit:regularCredit+comeCredit+oddsCredit+buyLayCredit+hardwayCredit+atsCredit,rollProfit:regularProfit+comeProfit+oddsProfit+buyLayProfit+hardwayProfit+atsProfit};});
 const publicPayouts=table.players.map(player=>{const r=playerResults.find(x=>x.playerId===player.id)!;return{playerId:player.id,playerName:player.name,seat:player.seat,payout:r.totalCredit,profit:r.rollProfit,result:r.rollProfit>0?"won" as const:r.rollProfit<0?"lost" as const:"push-or-working" as const};}).sort((a,b)=>a.seat-b.seat);
 return {table,bets:regular.bets,comeBets:come.bets,odds:odds.odds,buyLayBets:buyLay.bets,hardwayBets:hardways.bets,bankrolls,ats,roll:{id:history.id,shooterId:history.shooterId,die1:history.die1,die2:history.die2,total:history.total},regularSettlements:regular.settlements,comeSettlements:come.settlements,oddsSettlements:odds.settlements,buyLaySettlements:buyLay.settlements,hardwaySettlements:hardways.receipts,atsSettlements,playerResults,publicPayouts};
}
export function projectLiveCrapsSettlementForPlayer(result:LiveCrapsSettlementResult,playerId:string){const personal=result.playerResults.find(i=>i.playerId===playerId);if(!personal)throw new Error("Player result not found.");return{roll:result.roll,point:result.table.point,shooterSeat:result.table.shooterSeat,atsCovered:[...result.ats.covered],publicPayouts:result.publicPayouts,personal,personalSettlements:result.regularSettlements.filter(r=>r.playerId===playerId),personalComeSettlements:result.comeSettlements.filter(r=>r.playerId===playerId),personalOddsSettlements:result.oddsSettlements.filter(r=>r.playerId===playerId),personalBuyLaySettlements:result.buyLaySettlements.filter(r=>r.playerId===playerId),personalHardwaySettlements:result.hardwaySettlements.filter(r=>r.playerId===playerId),personalAtsSettlements:result.atsSettlements.filter(r=>r.playerId===playerId),personalBets:result.bets.filter(b=>b.playerId===playerId),personalComeBets:result.comeBets.filter(b=>b.playerId===playerId),personalOdds:result.odds.filter(b=>b.playerId===playerId),personalBuyLayBets:result.buyLayBets.filter(b=>b.playerId===playerId),personalHardwayBets:result.hardwayBets.filter(b=>b.playerId===playerId)};}
