import { randomUUID } from "node:crypto";
import { createLiveCrapsRoom, joinLiveCrapsRoom, startLiveCrapsRoom, closeLiveCrapsRoom, projectLiveCrapsRoom, type LiveCrapsRoom } from "./live-craps-room";
import { beginLiveCrapsRoomRoll, initializeLiveCrapsRoomRuntime, settleLiveCrapsRoomPhysicalRoll, settleLiveCrapsRoomVirtualRoll, tickLiveCrapsRoom, type LiveCrapsRoomRuntime } from "./live-craps-room-actions";
import { placeLiveCrapsBet, type LiveCrapsBetKind } from "./live-craps-bets";
import { placeLiveCrapsComeBet, type LiveCrapsComeKind } from "./live-craps-come";
import { placeLiveCrapsOdds, type LiveCrapsOddsParentKind } from "./live-craps-odds";
import { projectCommittedRollForReveal } from "./live-craps-dice-mode";
import type { LiveCrapsPoint } from "./live-craps";

type NewWagerRef={id:string;kind:"regular"|"come"|"odds"};
export type LiveCrapsStoredRoom = { runtime: LiveCrapsRoomRuntime | null; room: LiveCrapsRoom; version: number; updatedAt: string; newWagersByPlayer:Record<string,NewWagerRef[]> };
export type LiveCrapsRoomCommand =
  | { type: "join"; playerId: string; name: string }
  | { type: "start"; actorPlayerId: string; nowMs?: number }
  | { type: "tick"; nowMs?: number }
  | { type: "place-bet"; actorPlayerId: string; kind: LiveCrapsBetKind; amount: number; number?: LiveCrapsPoint }
  | { type: "place-come"; actorPlayerId: string; kind: LiveCrapsComeKind; amount: number }
  | { type: "place-odds"; actorPlayerId: string; parentBetId: string; amount: number }
  | { type: "undo-bet"; actorPlayerId: string }
  | { type: "clear-new-bets"; actorPlayerId: string }
  | { type: "begin-roll"; actorPlayerId: string }
  | { type: "settle-physical"; actorPlayerId: string; die1: number; die2: number; nowMs?: number }
  | { type: "settle-virtual"; actorPlayerId: string; nowMs?: number }
  | { type: "close"; actorPlayerId: string };

const rooms = new Map<string, LiveCrapsStoredRoom>();
const commandResults = new Map<string, LiveCrapsStoredRoom>();
function code(value: string) { return value.trim().toUpperCase(); }
function stamp(nowMs = Date.now()) { return new Date(nowMs).toISOString(); }
function track(wagers:Record<string,NewWagerRef[]>,playerId:string,ref:NewWagerRef){return{...wagers,[playerId]:[...(wagers[playerId]??[]),ref]};}
export function createStoredLiveCrapsRoom(input: Parameters<typeof createLiveCrapsRoom>[0]) { const room = createLiveCrapsRoom(input); if (rooms.has(room.code)) throw new Error("Live Craps room code is already in use."); const stored: LiveCrapsStoredRoom = { room, runtime: null, version: 1, updatedAt: room.createdAt,newWagersByPlayer:{} }; rooms.set(room.code, stored); return stored; }
export function getStoredLiveCrapsRoom(roomCode: string) { const stored = rooms.get(code(roomCode)); if (!stored) throw new Error("Live Craps room not found."); return stored; }
function assertBettingOpen(room: LiveCrapsRoom) { if (room.phase !== "playing") throw new Error("Live Craps must be playing before bets can be changed."); if (room.actionClock.phase !== "post-roll-betting") throw new Error("Betting is closed. Dice are out."); }
function assertActive(room: LiveCrapsRoom, playerId: string) { if (!room.game.table.players.some(p => p.id === playerId && !p.sittingOut)) throw new Error("Active player not found."); }
function placeStandardBet(room: LiveCrapsRoom, command: Extract<LiveCrapsRoomCommand,{type:"place-bet"}>){assertBettingOpen(room);assertActive(room,command.actorPlayerId);const id=`bet-${randomUUID()}`;const placed=placeLiveCrapsBet({bets:room.game.bets,bankrolls:room.game.bankrolls,playerId:command.actorPlayerId,kind:command.kind,amount:command.amount,point:room.game.table.point,number:command.number,id});return{room:{...room,game:{...room.game,bets:placed.bets,bankrolls:placed.bankrolls}},ref:{id,kind:"regular" as const}};}
function placeCome(room:LiveCrapsRoom,command:Extract<LiveCrapsRoomCommand,{type:"place-come"}>){assertBettingOpen(room);assertActive(room,command.actorPlayerId);const id=`come-${randomUUID()}`;const placed=placeLiveCrapsComeBet({bets:room.game.comeBets,bankrolls:room.game.bankrolls,playerId:command.actorPlayerId,kind:command.kind,amount:command.amount,tablePoint:room.game.table.point,id});return{room:{...room,game:{...room.game,comeBets:placed.bets,bankrolls:placed.bankrolls}},ref:{id,kind:"come" as const}};}
function findOddsParent(room: LiveCrapsRoom, playerId:string, parentBetId:string){const line=room.game.bets.find(b=>b.id===parentBetId&&b.playerId===playerId&&(b.kind==="pass-line"||b.kind==="dont-pass"));if(line){if(room.game.table.point===null)throw new Error("Line odds require an established table point.");return{kind:line.kind as LiveCrapsOddsParentKind,point:room.game.table.point,lineAmount:line.amount};}const come=room.game.comeBets.find(b=>b.id===parentBetId&&b.playerId===playerId);if(come){if(come.point===null)throw new Error("Come odds require an established come point.");return{kind:come.kind as LiveCrapsOddsParentKind,point:come.point,lineAmount:come.amount};}throw new Error("Odds must attach to one of your active line or Come wagers.");}
function placeOdds(room:LiveCrapsRoom,command:Extract<LiveCrapsRoomCommand,{type:"place-odds"}>){assertBettingOpen(room);assertActive(room,command.actorPlayerId);const parent=findOddsParent(room,command.actorPlayerId,command.parentBetId);const side=parent.kind==="pass-line"||parent.kind==="come"?"pass":"dont-pass";const id=`odds-${randomUUID()}`;const placed=placeLiveCrapsOdds({odds:room.game.odds,bankrolls:room.game.bankrolls,id,playerId:command.actorPlayerId,parentBetId:command.parentBetId,parentKind:parent.kind,side,point:parent.point,lineAmount:parent.lineAmount,amount:command.amount});return{room:{...room,game:{...room.game,odds:placed.odds,bankrolls:placed.bankrolls}},ref:{id,kind:"odds" as const}};}
function removeRefs(room:LiveCrapsRoom,playerId:string,refs:NewWagerRef[]){assertBettingOpen(room);if(!refs.length)return room;const ids=new Set(refs.map(r=>r.id));const regular=room.game.bets.filter(b=>ids.has(b.id)&&b.playerId===playerId);const come=room.game.comeBets.filter(b=>ids.has(b.id)&&b.playerId===playerId&&b.point===null);const odds=room.game.odds.filter(b=>ids.has(b.id)&&b.playerId===playerId);const owned=[...regular,...come,...odds];if(owned.length!==ids.size)throw new Error("Current betting-window wagers changed and cannot be removed.");const refund=owned.reduce((s,b)=>s+b.amount,0);return{...room,game:{...room.game,bets:room.game.bets.filter(b=>!ids.has(b.id)),comeBets:room.game.comeBets.filter(b=>!ids.has(b.id)),odds:room.game.odds.filter(b=>!ids.has(b.id)),bankrolls:room.game.bankrolls.map(b=>b.playerId===playerId?{...b,chips:b.chips+refund}:b)}};}
export function applyLiveCrapsRoomCommand(roomCode:string,commandId:string,command:LiveCrapsRoomCommand){if(!commandId.trim())throw new Error("Command id is required.");const key=`${code(roomCode)}:${commandId}`;const existing=commandResults.get(key);if(existing)return existing;const stored=getStoredLiveCrapsRoom(roomCode);let room=stored.room;let runtime=stored.runtime;let newWagers=stored.newWagersByPlayer;if(command.type==="join")room=joinLiveCrapsRoom(room,command);else if(command.type==="start"){room=startLiveCrapsRoom(room,command.actorPlayerId);runtime=initializeLiveCrapsRoomRuntime(room,command.nowMs);room=runtime;newWagers={};}else if(command.type==="tick"){if(!runtime)throw new Error("Live Craps has not started.");runtime=tickLiveCrapsRoom(runtime,command.nowMs);room=runtime;}else if(command.type==="place-bet"){const p=placeStandardBet(room,command);room=p.room;newWagers=track(newWagers,command.actorPlayerId,p.ref);}else if(command.type==="place-come"){const p=placeCome(room,command);room=p.room;newWagers=track(newWagers,command.actorPlayerId,p.ref);}else if(command.type==="place-odds"){const p=placeOdds(room,command);room=p.room;newWagers=track(newWagers,command.actorPlayerId,p.ref);}else if(command.type==="undo-bet"){assertBettingOpen(room);const refs=newWagers[command.actorPlayerId]??[];const last=refs.at(-1);if(last)room=removeRefs(room,command.actorPlayerId,[last]);newWagers={...newWagers,[command.actorPlayerId]:refs.slice(0,-1)};}else if(command.type==="clear-new-bets"){assertBettingOpen(room);const refs=newWagers[command.actorPlayerId]??[];room=removeRefs(room,command.actorPlayerId,refs);newWagers={...newWagers,[command.actorPlayerId]:[]};}else if(command.type==="begin-roll"){if(!runtime)throw new Error("Live Craps has not started.");runtime=beginLiveCrapsRoomRoll(runtime,command.actorPlayerId);room=runtime;newWagers={};}else if(command.type==="settle-physical"){if(!runtime)throw new Error("Live Craps has not started.");runtime=settleLiveCrapsRoomPhysicalRoll(runtime,command);room=runtime;}else if(command.type==="settle-virtual"){if(!runtime)throw new Error("Live Craps has not started.");runtime=settleLiveCrapsRoomVirtualRoll(runtime,command.actorPlayerId,command.nowMs);room=runtime;}else if(command.type==="close"){room=closeLiveCrapsRoom(room,command.actorPlayerId);runtime=runtime?{...runtime,phase:"closed"}:null;newWagers={};}if(runtime&&!(["tick","start","begin-roll","settle-physical","settle-virtual","close"] as string[]).includes(command.type)){runtime={...runtime,game:room.game};room=runtime;}const next:LiveCrapsStoredRoom={room,runtime,version:stored.version+1,updatedAt:stamp(command.type==="tick"?command.nowMs:undefined),newWagersByPlayer:newWagers};rooms.set(room.code,next);commandResults.set(key,next);return next;}
export function newLiveCrapsCommandId(){return randomUUID();}
function advanceStoredRoomForRead(roomCode:string,nowMs=Date.now()){const stored=getStoredLiveCrapsRoom(roomCode);const runtime=stored.runtime;if(!runtime||stored.room.phase!=="playing")return stored;const beforePhase=runtime.actionClock.phase;const beforeRolls=runtime.game.table.history.length;const advanced=tickLiveCrapsRoom(runtime,nowMs);if(advanced.actionClock===runtime.actionClock&&advanced.game===runtime.game)return stored;const materiallyChanged=advanced.actionClock.phase!==beforePhase||advanced.game.table.history.length!==beforeRolls;if(!materiallyChanged)return stored;const next:LiveCrapsStoredRoom={...stored,room:advanced,runtime:advanced,version:stored.version+1,updatedAt:stamp(nowMs),newWagersByPlayer:advanced.actionClock.phase==="post-roll-betting"?stored.newWagersByPlayer:{}};rooms.set(code(roomCode),next);return next;}
export function projectStoredLiveCrapsRoom(roomCode:string,playerId:string){const stored=advanceStoredRoomForRead(roomCode);const base={version:stored.version,updatedAt:stored.updatedAt,...projectLiveCrapsRoom(stored.room,playerId),myNewBetCount:(stored.newWagersByPlayer[playerId]??[]).length};const runtime=stored.runtime;const virtualReveal=runtime?.diceMode==="virtual"&&runtime.actionClock.phase==="revealing"&&runtime.committedRoll?{...projectCommittedRollForReveal(runtime.committedRoll),revealAtMs:runtime.revealAtMs,settleAtMs:runtime.settleAtMs}:null;return{...base,virtualReveal,serverNowMs:Date.now()};}
export function clearLiveCrapsRoomStoreForTests(){rooms.clear();commandResults.clear();}
