export type OnMyListQuestion = { id: string; prompt: string; count: 5 | 6 | 7 };

export const ON_MY_LIST_QUESTIONS: readonly OnMyListQuestion[] = [
  {id:"oml-001",count:5,prompt:"Name 5 foods {name} could happily eat every week."},
  {id:"oml-002",count:5,prompt:"Name 5 things that annoy {name} in public."},
  {id:"oml-003",count:5,prompt:"Name 5 places {name} would most like to visit."},
  {id:"oml-004",count:5,prompt:"Name 5 things {name} would grab first if they had to leave home quickly."},
  {id:"oml-005",count:6,prompt:"Name 6 real or fictional people, living or dead, {name} would most want to invite to dinner."},
  {id:"oml-006",count:5,prompt:"Name 5 things {name} would want on a deserted island."},
  {id:"oml-007",count:5,prompt:"Name 5 ways {name} would spend a completely free Saturday."},
  {id:"oml-008",count:5,prompt:"Name 5 things that can instantly put {name} in a better mood."},
  {id:"oml-009",count:5,prompt:"Name 5 restaurant foods {name} has a hard time passing up."},
  {id:"oml-010",count:5,prompt:"Name 5 things {name} would buy first after winning $10,000."},
  {id:"oml-011",count:5,prompt:"Name 5 jobs {name} thinks they would actually enjoy doing."},
  {id:"oml-012",count:5,prompt:"Name 5 things {name} is most likely to forget when leaving the house."},
  {id:"oml-013",count:5,prompt:"Name 5 songs or artists {name} would put on a road-trip playlist."},
  {id:"oml-014",count:5,prompt:"Name 5 things {name} would hate to give up for a month."},
  {id:"oml-015",count:5,prompt:"Name 5 stores {name} could easily spend an hour browsing."},
  {id:"oml-016",count:5,prompt:"Name 5 things {name} would want in their dream backyard."},
  {id:"oml-017",count:5,prompt:"Name 5 things {name} would do with an unexpected day off."},
  {id:"oml-018",count:5,prompt:"Name 5 foods {name} would never choose if other options were available."},
  {id:"oml-019",count:5,prompt:"Name 5 things {name} is unusually picky about."},
  {id:"oml-020",count:5,prompt:"Name 5 things {name} would pack for a weekend getaway."},
  {id:"oml-021",count:5,prompt:"Name 5 celebrities {name} would recognize immediately."},
  {id:"oml-022",count:5,prompt:"Name 5 things {name} would do if the power went out all evening."},
  {id:"oml-023",count:5,prompt:"Name 5 things {name} likes having within reach while watching TV."},
  {id:"oml-024",count:5,prompt:"Name 5 things that make {name} lose patience quickly."},
  {id:"oml-025",count:5,prompt:"Name 5 things {name} would be willing to wake up very early for."},
  {id:"oml-026",count:5,prompt:"Name 5 things {name} would put in their perfect game room."},
  {id:"oml-027",count:5,prompt:"Name 5 things {name} would miss most on a week without their phone."},
  {id:"oml-028",count:5,prompt:"Name 5 snacks {name} would choose for a movie night."},
  {id:"oml-029",count:5,prompt:"Name 5 things {name} would want someone else to handle on vacation."},
  {id:"oml-030",count:5,prompt:"Name 5 things {name} would be excited to find at a yard sale."},
  {id:"oml-031",count:5,prompt:"Name 5 things {name} would want to learn instantly if they could."},
  {id:"oml-032",count:5,prompt:"Name 5 things {name} would do during a perfect summer evening."},
  {id:"oml-033",count:5,prompt:"Name 5 household chores {name} dislikes the most."},
  {id:"oml-034",count:5,prompt:"Name 5 things {name} would order at a breakfast restaurant."},
  {id:"oml-035",count:5,prompt:"Name 5 things {name} would bring to a family cookout."},
  {id:"oml-036",count:5,prompt:"Name 5 things {name} would want to be famous for."},
  {id:"oml-037",count:5,prompt:"Name 5 things {name} would spend extra money to get the better version of."},
  {id:"oml-038",count:5,prompt:"Name 5 things {name} would rather repair than replace."},
  {id:"oml-039",count:5,prompt:"Name 5 things {name} would put on a bucket list."},
  {id:"oml-040",count:5,prompt:"Name 5 things {name} would do first after arriving at the beach."},
  {id:"oml-041",count:5,prompt:"Name 5 things {name} would want in a dream kitchen."},
  {id:"oml-042",count:5,prompt:"Name 5 things {name} is most likely to complain about on a long road trip."},
  {id:"oml-043",count:5,prompt:"Name 5 things {name} would choose for a last-minute takeout order."},
  {id:"oml-044",count:5,prompt:"Name 5 things {name} would do if they suddenly had an extra $500."},
  {id:"oml-045",count:5,prompt:"Name 5 things {name} would want at their ideal birthday celebration."},
  {id:"oml-046",count:5,prompt:"Name 5 things {name} would rather do outside than inside."},
  {id:"oml-047",count:5,prompt:"Name 5 things {name} would take on a camping trip."},
  {id:"oml-048",count:5,prompt:"Name 5 things {name} would want to change about a bad hotel room."},
  {id:"oml-049",count:5,prompt:"Name 5 things {name} would happily pay someone else to do."},
  {id:"oml-050",count:5,prompt:"Name 5 things {name} would look forward to at a county fair."},
  {id:"oml-051",count:5,prompt:"Name 5 things {name} would want in the car for a six-hour drive."},
  {id:"oml-052",count:5,prompt:"Name 5 things {name} would do if they could not use the internet all day."},
  {id:"oml-053",count:5,prompt:"Name 5 things {name} would want to improve about their home."},
  {id:"oml-054",count:5,prompt:"Name 5 things {name} would choose at an all-you-can-eat buffet."},
  {id:"oml-055",count:5,prompt:"Name 5 things {name} would want to see on a trip across America."},
  {id:"oml-056",count:5,prompt:"Name 5 things {name} would buy if they had to spend $1,000 today."},
  {id:"oml-057",count:5,prompt:"Name 5 things {name} would want nearby during a rainy day at home."},
  {id:"oml-058",count:5,prompt:"Name 5 things {name} would be most excited to get for free for life."},
  {id:"oml-059",count:5,prompt:"Name 5 things {name} would want to do on their dream vacation."},
  {id:"oml-060",count:5,prompt:"Name 5 things {name} would miss most if they moved far away."},
  {id:"oml-061",count:6,prompt:"Name 6 things that make {name} laugh."},
  {id:"oml-062",count:6,prompt:"Name 6 things {name} would put in the perfect tailgate setup."},
  {id:"oml-063",count:6,prompt:"Name 6 things {name} would want stocked in the refrigerator at all times."},
  {id:"oml-064",count:6,prompt:"Name 6 things {name} would do if they won a free week off with all expenses paid."},
  {id:"oml-065",count:7,prompt:"Name 7 things {name} would want if they were stuck at home for a snow day."},
  {id:"oml-066",count:7,prompt:"Name 7 foods {name} would put on their ultimate comfort-food menu."},
  {id:"oml-067",count:6,prompt:"Name 6 living people {name} would most want to invite to dinner."},
  {id:"oml-068",count:6,prompt:"Name 6 people from history {name} would most want to invite to dinner."},
] as const;

export function formatOnMyListPrompt(prompt: string, name: string) { return prompt.replaceAll("{name}", name); }
