export type OnMyListReunionQuestion = { id: string; prompt: string };

export const ON_MY_LIST_REUNION_QUESTIONS: readonly OnMyListReunionQuestion[] = [
  { id: "reunion-001", prompt: "List 5 people from your Huntland school years {name} would most like to catch up with tonight." },
  { id: "reunion-002", prompt: "List 5 people from Huntland {name} would choose for a weekend road trip today." },
  { id: "reunion-003", prompt: "List 5 people from those school years {name} remembers as being the funniest." },
  { id: "reunion-004", prompt: "List 5 people from Huntland {name} would want sitting around a fire telling stories tonight." },
  { id: "reunion-005", prompt: "List 5 people from school {name} would want on their team for a reunion competition." },
  { id: "reunion-006", prompt: "List 5 people from the Huntland years {name} wishes they had stayed in better contact with." },
  { id: "reunion-007", prompt: "List 5 people from those years {name} would most enjoy having dinner with today." },
  { id: "reunion-008", prompt: "List 5 people from Huntland {name} would trust to organize the next reunion." },
  { id: "reunion-009", prompt: "List 5 people from school {name} thinks could still keep everybody laughing until midnight." },
  { id: "reunion-010", prompt: "List 5 people from those years {name} would want with them if they got stranded somewhere." },
  { id: "reunion-011", prompt: "List 5 people from Huntland {name} would choose for one more night out like the old days." },
  { id: "reunion-012", prompt: "List 5 people from school {name} would most like to hear tell their favorite old story." },
  { id: "reunion-013", prompt: "List 5 people from the Huntland years {name} thinks they could recognize instantly after not seeing them for decades." },
  { id: "reunion-014", prompt: "List 5 people from school {name} thinks have changed the least." },
  { id: "reunion-015", prompt: "List 5 people from those years {name} would most want at their table tonight." },
  { id: "reunion-016", prompt: "List 5 songs from the late '80s or early '90s {name} would still turn up today." },
  { id: "reunion-017", prompt: "List 5 artists or bands from those years {name} would put on the reunion playlist." },
  { id: "reunion-018", prompt: "List 5 songs {name} thinks would immediately take everybody back to their school years." },
  { id: "reunion-019", prompt: "List 5 things from the late '80s or early '90s {name} wishes would make a comeback." },
  { id: "reunion-020", prompt: "List 5 things from that era {name} is perfectly happy leaving in the past." },
  { id: "reunion-021", prompt: "List 5 things {name} thinks were better when they were growing up than they are today." },
  { id: "reunion-022", prompt: "List 5 things {name} thinks are much better today than they were growing up." },
  { id: "reunion-023", prompt: "List 5 things teenagers have today {name} wishes they had had in school." },
  { id: "reunion-024", prompt: "List 5 things from the school years {name} thinks teenagers today would have trouble understanding." },
  { id: "reunion-025", prompt: "List 5 things people did before cell phones {name} thinks kids today would find hard to believe." },
  { id: "reunion-026", prompt: "List 5 things from those years {name} would put in a Huntland time capsule." },
  { id: "reunion-027", prompt: "List 5 things {name} would want to do if they could spend one day as a teenager again." },
  { id: "reunion-028", prompt: "List 5 things about being a teenager {name} absolutely would NOT want to experience again." },
  { id: "reunion-029", prompt: "List 5 things {name} appreciates now that they didn't appreciate when they were 18." },
  { id: "reunion-030", prompt: "List 5 pieces of advice {name} would give their 18-year-old self." },
  { id: "reunion-031", prompt: "List 5 things {name} would tell today's Huntland students not to worry so much about." },
  { id: "reunion-032", prompt: "List 5 things {name} would tell today's Huntland students to take more seriously." },
  { id: "reunion-033", prompt: "List 5 things {name} thought would matter a lot when they were young that don't seem nearly as important now." },
  { id: "reunion-034", prompt: "List 5 things {name} didn't think much about when they were young that matter a lot now." },
  { id: "reunion-035", prompt: "List 5 things about getting older {name} never expected when they graduated." },
  { id: "reunion-036", prompt: "List 5 things {name} enjoys more now than they did when they were young." },
  { id: "reunion-037", prompt: "List 5 things {name} could do easily at 18 that would probably hurt tomorrow if they tried tonight." },
  { id: "reunion-038", prompt: "List 5 things {name} is glad nobody had a camera phone around to record during the school years." },
  { id: "reunion-039", prompt: "List 5 things {name} thinks would have gotten the Huntland crowd in trouble if social media had existed." },
  { id: "reunion-040", prompt: "List 5 things {name} thinks were more fun because nobody had a cell phone." },
  { id: "reunion-041", prompt: "List 5 places around Huntland {name} would enjoy visiting again just for the memories." },
  { id: "reunion-042", prompt: "List 5 things {name} associates with growing up around Huntland." },
  { id: "reunion-043", prompt: "List 5 things about going to a small K-12 school {name} thinks someone from a big school wouldn't understand." },
  { id: "reunion-044", prompt: "List 5 things about growing up in a small community {name} appreciates more now." },
  { id: "reunion-045", prompt: "List 5 things {name} liked about knowing kids several grades older or younger at school." },
  { id: "reunion-046", prompt: "List 5 things {name} remembers being part of everyday life at Huntland School." },
  { id: "reunion-047", prompt: "List 5 school activities, sports, clubs, or events {name} would most enjoy seeing again." },
  { id: "reunion-048", prompt: "List 5 things {name} would want included in a perfect Huntland reunion." },
  { id: "reunion-049", prompt: "List 5 foods or drinks {name} thinks belong at a great reunion." },
  { id: "reunion-050", prompt: "List 5 things {name} would put on the soundtrack for one perfect night back in their school years." },
  { id: "reunion-051", prompt: "List 5 things {name} would want in the car for one more Friday night with old friends." },
  { id: "reunion-052", prompt: "List 5 things {name} remembers being excited about on a Friday when they were young." },
  { id: "reunion-053", prompt: "List 5 things {name} would spend money on if someone handed them $100 and sent them back to 1991 for one night." },
  { id: "reunion-054", prompt: "List 5 things {name} would want to show their teenage self about their life today." },
  { id: "reunion-055", prompt: "List 5 things about their life today {name} thinks would surprise their teenage self the most." },
  { id: "reunion-056", prompt: "List 5 things {name} thinks their teenage self would be proud of today." },
  { id: "reunion-057", prompt: "List 5 things {name} thinks their teenage self would laugh at them for today." },
  { id: "reunion-058", prompt: "List 5 things {name} thought they would have figured out by this age but still hasn't." },
  { id: "reunion-059", prompt: "List 5 things {name} knows now that they wish they had known back then." },
  { id: "reunion-060", prompt: "List 5 things {name} would tell the younger generation are worth slowing down and enjoying." },
  { id: "reunion-061", prompt: "List 5 things {name} would want everyone from the old Huntland days to do together tonight." },
  { id: "reunion-062", prompt: "List 5 things {name} hopes people talk about before the reunion is over." },
  { id: "reunion-063", prompt: "List 5 things {name} thinks always happen when old friends get back together." },
  { id: "reunion-064", prompt: "List 5 things {name} thinks can make people feel 18 again for a few minutes." },
  { id: "reunion-065", prompt: "List 5 things {name} would want everybody to remember about the Huntland years." },
  { id: "reunion-066", prompt: "List 5 things {name} hopes haven't changed about the people they grew up with." },
  { id: "reunion-067", prompt: "List 5 things {name} hopes HAVE changed since everyone was a teenager." },
  { id: "reunion-068", prompt: "List 5 things {name} thinks the group will still laugh about at the 50-year reunion." },
  { id: "reunion-069", prompt: "List 5 things {name} hopes everyone is still able to do together at the 50-year reunion." },
  { id: "reunion-070", prompt: "List 5 reasons {name} thinks it's worth getting old friends back together after 35 years." },
] as const;
