export const ON_MY_LIST_EXTRA_QUESTIONS = [
{id:"oml-251",prompt:"List things {name} would always make room for in the grocery cart."},
{id:"oml-252",prompt:"List smells {name} really likes."},
{id:"oml-069",prompt:"List foods {name} thinks are overrated."},
{id:"oml-070",prompt:"List drinks {name} reaches for most often."},
{id:"oml-071",prompt:"List desserts {name} would have trouble turning down."},
{id:"oml-072",prompt:"List foods {name} would choose for a midnight snack."},
{id:"oml-073",prompt:"List meals {name} would be happy to eat on their birthday."},
{id:"oml-074",prompt:"List foods {name} likes better homemade than from a restaurant."},
{id:"oml-075",prompt:"List toppings {name} would put on their ideal pizza."},
{id:"oml-076",prompt:"List foods {name} would want at a backyard cookout."},
{id:"oml-077",prompt:"List things {name} would order from an ice cream shop."},
{id:"oml-078",prompt:"List foods {name} would want someone to bring them when they are sick."},
{id:"oml-079",prompt:"List things {name} would put on the table for a game-day spread."},
{id:"oml-080",prompt:"List foods {name} would be willing to drive out of the way to get."},
{id:"oml-081",prompt:"List restaurants or restaurant types {name} is almost always willing to visit."},
{id:"oml-082",prompt:"List breakfast foods {name} would choose first."},
{id:"oml-083",prompt:"List things {name} would want in a perfect sandwich."},
{id:"oml-084",prompt:"List foods {name} would want at a holiday meal."},
{id:"oml-085",prompt:"List snacks {name} tends to finish faster than they planned."},
{id:"oml-086",prompt:"List foods {name} would happily eat straight from the refrigerator."},
{id:"oml-087",prompt:"List places {name} would choose for a long weekend."},
{id:"oml-088",prompt:"List places {name} would revisit without hesitation."},
{id:"oml-089",prompt:"List states or countries {name} would most like to explore."},
{id:"oml-090",prompt:"List things {name} wants a vacation hotel to have."},
{id:"oml-091",prompt:"List things {name} would do on the first day of a cruise."},
{id:"oml-092",prompt:"List places {name} would stop on a cross-country road trip."},
{id:"oml-093",prompt:"List things {name} would pack first for a beach vacation."},
{id:"oml-094",prompt:"List things {name} would pack first for a mountain trip."},
{id:"oml-095",prompt:"List vacation activities {name} would actually look forward to."},
{id:"oml-096",prompt:"List things that can ruin a trip for {name}."},
{id:"oml-097",prompt:"List things {name} likes to do before leaving for a trip."},
{id:"oml-098",prompt:"List places {name} would rather drive to than fly to."},
{id:"oml-100",prompt:"List travel expenses {name} is willing to splurge on."},
{id:"oml-101",prompt:"List things {name} would photograph on vacation."},
{id:"oml-102",prompt:"List places {name} would choose for a quiet getaway."},
{id:"oml-103",prompt:"List things {name} would want to try in a city they had never visited."},
{id:"oml-104",prompt:"List places {name} would enjoy visiting with the whole family."},
{id:"oml-106",prompt:"List things {name} would never want to forget on a trip."},
{id:"oml-108",prompt:"List household projects {name} would actually enjoy doing."},
{id:"oml-109",prompt:"List things {name} would change first in a new house."},
{id:"oml-110",prompt:"List things {name} wants their home to feel like."},
{id:"oml-111",prompt:"List rooms or spaces {name} would most like to upgrade."},
{id:"oml-112",prompt:"List things {name} always notices when visiting someone else's home."},
{id:"oml-113",prompt:"List things {name} would want in a dream garage or workshop."},
{id:"oml-114",prompt:"List things {name} would keep if they had to downsize dramatically."},
{id:"oml-115",prompt:"List things {name} would throw away during a serious decluttering day."},
{id:"oml-117",prompt:"List things {name} would want near their favorite chair."},
{id:"oml-118",prompt:"List things {name} would put on the walls of a room that was completely theirs."},
{id:"oml-120",prompt:"List things {name} would want in a dream bathroom."},
{id:"oml-121",prompt:"List things {name} would want in a dream bedroom."},
{id:"oml-122",prompt:"List things {name} would fix immediately if money were no object."},
{id:"oml-123",prompt:"List things {name} likes to keep unusually organized."},
{id:"oml-124",prompt:"List things {name} tends to leave lying around."},
{id:"oml-125",prompt:"List things {name} would save first from their house if everyone was already safe."},
{id:"oml-126",prompt:"List things that make a house feel comfortable to {name}."},
{id:"oml-127",prompt:"List hobbies {name} would like to spend more time doing."},
{id:"oml-129",prompt:"List things {name} could talk about for an hour without preparation."},
{id:"oml-130",prompt:"List activities that make {name} lose track of time."},
{id:"oml-131",prompt:"List things {name} would try if they knew they could not fail."},
{id:"oml-132",prompt:"List things {name} would enjoy collecting."},
{id:"oml-133",prompt:"List hobbies {name} thinks look fun but has never seriously tried."},
{id:"oml-134",prompt:"List things {name} would want lessons for."},
{id:"oml-135",prompt:"List things {name} would build or make if they had the tools and time."},
{id:"oml-136",prompt:"List outdoor activities {name} enjoys most."},
{id:"oml-137",prompt:"List indoor activities {name} enjoys most."},
{id:"oml-138",prompt:"List sports {name} enjoys watching or playing."},
{id:"oml-139",prompt:"List games {name} would be happy to play tonight."},
{id:"oml-140",prompt:"List things {name} does when they need to unwind."},
{id:"oml-142",prompt:"List creative things {name} would enjoy learning."},
{id:"oml-143",prompt:"List things {name} would like to get better at this year."},
{id:"oml-144",prompt:"List activities {name} would rather do with friends than alone."},
{id:"oml-145",prompt:"List activities {name} would rather do alone than with a crowd."},
{id:"oml-146",prompt:"List things {name} would enter a friendly competition for."},
{id:"oml-148",prompt:"List things that can put {name} in a bad mood quickly."},
{id:"oml-149",prompt:"List things {name} finds surprisingly relaxing."},
{id:"oml-150",prompt:"List little things that make {name} feel appreciated."},
{id:"oml-152",prompt:"List things that make {name} feel proud."},
{id:"oml-153",prompt:"List things that make {name} feel nostalgic."},
{id:"oml-154",prompt:"List things {name} is more sentimental about than people might expect."},
{id:"oml-157",prompt:"List things {name} takes more seriously than most people do."},
{id:"oml-158",prompt:"List things {name} is competitive about."},
{id:"oml-160",prompt:"List things {name} is stubborn about."},
{id:"oml-161",prompt:"List situations where {name} is most likely to speak up."},
{id:"oml-162",prompt:"List things {name} does when they are nervous."},
{id:"oml-163",prompt:"List things that help {name} reset after a rough day."},
{id:"oml-164",prompt:"List things {name} considers a really good day."},
{id:"oml-165",prompt:"List things {name} would choose over having more money."},
{id:"oml-166",prompt:"List things {name} values more now than they did ten years ago."},
{id:"oml-167",prompt:"List qualities {name} respects most in another person."},
{id:"oml-168",prompt:"List qualities that make {name} trust someone."},
{id:"oml-169",prompt:"List things friends can count on {name} for."},
{id:"oml-170",prompt:"List things {name} appreciates most in a close friend."},
{id:"oml-171",prompt:"List things {name} likes doing with family."},
{id:"oml-172",prompt:"List things {name} would plan for a perfect family day."},
{id:"oml-173",prompt:"List traditions {name} would hate to see disappear."},
{id:"oml-174",prompt:"List things {name} remembers most from childhood."},
{id:"oml-176",prompt:"List things {name} thinks make someone a good parent."},
{id:"oml-177",prompt:"List things {name} thinks make someone a good friend."},
{id:"oml-178",prompt:"List things {name} would do to cheer up someone they care about."},
{id:"oml-179",prompt:"List things {name} enjoys celebrating with other people."},
{id:"oml-180",prompt:"List kinds of people {name} enjoys being around."},
{id:"oml-181",prompt:"List things that make {name} feel welcome somewhere."},
{id:"oml-182",prompt:"List things {name} would want people to remember about them."},
{id:"oml-183",prompt:"List things {name} would rather receive than an expensive gift."},
{id:"oml-184",prompt:"List things {name} enjoys giving to other people."},
{id:"oml-185",prompt:"List occasions {name} thinks are worth making a big deal about."},
{id:"oml-186",prompt:"List people {name} would call first with really good news."},
{id:"oml-187",prompt:"List movies {name} could watch again without complaining."},
{id:"oml-188",prompt:"List TV shows {name} would recommend to somebody."},
{id:"oml-189",prompt:"List kinds of music {name} is usually in the mood for."},
{id:"oml-190",prompt:"List songs that would get {name} singing along."},
{id:"oml-191",prompt:"List movies that made a big impression on {name}."},
{id:"oml-192",prompt:"List fictional characters {name} really likes."},
{id:"oml-193",prompt:"List celebrities {name} would actually enjoy meeting."},
{id:"oml-194",prompt:"List books, podcasts, or shows {name} has learned something from."},
{id:"oml-195",prompt:"List kinds of videos {name} is likely to watch online."},
{id:"oml-196",prompt:"List songs {name} would put on when they need energy."},
{id:"oml-197",prompt:"List songs or artists {name} would choose for a quiet evening."},
{id:"oml-198",prompt:"List movies {name} thinks everyone should see at least once."},
{id:"oml-199",prompt:"List TV or movie genres {name} almost always gives a chance."},
{id:"oml-202",prompt:"List fictional worlds {name} would be willing to visit for a day."},
{id:"oml-203",prompt:"List concerts or live events {name} would be excited to attend."},
{id:"oml-204",prompt:"List things {name} likes to have on while doing chores or driving."},
{id:"oml-205",prompt:"List purchases under $50 that make {name} unusually happy."},
{id:"oml-208",prompt:"List things {name} thinks people waste too much money on."},
{id:"oml-209",prompt:"List things {name} would spend more on if money were no concern."},
{id:"oml-210",prompt:"List things {name} would never spend a lot of money on."},
{id:"oml-211",prompt:"List stores or websites {name} has trouble browsing without wanting something."},
{id:"oml-212",prompt:"List things {name} would buy used without hesitation."},
{id:"oml-213",prompt:"List things {name} strongly prefers buying new."},
{id:"oml-214",prompt:"List things {name} would save up for rather than finance."},
{id:"oml-215",prompt:"List things {name} considers worth paying for convenience."},
{id:"oml-216",prompt:"List things {name} would do first after winning a million dollars."},
{id:"oml-217",prompt:"List things {name} would still keep doing even if they became wealthy."},
{id:"oml-218",prompt:"List things {name} would stop doing immediately if they became wealthy."},
{id:"oml-219",prompt:"List things {name} would happily spend gift-card money on."},
{id:"oml-221",prompt:"List things {name} would want with them during a long power outage."},
{id:"oml-222",prompt:"List things {name} would do first if their phone disappeared for a week."},
{id:"oml-223",prompt:"List things {name} would grab if they had ten minutes to prepare for a storm."},
{id:"oml-224",prompt:"List things {name} would want if they were stuck in an airport overnight."},
{id:"oml-225",prompt:"List things {name} would want if their car broke down far from home."},
{id:"oml-227",prompt:"List things {name} would do if every store and restaurant closed for a day."},
{id:"oml-228",prompt:"List things {name} would want if they had to live in a tiny cabin for a month."},
{id:"oml-229",prompt:"List things {name} would bring if they could only take one suitcase for a month."},
{id:"oml-231",prompt:"List things {name} would want during a twelve-hour road closure."},
{id:"oml-232",prompt:"List things {name} would do if they accidentally had the whole house to themselves for a weekend."},
{id:"oml-233",prompt:"List things {name} would choose if they could only keep ten possessions."},
{id:"oml-234",prompt:"List things {name} would do first if they moved to a town where they knew nobody."},
{id:"oml-235",prompt:"List things {name} would want if they had to spend a week off-grid."},
{id:"oml-236",prompt:"List things {name} would prioritize if they had only one hour of free time each day."},
{id:"oml-237",prompt:"List things {name} would do if they could relive one ordinary day from the past."},
{id:"oml-238",prompt:"List things {name} would choose if they had to give up five conveniences for a year."},
{id:"oml-240",prompt:"List accomplishments {name} would feel especially proud to achieve."},
{id:"oml-241",prompt:"List things {name} hopes to have more time for in the future."},
{id:"oml-242",prompt:"List places {name} would like to take someone they love someday."},
{id:"oml-243",prompt:"List things {name} would like to teach somebody else."},
{id:"oml-244",prompt:"List things {name} hopes never change about their life."},
{id:"oml-245",prompt:"List things {name} would like to improve before their next big birthday."},
{id:"oml-246",prompt:"List experiences {name} thinks are better than owning more stuff."},
{id:"oml-247",prompt:"List things {name} wants to be better known for."},
{id:"oml-249",prompt:"List things {name} would most like to make more memories doing."},
{id:"oml-250",prompt:"List things {name} would call part of a life well lived."},
{id:"oml-253",prompt:"List things from the past {name} wishes would make a comeback."},
{id:"oml-254",prompt:"List things from growing up {name} is perfectly happy leaving in the past."},
{id:"oml-255",prompt:"List things young people have today {name} wishes had existed when they were growing up."},
{id:"oml-256",prompt:"List things people did before smartphones that {name} thinks younger people would find hard to believe."},
{id:"oml-257",prompt:"List things about being a teenager {name} would not want to experience again."},
{id:"oml-258",prompt:"List pieces of advice {name} would give their younger self."},
{id:"oml-259",prompt:"List things {name} thought mattered a lot when they were younger that matter much less now."},
{id:"oml-260",prompt:"List things about getting older that have surprised {name}."},
{id:"oml-261",prompt:"List things {name} could do easily when younger that would probably hurt tomorrow now."},
{id:"oml-262",prompt:"List things from their younger years {name} is glad were never captured on a camera phone or social media."},
{id:"oml-263",prompt:"List things about their life today that would surprise {name}'s younger self."},
] as const;
