create table if not exists public.ppl_game_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  game_sku text not null,
  provider text not null check (provider in ('web_checkout', 'apple_iap', 'google_play', 'manual', 'founder', 'bundle')),
  provider_transaction_id text not null,
  provider_original_transaction_id text,
  status text not null default 'purchased' check (status in ('purchased', 'refunded', 'revoked', 'expired')),
  purchased_at timestamptz not null default now(),
  revoked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ppl_game_purchases_game_sku_format check (game_sku ~ '^[a-z0-9][a-z0-9._-]{2,79}$'),
  constraint ppl_game_purchases_provider_transaction_unique unique (provider, provider_transaction_id)
);

create index if not exists ppl_game_purchases_user_game_idx
  on public.ppl_game_purchases (user_id, game_sku)
  where user_id is not null;

create index if not exists ppl_game_purchases_original_transaction_idx
  on public.ppl_game_purchases (provider, provider_original_transaction_id)
  where provider_original_transaction_id is not null;

alter table public.ppl_game_purchases enable row level security;
revoke all on table public.ppl_game_purchases from anon, authenticated;
grant all on table public.ppl_game_purchases to service_role;

comment on table public.ppl_game_purchases is
  'Provider-neutral purchase ledger. Entitlements remain the access projection; account deletion anonymizes the user link while preserving transaction history needed for refunds/restores.';
