create table if not exists public.ppl_game_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_sku text not null,
  status text not null default 'active' check (status in ('active', 'revoked', 'expired')),
  source text not null default 'manual',
  granted_at timestamptz not null default now(),
  expires_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint ppl_game_entitlements_user_game_unique unique (user_id, game_sku),
  constraint ppl_game_entitlements_game_sku_format check (game_sku ~ '^[a-z0-9][a-z0-9._-]{2,79}$')
);

create index if not exists ppl_game_entitlements_user_status_idx
  on public.ppl_game_entitlements (user_id, status);

alter table public.ppl_game_entitlements enable row level security;
revoke all on table public.ppl_game_entitlements from anon, authenticated;
grant all on table public.ppl_game_entitlements to service_role;
