"use client";

import { useCallback, useEffect, useState } from "react";
import { RoomJoinPanel } from "@/app/games/_components/RoomJoinPanel";

type Player={id:string;name:string;score:number;seat:number};
type Game={code:string;status:"lobby"|"playing"|"finished";hostPlayerId:string;players:Player[];round:number;maxRounds:number;answers:Record<string,number>;revealed:boolean;average:number|null;sameBrain:boolean;message:string;currentPrompt:string|null;answeredCount:number;me:{id:string;isHost:boolean}};
type Session={code:string;playerId:string;token:string};
const KEY="pps-how-close-session";

export function HowCloseClient(){
 const[game,setGame]=useState<Game|null>(null),[session,setSession]=useState<Session|null>(null),[name,setName]=useState(""),[code,setCode]=useState(""),[value,setValue]=useState(50),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const request=useCallback(async(url:string,init?:RequestInit)=>{const r=await fetch(url,{...init,cache:"no-store",headers:{"content-type":"application/json",...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Something went wrong.");return j},[]);
 const store=(s:Session,g:Game)=>{localStorage.setItem(KEY,JSON.stringify(s));setSession(s);setGame(g)};
 useEffect(()=>{const q=new URLSearchParams(location.search).get("code");if(q)setCode(q.toUpperCase());try{const raw=localStorage.getItem(KEY);if(raw)setSession(JSON.parse(raw))}catch{}},[]);
 const refresh=useCallback(async()=>{if(!session)return;try{const j=await request(`/api/games/how-close/${session.code}?playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);setGame(j.state)}catch{}},[request,session]);
 useEffect(()=>{if(!session)return;refresh();const t=setInterval(refresh,1200);return()=>clearInterval(t)},[session,refresh]);
 async function open(intent:"create"|"join"){setBusy(true);setError("");try{const j=await request("/api/games/how-close",{method:"POST",body:JSON.stringify({intent,name,code})});store({code:j.code,playerId:j.playerId,token:j.token},j.state);history.replaceState(null,"",`/games/how-close?code=${j.code}`)}catch(e){setError(e instanceof Error?e.message:"Unable to join.")}finally{setBusy(false)}}
 async function act(action:string,payload:Record<string,unknown>={}){if(!session)return;setBusy(true);setError("");try{const j=await request(`/api/games/how-close/${session.code}`,{method:"POST",body:JSON.stringify({...session,action,payload})});setGame(j.state)}catch(e){setError(e instanceof Error?e.message:"Try again.")}finally{setBusy(false)}}
 const answered=!!(session&&game?.answers[session.playerId]!==undefined);const joinUrl=game&&typeof window!=="undefined"?`${window.location.origin}/games/how-close?code=${game.code}`:"";
 if(!game)return <main className="px-5 py-10 sm:px-8"><div className="mx-auto max-w-xl rounded-[32px] border border-violet-300/20 bg-violet-300/[0.06] p-7"><div className="text-xs font-black uppercase tracking-[.24em] text-violet-200">Play Point Family Games</div><h1 className="mt-3 text-5xl font-black tracking-tight text-white">How Close Are We?</h1><p className="mt-4 leading-7 text-white/65">Everyone answers the same 1–100 question privately. Then find out how similarly your table thinks.</p><input className="mt-7 w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-lg text-white" placeholder="Your first name" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} onClick={()=>open("create")} className="mt-3 w-full rounded-2xl bg-violet-300 px-5 py-4 font-black text-slate-950">CREATE FAMILY GAME</button><div className="my-5 text-center text-xs font-black uppercase tracking-widest text-white/35">or join a table</div><input className="w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-4 text-center text-xl font-black uppercase tracking-[.3em] text-white" placeholder="ROOM CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button disabled={busy} onClick={()=>open("join")} className="mt-3 w-full rounded-2xl border border-white/15 px-5 py-4 font-black text-white">JOIN GAME</button>{error&&<p className="mt-4 text-sm text-rose-200">{error}</p>}</div></main>;
 return <main className="px-4 py-7 sm:px-8"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-violet-200">How Close Are We?</div><div className="mt-1 text-sm text-white/50">Room <b className="text-white">{game.code}</b></div></div><div className="text-right text-xs text-white/45">{game.status==="lobby"?"Lobby":`Round ${Math.min(game.round+1,game.maxRounds)} of ${game.maxRounds}`}</div></header>
 <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{game.players.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="truncate text-sm font-bold text-white">{p.name}{p.id===session?.playerId?" · You":""}</div><div className="mt-1 text-2xl font-black text-violet-100">{p.score}</div></div>)}</div>
 {game.status==="lobby"&&<section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black text-white">Get everyone in fast</h2><p className="mt-2 text-sm leading-6 text-white/60">Scan, type a first name, join. Only the host needs an account.</p><RoomJoinPanel code={game.code} joinUrl={joinUrl} gameName="How Close Are We?"/>{game.me.isHost?<button disabled={busy||game.players.length<2} onClick={()=>act("start")} className="mt-3 w-full rounded-2xl bg-violet-300 px-4 py-4 font-black text-slate-950 disabled:opacity-40">START GAME</button>:<p className="mt-4 text-center text-sm text-white/50">Waiting for the host to start…</p>}</section>}
 {game.status==="playing"&&<><section className="mt-6 rounded-[30px] border border-violet-300/15 bg-violet-300/[.06] p-6 text-center"><div className="text-xs font-black uppercase tracking-[.22em] text-white/45">Rate it from 1 to 100</div><h2 className="mt-4 text-2xl font-black leading-tight text-white sm:text-3xl">{game.currentPrompt}</h2><p className="mt-3 text-sm text-white/55">{game.message}</p></section>{!game.revealed?<section className="mt-4 rounded-[28px] border border-white/10 bg-white/[.035] p-6">{answered?<div className="text-center"><div className="text-sm font-black uppercase tracking-widest text-violet-200">Locked in</div><div className="mt-2 text-5xl font-black text-white">{game.answers[session!.playerId]}</div><p className="mt-3 text-sm text-white/50">Waiting for {game.players.length-game.answeredCount} more.</p></div>:<><div className="text-center text-6xl font-black text-white">{value}</div><input aria-label="Your answer from 1 to 100" type="range" min="1" max="100" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-6 w-full"/><div className="mt-2 flex justify-between text-xs font-bold text-white/35"><span>1</span><span>100</span></div><button disabled={busy} onClick={()=>act("answer",{value})} className="mt-5 w-full rounded-2xl bg-violet-300 px-4 py-4 font-black text-slate-950">LOCK IN {value}</button></>}</section>:<section className="mt-4 rounded-[28px] border border-emerald-300/20 bg-emerald-300/10 p-6"><div className="text-center text-xs font-black uppercase tracking-widest text-emerald-100">{game.sameBrain?"SAME BRAIN!":"TABLE REVEAL"}</div><div className="mt-2 text-center text-5xl font-black text-white">{game.average}</div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{game.players.map(p=><div key={p.id} className="rounded-2xl bg-black/20 p-3 text-center"><div className="text-sm font-bold text-white/65">{p.name}</div><div className="mt-1 text-3xl font-black text-white">{game.answers[p.id]}</div></div>)}</div>{game.me.isHost?<button disabled={busy} onClick={()=>act("next")} className="mt-5 w-full rounded-2xl bg-white px-4 py-4 font-black text-slate-950">{game.round+1>=game.maxRounds?"SEE FINAL SCORE":"NEXT QUESTION"}</button>:<p className="mt-4 text-center text-sm text-white/50">Talk it over while the host moves to the next question.</p>}</section>}</>}
 {game.status==="finished"&&<section className="mt-6 rounded-[28px] border border-emerald-300/20 bg-emerald-300/10 p-6 text-center"><div className="text-xs font-black uppercase tracking-widest text-emerald-100">Final table score</div><h2 className="mt-2 text-3xl font-black text-white">{[...game.players].sort((a,b)=>b.score-a.score)[0]?.name} knows this table best!</h2><div className="mt-5 space-y-2">{[...game.players].sort((a,b)=>b.score-a.score).map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-2xl bg-black/20 px-4 py-3"><span className="font-bold text-white">{i+1}. {p.name}</span><span className="text-xl font-black text-emerald-100">{p.score}</span></div>)}</div>{game.me.isHost&&<button onClick={()=>act("restart")} className="mt-5 rounded-2xl bg-white px-5 py-3 font-black text-slate-950">PLAY AGAIN</button>}</section>}{error&&<p className="mt-4 text-center text-sm text-rose-200">{error}</p>}</div></main>;
}
